name: "Install dependencies"
description: "Install dependencies required by the runner"
inputs:
  runner-version:
    description: "The os and version of the runner used to execute the tests"
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - uses: azure/setup-kubectl@v1
      with:
        version: 'v1.19.3'
      id: kubectl
    - if: inputs.runner-version == 'ubuntu-latest'
      name: install ${{ inputs.runner-version }} dependencies
      shell: bash
      run: |
        sudo rm -f /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y sshfs socat
        sudo sh -c 'echo user_allow_other >> /etc/fuse.conf'
