run:
  build-tags:
    - citest

issues:
  # Give me the full output
  max-same-issues: 0

  # Use the default excludes...
  exclude-use-default: false
  # ...but also add some of our own
  exclude:
    - Error return value of `(\w+\.)+(Close|Flush|Remove|(Un)?Setenv|(Fp|P)rint(f|ln))\` is not checked
    - 'structtag: struct field \w+ repeats json tag'
    - 'Subprocess launched with function call as argument or cmd arguments'
  exclude-rules:
    - path: _test\.go
      linters:
        - const
        - dupl
        - gochecknoglobals
        - goconst
        - golint
        - lll
        - unparam

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages-with-error-message:
      - os/exec:                    "Use `github.com/datawire/dlib/dexec` instead of `os/exec`"
      - github.com/golang/protobuf: "Use `google.golang.org/protobuf` instead of `github.com/golang/protobuf`"
      - github/datawire/dlib/dutil: "Use either `github/datawire/dlib/derror` or `github/datawire/dlib/dhttp` instead of `github/datawire/dlib/dutil`"
      - golang.org/x/net/http2/h2c: "Use `github/datawire/dlib/dhttp` instead of `golang.org/x/net/http2/h2c`"

  gocyclo:
    min-complexity: 35

  gocognit:
    min-complexity: 60

  goimports:
    # A comma-separated list
    local-prefixes: github.com/telepresenceio,github.com/datawire

  lll:
    line-length: 180
    tab-width: 2

  misspell:
    ignore-words:
      - mosquitto

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goimports # temporarily use 'goimports' instead of 'gci' https://github.com/daixiang0/gci/pull/33
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - structcheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

  # don't enable:
  # - dupl
  # - funlen
  # - gochecknoglobals
  # - gochecknoinits
  # - goconst
  # - godox
  # - goimports # use gci instead
  # - golint
  # - gosec
  # - interfacer
  # - maligned # is premature-optimization
  # - stylecheck
  # - unparam
