run:
  build-tags:
    - citest
  modules-download-mode: readonly

issues:
  # Give me the full output
  max-same-issues: 0

  # Use the default excludes...
  exclude-use-default: false
  # ...but also add some of our own
  exclude:
    - Error return value of `(\w+\.)+(Close|Flush|Remove|(Un)?Setenv|(Fp|P)rint(f|ln))\` is not checked
    - 'structtag: struct field \w+ repeats json tag'
    - 'Subprocess launched with function call as argument or cmd arguments'
  exclude-rules:
    - path: _test\.go
      linters:
        - const
        - dupl
        - gochecknoglobals
        - goconst
        - golint
        - lll
        - unparam

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages-with-error-message:
      - io/ioutil:                         "`io/ioutil` is deprecated in Go 1.16, use `io` or `os` instead"
      - os/exec:                           "Use `github.com/datawire/dlib/dexec` instead of `os/exec`"
      - syscall:                           "Use `golang.org/x/sys/...` instead of `syscall`"
      - github.com/golang/protobuf:        "Use `google.golang.org/protobuf` instead of `github.com/golang/protobuf`"
      - github.com/kballard/go-shellquote: "Use `github.com/telepresenceio/telepresence/pkg/shellquote.ShellString` instead of `github.com/kballard/go-shellquote.Join`"
      - github.com/datawire/dlib/dutil:    "Use either `github.com/datawire/dlib/derror` or `github.com/datawire/dlib/dhttp` instead of `github.com/datawire/dlib/dutil`"
      - golang.org/x/net/http2/h2c:        "Use `github.com/datawire/dlib/dhttp` instead of `golang.org/x/net/http2/h2c`"
  gomodguard:
    blocked:
      modules:
        - gotest.tools:    { recommendations: ['github.com/stretchr/testify', 'github.com/google/go-cmp/cmp'] }
        - gotest.tools/v2: { recommendations: ['github.com/stretchr/testify', 'github.com/google/go-cmp/cmp'] }
        - gotest.tools/v3: { recommendations: ['github.com/stretchr/testify', 'github.com/google/go-cmp/cmp'] }
  forbidigo:
    forbid:
      - '^os\.(DirEntry|FileInfo|FileMode|PathError)$' # deprecated in Go 1.16, import them from 'io/fs' instead
      - '\.Readdir$' # deprecated in Go 1.16, use ReadDir instead
    exclude_godoc_examples: false

  gocyclo:
    min-complexity: 35

  gocognit:
    min-complexity: 60

  goimports:
    # A comma-separated list
    local-prefixes: github.com/telepresenceio,github.com/datawire

  lll:
    line-length: 180
    tab-width: 2

  nolintlint:
    allow-unused: true # Needed because there's some linters disabled for 1.18
    allow-leading-space: false
    require-explanation: true
    require-specific: true
    allow-no-explanation:
      - gocognit

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - forbidigo
    - goimports
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - gomodguard
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

  # don't enable:
  # - dupl
  # - funlen
  # - gci
  # - gochecknoglobals
  # - gochecknoinits
  # - goconst
  # - godox
  # - golint
  # - gosec
  # - interfacer
  # - maligned # is premature-optimization
  # - stylecheck
  # - unparam
