#!/usr/bin/env python3

from time import time
from os import (
    environ,
    pathsep,
)
from sys import (
    platform,
    stdout,
    stderr,
)
from os.path import (
    abspath,
)
from shutil import (
    rmtree,
    which,
)
from argparse import ArgumentParser
from subprocess import (
    CalledProcessError,
    check_call,
    check_output,
)


def main():
    parser = _parser()
    args = parser.parse_args()

    try:
        # Presence of this variable in pip processes we launch causes pip to
        # write the wrong #! line.  Only expected to be set on OS X.
        # https://bugs.python.org/issue22490
        del environ['__PYVENV_LAUNCHER__']
    except KeyError:
        pass

    run_tests = args.tests

    if args.circle:
        manage_virtualenv = False
        registry = "gcr.io/" + environ["PROJECT_NAME"]
        version_suffix = ""
        methods = ["inject-tcp", "vpn-tcp"]
        if platform == "linux":
            methods.insert(0, "container")
        lint = False
        build_and_push = False
        test_args = []
        test_env = {
            # Magic incantation to make kubectl work, because apparently
            # gcloud can't do that correctly (see
            # https://github.com/kubernetes/kubernetes/issues/30617)
            "GOOGLE_APPLICATION_CREDENTIALS":
            abspath("gcloud-service-key.json"),
        }
    else:
        manage_virtualenv = args.manage_virtualenv
        lint = args.lint
        registry = args.registry
        build_and_push = args.build_and_push
        version_suffix = args.version_suffix
        methods = args.methods
        test_args = args.test_args or []
        test_env = {}

        if (run_tests or methods) and not build_and_push:
            print(
                "Some tests will run, behaving as though"
                " --build-and-push supplied."
            )
            build_and_push = True

    if methods or run_tests:
        if which("kubectl") is None:
            raise SystemExit(
                "Required executable 'kubectl' not found on $PATH.",
            )

    if registry is None:
        raise SystemExit(
            "You must specify a registry with --registry (or --circle)"
        )

    # Attempt to get credentials cached early on while the user is still
    # looking at the terminal.  They'll be required later on during the test
    # suite run and the prompt is likely to be buried in test output at that
    # point.
    _sudo("echo", "-n")

    if manage_virtualenv:
        _setup_virtualenv()

    if lint:
        _lint()

    _virtualenv('telepresence', '--help')

    version = _get_version(version_suffix)

    if build_and_push:
        _build(registry, version)
        # build_images implies pushing because the tests that want to consume
        # the images are run remotely and aren't going to be able to pull from
        # our _local_ Docker image repository.
        _push(registry, version)

    if run_tests:
        # Run the original end-to-end tests against each requested
        # Telepresence method.
        for method in methods:
            _test(registry, version, method, test_env, test_args)

        # Run the rest of the test suite, including the new end-to-end tests
        # which manage the Telepresence method in use without our help.
        _newtest(registry, version, test_env, test_args)


def _limit_for_openshift(maximum):
    """
    Select a testing parallelism level, taking into consideration the limits
    of OpenShift if that's where we're running.
    """
    if environ.get("TELEPRESENCE_OPENSHIFT"):
        # Don't want parallism for OpenShift (causes problems with OpenShift
        # Online's limited free plan).
        return 1
    return maximum


def _limit_for_method(method, maximum):
    """
    Select a testing parallelism level, taking into consideration the limits
    of the given Telepresence method.
    """
    if method == "vpn-tcp" or method == "container":
        # And don't want parallelism for VPN-y method since should only have
        # one running a time.  Or for container method because it confuses
        # checking in the tests for leaked resources.
        return 1
    return maximum


def _newtest(registry, version, test_env, test_args):
    """
    Run the test suite (except the original end-to-end tests).

    :param registry: A Docker registry where necessary images can be found.
    :param version: The Telepresence version to test.
    :param test_env: Extra items to add to the test process environment.
    :param test_args: Extra args to add to the py.test command line.
    """
    test_env = _test_env_for_telepresence(test_env, registry, version)
    _pytest(
        "-k",
        "not test_run",
        *test_args,
        test_env=test_env,
    )


def _test(registry, version, method, test_env, test_args):
    # Refresh the credentials
    _sudo("echo", "-n")

    parallel = str(_limit_for_openshift(_limit_for_method(method, 4)))
    test_env = _test_env_for_telepresence(test_env, registry, version)
    test_env.update({
        "TELEPRESENCE_METHOD": method,
    })

    _pytest(
        "--numprocesses",
        parallel,
        *test_args,
        "tests/test_run.py",
        "k8s-proxy/test_socks.py",
        test_env=test_env,
    )


def _pytest(*args, test_env=None):
    _virtualenv(
        "py.test",
        "-v",
        "--timeout=360",
        "--timeout-method=thread",
        *args,
        env=test_env,
    )


def _test_env_for_telepresence(test_env, registry, version):
    """
    Construct the additional environment variables which must be set in
    Telepresence's environment for it to behave as we wish.

    :param test_env: More variables to include in the result.

    :param registry: The location of the registry holding Telepresence Docker
        images to test.

    :param version: The version of Telepresence (as indicated by Docker image
        tags) to test.
    """
    if test_env is None:
        test_env = {}
    if registry is not None:
        test_env.update({
            "TELEPRESENCE_REGISTRY": registry,
        })
    test_env.update({
        "TELEPRESENCE_VERSION": version,

        # We don't want to collect test runs as real usage data.
        "SCOUT_DISABLE": "1",
    })
    return test_env


def _build(registry, version):
    _run(
        "docker",
        "build",
        "--file",
        "local-docker/Dockerfile",
        ".",
        "-t",
        "{}/telepresence-local:{}".format(registry, version),
    )
    _run(
        "docker",
        "build",
        "k8s-proxy",
        "-t",
        "{}/telepresence-k8s:{}".format(registry, version),
    )


def _push(registry, version):
    for image in ["telepresence-k8s", "telepresence-local"]:
        image = registry + "/" + image + ":" + version
        _run(
            "docker",
            "push",
            image,
        )


def _parser():
    parser = ArgumentParser(description="Test Telepresence")
    parser.add_argument(
        '--circle',
        action='store_true',
        help='do all the things CircleCI should do',
    )
    parser.add_argument(
        '--registry',
        metavar='REGISTRY',
        dest='registry',
        type=str,
        help='Docker registry for pushing/pulling Telepresence images',
    )
    parser.add_argument(
        '--build-and-push',
        action='store_true',
        dest='build_and_push',
        help='build the Docker images and push them to the registry',
    )
    parser.add_argument(
        '--version-suffix',
        dest='version_suffix',
        default="-{OS}-{TIME}",
        help='include a unique-ish suffix on the version number/image tag',
    )
    parser.add_argument(
        "--manage-virtualenv",
        action='store_true',
        dest='manage_virtualenv',
    )
    parser.add_argument(
        "--no-tests",
        action='store_false',
        dest='tests',
        default=True,
    )
    parser.add_argument(
        '--lint',
        action='store_true',
        dest='lint',
        help='run linters on the code base (yapf, flake8, pylint, mypy)',
    )
    parser.add_argument(
        '--method',
        action='append',
        dest='methods',
        choices=['container', 'inject-tcp', 'vpn-tcp'],
        default=[],
        help='add a mode to those which will be tested',
    )
    parser.add_argument(
        'test_args',
        metavar='test-args',
        nargs='*',
        help='pass additional arguments to py.test',
    )

    return parser


def _get_version(suffix_format):
    git_tag = check_output(["git", "describe",
                            "--tags"]).decode("utf-8").strip()
    os = {"linux": "LNX", "darwin": "OSX"}.get(platform)
    now = str(int(time()))
    return git_tag + suffix_format.format(OS=os, TIME=now)


def _setup_virtualenv():
    rmtree("virtualenv", ignore_errors=True)
    _run("virtualenv", "--python=python3", "virtualenv")
    _pip("--version")
    _pip("install", "flake8")
    _pip("install", "-r", "dev-requirements.txt")
    _pip("install", "-r", "k8s-proxy/requirements.txt")
    _pip(
        "install", "git+https://github.com/datawire/sshuttle.git@telepresence"
    )
    _pip("install", "-e", ".")


def _lint():
    _virtualenv("yapf", "-dr", "telepresence", "build")
    _virtualenv(
        "flake8", "--isolated", "local-docker", "k8s-proxy", "telepresence",
        "build"
    )
    _virtualenv("pylint", "-f", "parseable", "-E", "telepresence", "build")
    _virtualenv("mypy", "telepresence", "local-docker/entrypoint.py", "build")
    # Couldn't figure out how to make this work well, so it's not very useful
    # cause of the skip:
    _virtualenv(
        "mypy", "--ignore-missing-imports", "k8s-proxy/forwarder.py",
        "k8s-proxy/socks.py"
    )


def _pip(*argv):
    _virtualenv("pip", *argv)


def _virtualenv(*argv, env=None):
    bindir = abspath("virtualenv/bin")
    if env is None:
        env = {}
    env.update({"PATH": bindir + pathsep + environ["PATH"]})
    _run("/".join((bindir, argv[0])), *argv[1:], env=env)


def _sudo(*argv):
    _run("sudo", *argv)


def _run(*argv, env=None):
    pass_env = environ.copy()
    if env is not None:
        pass_env.update(env)
    print(
        "+ {} {}".format(
            " ".join(
                list("{}={}".format(k, v) for (k, v) in (env or {}).items())
            ),
            " ".join(argv),
        ),
        flush=True,
    )
    try:
        check_call(argv, stdout=stdout, stderr=stderr, env=pass_env)
    except CalledProcessError as e:
        raise SystemExit(e.returncode)


if __name__ == '__main__':
    main()
