#!/usr/bin/env python3

from time import time
from os import (
    environ,
    pathsep,
)
from sys import (
    platform,
    stdout,
    stderr,
)
from os.path import (
    abspath,
)
from shutil import (
    rmtree,
    which,
)
from argparse import ArgumentParser
from subprocess import (
    CalledProcessError,
    check_call,
    check_output,
)

def main():
    parser = _parser()
    args = parser.parse_args()

    for exe in {"gcloud", "kubectl"}:
        if which(exe) is None:
            raise SystemExit("Required executable {} not found on $PATH".format(exe))

    try:
        # Presence of this variable in pip processes we launch causes pip to
        # write the wrong #! line.  Only expected to be set on OS X.
        # https://bugs.python.org/issue22490
        del environ['__PYVENV_LAUNCHER__']
    except KeyError:
        pass

    if args.travis:
        manage_virtualenv = True
        flake8 = True
        pylint = True
        mypy = True
        registry = "gcr.io/" + environ["PROJECT_NAME"]
        if platform == "linux":
            # We'll do this on Linux and keep our fingers crossed that this is
            # done by the time the OS X builder wants to pull any images.  On
            # travis, this is a pretty safe bet as OS X has much longer build
            # queues and takes longer to set up.
            build_and_push = True
        else:
            build_and_push = False
        version_suffix = ""
        methods = ["inject-tcp", "vpn-tcp"]
        if platform == "linux":
            methods.insert(0, "container")
        test_args = []
        test_env = {
            # Magic incantation to make kubectl work, because apparently
            # gcloud can't do that correctly (see
            # https://github.com/kubernetes/kubernetes/issues/30617)
            "GOOGLE_APPLICATION_CREDENTIALS": abspath("gcloud-service-key.json"),
        }
    elif args.circle:
        manage_virtualenv = False
        registry = "exarkun"
        version_suffix = "-osx"
        methods = ["inject-tcp", "vpn-tcp"]
        flake8 = pylint = mypy = build_and_push = False
        test_args = []
        test_env = {}
    else:
        manage_virtualenv = args.manage_virtualenv
        flake8 = args.flake8
        pylint = args.pylint
        mypy = args.mypy
        registry = args.registry
        build_and_push = args.build_and_push
        version_suffix = args.version_suffix
        methods = args.methods
        test_args = args.test_args or []
        test_env = {}

        if methods and not build_and_push:
            print("Some tests will run, behaving as though --build-and-push supplied.")
            build_and_push = True

    if registry is None:
        raise SystemExit("You must specify a registry with --registry (or --travis)")

    # Attempt to get credentials cached early on while the user is still
    # looking at the terminal.  They'll be required later on during the test
    # suite run and the prompt is likely to be buried in test output at that
    # point.
    _sudo("echo", "-n")

    if manage_virtualenv:
        _setup_virtualenv()

    if flake8:
        _flake8()

    if pylint:
        _pylint()

    if mypy:
        _mypy()

    _virtualenv('telepresence', '--help')

    version = _get_version(version_suffix)

    if build_and_push:
        _build(registry, version)
        # build_images implies pushing because the tests that want to consume
        # the images are run remotely and aren't going to be able to pull from
        # our _local_ Docker image repository.
        _push(registry, version)

    for method in methods:
        _test(registry, version, method, test_env, test_args)

def _test(registry, version, method, test_env, test_args):
    # Refresh the credentials
    _sudo("echo", "-n")

    if environ.get("TELEPRESENCE_OPENSHIFT"):
        # Don't want parallism for OpenShift (causes problems with OpenShift
        # Online's limited free plan).
        parallel = "1"
    elif method == "vpn-tcp" or method == "container":
        # And don't want parallelism for VPN-y method since should only have
        # one running a time.  Or for container method because it confuses
        # checking in the tests for leaked resources.
        parallel = "1"
    else:
        parallel = "4"

    if test_env is None:
        test_env = {}
    if registry is not None:
        test_env.update({
            "TELEPRESENCE_REGISTRY": registry,
        })
    test_env.update({
        "TELEPRESENCE_METHOD": method,
        "TELEPRESENCE_VERSION": version,
        "SCOUT_DISABLE": "1",
    })

    _virtualenv(
        "py.test",
        "-v",
        "--timeout", "360",
        "--timeout-method", "thread",
        "--fulltrace",
        "--numprocesses", parallel,
        *test_args,
        "tests",
        "k8s-proxy/test_socks.py",
        env=test_env,
    )

def _build(registry, version):
    _run(
        "docker",
        "build",
        "--file",
        "local-docker/Dockerfile",
        ".",
        "-t",
        "{}/telepresence-local:{}".format(registry, version),
    )
    _run(
        "docker",
        "build",
        "k8s-proxy",
        "-t",
        "{}/telepresence-k8s:{}".format(registry, version),
    )

def _push(registry, version):
    for image in ["telepresence-k8s", "telepresence-local"]:
        image = registry + "/" + image + ":" + version
        if registry.startswith("gcr.io/"):
            _gcloud(
                "docker",
                "--",
                "push",
                image,
            )
        else:
            _run(
                "docker",
                "push",
                image,
            )

def _parser():
    parser = ArgumentParser(
        description="Test Telepresence",
    )
    parser.add_argument(
        '--travis',
        action='store_true',
        help='do all the things Travis should do'
    )
    parser.add_argument(
        '--circle',
        action='store_true',
        help='do all the things CircleCI should do'
    )
    parser.add_argument(
        '--registry',
        metavar='REGISTRY',
        dest='registry',
        type=str,
        help='Docker registry for pushing/pulling Telepresence images',
    )
    parser.add_argument(
        '--build-and-push',
        action='store_true',
        dest='build_and_push',
        help='build the Docker images and push them to the registry',
    )
    parser.add_argument(
        '--version-suffix',
        dest='version_suffix',
        default="-{OS}-{TIME}",
        help='include a unique-ish suffix on the version number/image tag',
    )
    parser.add_argument(
        "--manage-virtualenv",
        action='store_true',
        dest='manage_virtualenv',
    )
    parser.add_argument(
        '--flake8',
        action='store_true',
        dest='flake8',
        help='run flake8 on the code base',
    )
    parser.add_argument(
        '--pylint',
        action='store_true',
        dest='pylint',
        help='run pylint on the code base',
    )
    parser.add_argument(
        '--mypy',
        action='store_true',
        dest='mypy',
        help='run mypy on the code base',
    )
    parser.add_argument(
        '--method',
        action='append',
        dest='methods',
        choices=['container', 'inject-tcp', 'vpn-tcp'],
        default=[],
        help='add a mode to those which will be tested',
    )
    parser.add_argument(
        'test_args',
        metavar='test-args',
        nargs='*',
        help='pass additional arguments to py.test',
    )

    return parser

def _get_version(suffix_format):
    git_tag = check_output(["git", "describe", "--tags"]).decode("utf-8").strip()
    os = {"linux": "LNX", "darwin": "OSX"}.get(platform)
    now = str(int(time()))
    return git_tag + suffix_format.format(OS=os, TIME=now)

def _setup_virtualenv():
    rmtree("virtualenv", ignore_errors=True)
    _run("virtualenv", "--python=python3", "virtualenv")
    _pip("--version")
    _pip("install", "flake8")
    _pip("install", "-r", "dev-requirements.txt")
    _pip("install", "-r", "k8s-proxy/requirements.txt")
    _pip("install", "git+https://github.com/datawire/sshuttle.git@telepresence")
    _pip("install", "-e", ".")

def _flake8():
    _virtualenv("flake8", "--isolated", "local-docker", "k8s-proxy", "telepresence")

def _pylint():
    _virtualenv("pylint", "-f", "parseable", "-E", "telepresence")

def _mypy():
    _virtualenv("mypy", "telepresence", "local-docker/entrypoint.py")
    # Couldn't figure out how to make this work well, so it's not very useful
    # cause of the skip:
    _virtualenv(
        "mypy",
        "--ignore-missing-imports",
        "k8s-proxy/forwarder.py",
        "k8s-proxy/socks.py",
    )

def _gcloud(*argv):
    _run("gcloud", *argv)

def _pip(*argv):
    _virtualenv("pip", *argv)

def _virtualenv(*argv, env=None):
    bindir = abspath("virtualenv/bin")
    if env is None:
        env = {}
    env.update({
        "PATH": bindir + pathsep + environ["PATH"]
    })
    _run("/".join((bindir, argv[0])), *argv[1:], env=env)

def _sudo(*argv):
    _run("sudo", *argv)

def _run(*argv, env=None):
    pass_env = environ.copy()
    if env is not None:
        pass_env.update(env)
    print(
        "+ {} {}".format(
            " ".join(list(
                "{}={}".format(k, v) for (k, v) in (env or {}).items()
            )),
            " ".join(argv),
        ),
        flush=True,
    )
    try:
        check_call(argv, stdout=stdout, stderr=stderr, env=pass_env)
    except CalledProcessError as e:
        raise SystemExit(e.returncode)


if __name__ == '__main__':
    main()
