package setup

import (
	"fmt"
	"sort"
	"strings"

	"github.com/telepresenceio/telepresence/v2/pkg/errcat"
)

// missingRBACName is the name given to every object GenerateMissingRBAC
// produces.
const missingRBACName = "telepresence-setup-missing"

// missingRBACHeader explains what produced the file and what the admin still
// has to do before applying it.
const missingRBACHeader = `# Generated by telepresence setup: RBAC covering the install privileges that
# were denied while probing the cluster. Review the rules below, then add the
# requester's identity to the empty subjects list before applying.
`

// placeholderSubject is an empty subjects list plus a commented example, so
// the file parses as YAML and grants access to no one until the admin adds a
// subject.
const placeholderSubject = `subjects: []
# TODO: replace the empty list above with the requester's identity, e.g.:
# subjects:
#   - kind: User
#     name: alice
#     apiGroup: rbac.authorization.k8s.io
`

// ruleKey aggregates RBAC rules by the pair a Role/ClusterRole rule actually
// varies on: apiGroup and resource.
type ruleKey struct {
	group    string
	resource string
}

// GenerateMissingRBAC turns a list of denied privileges into ready-to-review
// RBAC YAML: a ClusterRole/ClusterRoleBinding pair for the cluster-scoped
// denials (empty namespace) and a Role/RoleBinding pair per namespace for the
// namespaced ones, rules aggregated by apiGroup+resource into a sorted verb
// list. Every binding's subjects list is empty, with a commented example the
// admin can uncomment and fill in. Output is deterministic.
func GenerateMissingRBAC(denied []DeniedAttribute) ([]byte, error) {
	if len(denied) == 0 {
		return nil, errcat.User.New("no denied privileges to generate RBAC for")
	}

	clusterRules := map[ruleKey]map[string]bool{}
	nsRules := map[string]map[ruleKey]map[string]bool{}
	for _, d := range denied {
		key := ruleKey{group: d.Group, resource: d.Resource}
		target := clusterRules
		if d.Namespace != "" {
			m := nsRules[d.Namespace]
			if m == nil {
				m = map[ruleKey]map[string]bool{}
				nsRules[d.Namespace] = m
			}
			target = m
		}
		verbs := target[key]
		if verbs == nil {
			verbs = map[string]bool{}
			target[key] = verbs
		}
		verbs[d.Verb] = true
	}

	var sb strings.Builder
	sb.WriteString(missingRBACHeader)
	if len(clusterRules) > 0 {
		writeClusterRole(&sb, clusterRules)
		writeClusterRoleBinding(&sb)
	}
	for _, ns := range sortedNamespaceKeys(nsRules) {
		writeRole(&sb, ns, nsRules[ns])
		writeRoleBinding(&sb, ns)
	}
	return []byte(sb.String()), nil
}

func writeClusterRole(sb *strings.Builder, rules map[ruleKey]map[string]bool) {
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: rbac.authorization.k8s.io/v1\n")
	sb.WriteString("kind: ClusterRole\n")
	fmt.Fprintf(sb, "metadata:\n  name: %s\n", missingRBACName)
	sb.WriteString("rules:\n")
	writeRules(sb, rules)
}

func writeClusterRoleBinding(sb *strings.Builder) {
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: rbac.authorization.k8s.io/v1\n")
	sb.WriteString("kind: ClusterRoleBinding\n")
	fmt.Fprintf(sb, "metadata:\n  name: %s\n", missingRBACName)
	sb.WriteString(placeholderSubject)
	sb.WriteString("roleRef:\n")
	sb.WriteString("  apiGroup: rbac.authorization.k8s.io\n")
	sb.WriteString("  kind: ClusterRole\n")
	fmt.Fprintf(sb, "  name: %s\n", missingRBACName)
}

func writeRole(sb *strings.Builder, namespace string, rules map[ruleKey]map[string]bool) {
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: rbac.authorization.k8s.io/v1\n")
	sb.WriteString("kind: Role\n")
	fmt.Fprintf(sb, "metadata:\n  name: %s\n  namespace: %s\n", missingRBACName, namespace)
	sb.WriteString("rules:\n")
	writeRules(sb, rules)
}

func writeRoleBinding(sb *strings.Builder, namespace string) {
	sb.WriteString("---\n")
	sb.WriteString("apiVersion: rbac.authorization.k8s.io/v1\n")
	sb.WriteString("kind: RoleBinding\n")
	fmt.Fprintf(sb, "metadata:\n  name: %s\n  namespace: %s\n", missingRBACName, namespace)
	sb.WriteString(placeholderSubject)
	sb.WriteString("roleRef:\n")
	sb.WriteString("  apiGroup: rbac.authorization.k8s.io\n")
	sb.WriteString("  kind: Role\n")
	fmt.Fprintf(sb, "  name: %s\n", missingRBACName)
}

func writeRules(sb *strings.Builder, rules map[ruleKey]map[string]bool) {
	for _, k := range sortedRuleKeys(rules) {
		fmt.Fprintf(sb, "- apiGroups: [%q]\n", k.group)
		fmt.Fprintf(sb, "  resources: [%q]\n", k.resource)
		verbs := sortedVerbs(rules[k])
		quoted := make([]string, len(verbs))
		for i, v := range verbs {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		fmt.Fprintf(sb, "  verbs: [%s]\n", strings.Join(quoted, ", "))
	}
}

func sortedNamespaceKeys(m map[string]map[ruleKey]map[string]bool) []string {
	out := make([]string, 0, len(m))
	for ns := range m {
		out = append(out, ns)
	}
	sort.Strings(out)
	return out
}

func sortedRuleKeys(m map[ruleKey]map[string]bool) []ruleKey {
	out := make([]ruleKey, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].group != out[j].group {
			return out[i].group < out[j].group
		}
		return out[i].resource < out[j].resource
	})
	return out
}

func sortedVerbs(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for v := range m {
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}

// ClientRbacSubject is one entry of the chart's clientRbac.subjects list,
// parsed from a "kind:name" (User, Group) or "kind:name:namespace"
// (ServiceAccount) flag/prompt entry.
type ClientRbacSubject struct {
	Kind      string `json:"kind"`
	Name      string `json:"name"`
	Namespace string `json:"namespace,omitempty"`
}

// ParseClientRbacSubjects parses the --client-rbac-subjects flag values.
func ParseClientRbacSubjects(vals []string) ([]ClientRbacSubject, error) {
	subjects := make([]ClientRbacSubject, 0, len(vals))
	for _, v := range vals {
		s, ok := parseClientRbacSubject(v)
		if !ok {
			return nil, errcat.User.Newf(
				"invalid --client-rbac-subjects entry %q: expected kind:name (User or Group) or ServiceAccount:name:namespace", v)
		}
		subjects = append(subjects, s)
	}
	return subjects, nil
}

// parseClientRbacSubject parses one "kind:name" or "kind:name:namespace"
// entry. The kind is split off first; for User and Group the remainder is
// taken as-is as the name (so it may itself contain colons, e.g.
// "system:authenticated"); for ServiceAccount the remainder is split once
// more into a name and a namespace, neither of which may be empty or contain
// a colon. Every component is trimmed of surrounding whitespace.
func parseClientRbacSubject(s string) (ClientRbacSubject, bool) {
	kind, rest, ok := strings.Cut(s, ":")
	if !ok {
		return ClientRbacSubject{}, false
	}
	kind = strings.TrimSpace(kind)
	switch kind {
	case "User", "Group":
		name := strings.TrimSpace(rest)
		if name == "" {
			return ClientRbacSubject{}, false
		}
		return ClientRbacSubject{Kind: kind, Name: name}, true
	case "ServiceAccount":
		parts := strings.SplitN(rest, ":", 2)
		if len(parts) != 2 {
			return ClientRbacSubject{}, false
		}
		name := strings.TrimSpace(parts[0])
		ns := strings.TrimSpace(parts[1])
		if name == "" || ns == "" || strings.Contains(ns, ":") {
			return ClientRbacSubject{}, false
		}
		return ClientRbacSubject{Kind: kind, Name: name, Namespace: ns}, true
	default:
		return ClientRbacSubject{}, false
	}
}

// clientRbacSubjectValue mirrors the chart's rbac.v1.Subject shape: User and
// Group carry the standard RBAC apiGroup, ServiceAccount carries a namespace
// and no apiGroup.
func clientRbacSubjectValue(s ClientRbacSubject) map[string]any {
	v := map[string]any{"kind": s.Kind, "name": s.Name}
	if s.Kind == "ServiceAccount" {
		v["namespace"] = s.Namespace
	} else {
		v["apiGroup"] = "rbac.authorization.k8s.io"
	}
	return v
}
