package setup

import (
	"bufio"
	"bytes"
	"errors"
	"io"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	yamlutil "k8s.io/apimachinery/pkg/util/yaml"
	"sigs.k8s.io/yaml"
)

func TestGenerateMissingRBAC(t *testing.T) {
	t.Run("errors with nothing to generate", func(t *testing.T) {
		_, err := GenerateMissingRBAC(nil)
		require.Error(t, err)
	})

	t.Run("cluster-scoped denials produce a ClusterRole/ClusterRoleBinding pair", func(t *testing.T) {
		manifest, err := GenerateMissingRBAC([]DeniedAttribute{
			{Verb: "create", Group: "rbac.authorization.k8s.io", Resource: "clusterroles"},
			{Verb: "create", Group: "rbac.authorization.k8s.io", Resource: "clusterrolebindings"},
		})
		require.NoError(t, err)
		docs := splitYAMLDocs(t, manifest)
		require.Len(t, docs, 2)
		assert.Equal(t, "ClusterRole", docs[0]["kind"])
		assert.Equal(t, "ClusterRoleBinding", docs[1]["kind"])
		assert.NotContains(t, string(manifest), "kind: Role\n")
	})

	t.Run("namespaced denials produce a Role/RoleBinding pair per namespace", func(t *testing.T) {
		manifest, err := GenerateMissingRBAC([]DeniedAttribute{
			{Verb: "create", Resource: "secrets", Namespace: "ambassador"},
			{Verb: "create", Group: "apps", Resource: "deployments", Namespace: "other"},
		})
		require.NoError(t, err)
		docs := splitYAMLDocs(t, manifest)
		require.Len(t, docs, 4) // Role+RoleBinding for each of 2 namespaces, sorted by namespace
		assert.Equal(t, "Role", docs[0]["kind"])
		assert.Equal(t, "ambassador", metaField(t, docs[0], "namespace"))
		assert.Equal(t, "RoleBinding", docs[1]["kind"])
		assert.Equal(t, "Role", docs[2]["kind"])
		assert.Equal(t, "other", metaField(t, docs[2], "namespace"))
		assert.Equal(t, "RoleBinding", docs[3]["kind"])
		assert.NotContains(t, string(manifest), "kind: ClusterRole\n")
	})

	t.Run("mixed cluster and namespaced denials produce both", func(t *testing.T) {
		manifest, err := GenerateMissingRBAC([]DeniedAttribute{
			{Verb: "create", Group: "rbac.authorization.k8s.io", Resource: "clusterroles"},
			{Verb: "create", Resource: "secrets", Namespace: "ambassador"},
		})
		require.NoError(t, err)
		docs := splitYAMLDocs(t, manifest)
		require.Len(t, docs, 4)
		assert.Equal(t, "ClusterRole", docs[0]["kind"])
		assert.Equal(t, "ClusterRoleBinding", docs[1]["kind"])
		assert.Equal(t, "Role", docs[2]["kind"])
		assert.Equal(t, "RoleBinding", docs[3]["kind"])
	})

	t.Run("rules are aggregated by group+resource into a sorted verb list", func(t *testing.T) {
		manifest, err := GenerateMissingRBAC([]DeniedAttribute{
			{Verb: "patch", Resource: "namespaces", Name: "ambassador"},
			{Verb: "create", Resource: "namespaces"},
			{Verb: "get", Resource: "namespaces"},
		})
		require.NoError(t, err)
		docs := splitYAMLDocs(t, manifest)
		require.Len(t, docs, 2)
		rules, ok := docs[0]["rules"].([]any)
		require.True(t, ok)
		require.Len(t, rules, 1, "same group+resource must aggregate into a single rule")
		rule, ok := rules[0].(map[string]any)
		require.True(t, ok)
		assert.Equal(t, []any{"create", "get", "patch"}, rule["verbs"], "verbs must be sorted")
	})

	t.Run("output is deterministic regardless of input order", func(t *testing.T) {
		a := []DeniedAttribute{
			{Verb: "create", Group: "apps", Resource: "deployments", Namespace: "b"},
			{Verb: "get", Resource: "namespaces"},
			{Verb: "create", Resource: "secrets", Namespace: "a"},
			{Verb: "create", Group: "rbac.authorization.k8s.io", Resource: "clusterroles"},
		}
		b := []DeniedAttribute{a[3], a[1], a[2], a[0]}
		m1, err := GenerateMissingRBAC(a)
		require.NoError(t, err)
		m2, err := GenerateMissingRBAC(b)
		require.NoError(t, err)
		assert.Equal(t, string(m1), string(m2))
	})

	t.Run("binding subjects list is empty with an explanatory comment", func(t *testing.T) {
		manifest, err := GenerateMissingRBAC([]DeniedAttribute{
			{Verb: "create", Group: "rbac.authorization.k8s.io", Resource: "clusterroles"},
		})
		require.NoError(t, err)
		text := string(manifest)
		assert.Contains(t, text, "TODO: replace the empty list above with the requester's identity")

		docs := splitYAMLDocs(t, manifest)
		binding := docs[1]
		subjects, ok := binding["subjects"].([]any)
		require.True(t, ok, "the empty subjects list must still parse as valid YAML")
		assert.Empty(t, subjects, "the file must grant access to no one until the admin edits it")
	})

	t.Run("header names the generator and instructs review", func(t *testing.T) {
		manifest, err := GenerateMissingRBAC([]DeniedAttribute{{Verb: "create", Resource: "namespaces"}})
		require.NoError(t, err)
		assert.Contains(t, string(manifest), "# Generated by telepresence setup")
	})
}

// splitYAMLDocs splits a multi-document YAML manifest and decodes each
// document, in order.
func splitYAMLDocs(t *testing.T, manifest []byte) []map[string]any {
	t.Helper()
	reader := yamlutil.NewYAMLReader(bufio.NewReader(bytes.NewReader(manifest)))
	var docs []map[string]any
	for {
		doc, err := reader.Read()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			require.NoError(t, err)
		}
		doc = bytes.TrimSpace(doc)
		if len(doc) == 0 {
			continue
		}
		var m map[string]any
		require.NoError(t, yaml.Unmarshal(doc, &m))
		if len(m) > 0 {
			docs = append(docs, m)
		}
	}
	return docs
}

func metaField(t *testing.T, doc map[string]any, field string) string {
	t.Helper()
	meta, ok := doc["metadata"].(map[string]any)
	require.True(t, ok)
	v, _ := meta[field].(string)
	return v
}

func TestParseClientRbacSubjects(t *testing.T) {
	t.Run("valid User and Group entries", func(t *testing.T) {
		subjects, err := ParseClientRbacSubjects([]string{"User:alice", "Group:devs"})
		require.NoError(t, err)
		assert.Equal(t, []ClientRbacSubject{
			{Kind: "User", Name: "alice"},
			{Kind: "Group", Name: "devs"},
		}, subjects)
	})
	t.Run("valid ServiceAccount entry", func(t *testing.T) {
		subjects, err := ParseClientRbacSubjects([]string{"ServiceAccount:my-sa:my-ns"})
		require.NoError(t, err)
		assert.Equal(t, []ClientRbacSubject{{Kind: "ServiceAccount", Name: "my-sa", Namespace: "my-ns"}}, subjects)
	})
	t.Run("Group name containing colons is kept intact", func(t *testing.T) {
		subjects, err := ParseClientRbacSubjects([]string{"Group:system:authenticated"})
		require.NoError(t, err)
		assert.Equal(t, []ClientRbacSubject{{Kind: "Group", Name: "system:authenticated"}}, subjects)
	})
	t.Run("User name containing colons is kept intact", func(t *testing.T) {
		subjects, err := ParseClientRbacSubjects([]string{"User:system:admin"})
		require.NoError(t, err)
		assert.Equal(t, []ClientRbacSubject{{Kind: "User", Name: "system:admin"}}, subjects)
	})
	t.Run("ServiceAccount without a namespace is invalid", func(t *testing.T) {
		_, err := ParseClientRbacSubjects([]string{"ServiceAccount:name"})
		require.Error(t, err)
	})
	t.Run("User with an empty name is invalid", func(t *testing.T) {
		_, err := ParseClientRbacSubjects([]string{"User:"})
		require.Error(t, err)
	})
	t.Run("unknown kind is invalid", func(t *testing.T) {
		_, err := ParseClientRbacSubjects([]string{"Robot:hal"})
		require.Error(t, err)
		assert.Contains(t, err.Error(), "Robot:hal")
	})
	t.Run("empty entry is invalid", func(t *testing.T) {
		_, err := ParseClientRbacSubjects([]string{""})
		require.Error(t, err)
	})
	t.Run("bare word with no colon is invalid", func(t *testing.T) {
		_, err := ParseClientRbacSubjects([]string{"alice"})
		require.Error(t, err)
	})
}

func TestClientRbacSubjectValue(t *testing.T) {
	assert.Equal(t, map[string]any{"kind": "User", "name": "alice", "apiGroup": "rbac.authorization.k8s.io"},
		clientRbacSubjectValue(ClientRbacSubject{Kind: "User", Name: "alice"}))
	assert.Equal(t, map[string]any{"kind": "ServiceAccount", "name": "sa", "namespace": "ns"},
		clientRbacSubjectValue(ClientRbacSubject{Kind: "ServiceAccount", Name: "sa", Namespace: "ns"}))
}
