name: "Check re-run cache"
description: "Checks to see if the job has passed previously when doing a re-run"
outputs:
  passed:
    description: "Whether the job passed in a previous run"
    value: ${{ steps.run_result.outputs.run_result }}
runs:
  using: composite
  steps:
    # Used so we don't have to re-run tests that pass, kinda hacky but github
    # doesn't have any other alternative right now aside from re-running *all* jobs.
    # It is on the roadmap though: https://github.com/github/roadmap/issues/271
    - id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"
      shell: bash

    - name: Get previous run
      uses: actions/cache@v3
      with:
        path: |
          run_result
        key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ github.run_id }}-${{ github.job }}-

    - name: Get result from the previous run
      id: run_result
      run: cat run_result 2>/dev/null || echo 'not run'
      shell: bash
