// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: rpc/systema/agent2systema.proto

package systema

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	manager "github.com/telepresenceio/telepresence/rpc/v2/manager"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReviewInterceptResponse_Status int32

const (
	ReviewInterceptResponse_UNSPECIFIED ReviewInterceptResponse_Status = 0
	ReviewInterceptResponse_ALLOW       ReviewInterceptResponse_Status = 1
	ReviewInterceptResponse_DENY        ReviewInterceptResponse_Status = 2
)

// Enum value maps for ReviewInterceptResponse_Status.
var (
	ReviewInterceptResponse_Status_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ALLOW",
		2: "DENY",
	}
	ReviewInterceptResponse_Status_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ALLOW":       1,
		"DENY":        2,
	}
)

func (x ReviewInterceptResponse_Status) Enum() *ReviewInterceptResponse_Status {
	p := new(ReviewInterceptResponse_Status)
	*p = x
	return p
}

func (x ReviewInterceptResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewInterceptResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_systema_agent2systema_proto_enumTypes[0].Descriptor()
}

func (ReviewInterceptResponse_Status) Type() protoreflect.EnumType {
	return &file_rpc_systema_agent2systema_proto_enumTypes[0]
}

func (x ReviewInterceptResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewInterceptResponse_Status.Descriptor instead.
func (ReviewInterceptResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_rpc_systema_agent2systema_proto_rawDescGZIP(), []int{0, 0}
}

type ReviewInterceptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Status is whether or not to allow this intercept to become active.
	Status ReviewInterceptResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=telepresence.systema.ReviewInterceptResponse_Status" json:"status,omitempty"`
	// Msg is a user-facing explanation of why the intercept is not
	// allowed to become active.
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ReviewInterceptResponse) Reset() {
	*x = ReviewInterceptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_systema_agent2systema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReviewInterceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewInterceptResponse) ProtoMessage() {}

func (x *ReviewInterceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_systema_agent2systema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewInterceptResponse.ProtoReflect.Descriptor instead.
func (*ReviewInterceptResponse) Descriptor() ([]byte, []int) {
	return file_rpc_systema_agent2systema_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewInterceptResponse) GetStatus() ReviewInterceptResponse_Status {
	if x != nil {
		return x.Status
	}
	return ReviewInterceptResponse_UNSPECIFIED
}

func (x *ReviewInterceptResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type InterceptRemoval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterceptId string `protobuf:"bytes,1,opt,name=intercept_id,json=interceptId,proto3" json:"intercept_id,omitempty"`
}

func (x *InterceptRemoval) Reset() {
	*x = InterceptRemoval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_systema_agent2systema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterceptRemoval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptRemoval) ProtoMessage() {}

func (x *InterceptRemoval) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_systema_agent2systema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptRemoval.ProtoReflect.Descriptor instead.
func (*InterceptRemoval) Descriptor() ([]byte, []int) {
	return file_rpc_systema_agent2systema_proto_rawDescGZIP(), []int{1}
}

func (x *InterceptRemoval) GetInterceptId() string {
	if x != nil {
		return x.InterceptId
	}
	return ""
}

var File_rpc_systema_agent2systema_proto protoreflect.FileDescriptor

var file_rpc_systema_agent2systema_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x2f, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x32, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x14, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa9, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63,
	0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x74, 0x65,
	0x6c, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x61, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65,
	0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2e, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x02, 0x22, 0x35, 0x0a, 0x10, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74,
	0x49, 0x64, 0x32, 0xc8, 0x01, 0x0a, 0x0c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x65, 0x0a, 0x0f, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x12, 0x23, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x2d, 0x2e, 0x74, 0x65,
	0x6c, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x61, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65,
	0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0f, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x12, 0x26, 0x2e,
	0x74, 0x65, 0x6c, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x61, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x37, 0x5a,
	0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x6c, 0x65,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x69, 0x6f, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x32, 0x2f, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_systema_agent2systema_proto_rawDescOnce sync.Once
	file_rpc_systema_agent2systema_proto_rawDescData = file_rpc_systema_agent2systema_proto_rawDesc
)

func file_rpc_systema_agent2systema_proto_rawDescGZIP() []byte {
	file_rpc_systema_agent2systema_proto_rawDescOnce.Do(func() {
		file_rpc_systema_agent2systema_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_systema_agent2systema_proto_rawDescData)
	})
	return file_rpc_systema_agent2systema_proto_rawDescData
}

var file_rpc_systema_agent2systema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_systema_agent2systema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_systema_agent2systema_proto_goTypes = []interface{}{
	(ReviewInterceptResponse_Status)(0), // 0: telepresence.systema.ReviewInterceptResponse.Status
	(*ReviewInterceptResponse)(nil),     // 1: telepresence.systema.ReviewInterceptResponse
	(*InterceptRemoval)(nil),            // 2: telepresence.systema.InterceptRemoval
	(*manager.InterceptInfo)(nil),       // 3: telepresence.manager.InterceptInfo
	(*empty.Empty)(nil),                 // 4: google.protobuf.Empty
}
var file_rpc_systema_agent2systema_proto_depIdxs = []int32{
	0, // 0: telepresence.systema.ReviewInterceptResponse.status:type_name -> telepresence.systema.ReviewInterceptResponse.Status
	3, // 1: telepresence.systema.SystemAAgent.ReviewIntercept:input_type -> telepresence.manager.InterceptInfo
	2, // 2: telepresence.systema.SystemAAgent.RemoveIntercept:input_type -> telepresence.systema.InterceptRemoval
	1, // 3: telepresence.systema.SystemAAgent.ReviewIntercept:output_type -> telepresence.systema.ReviewInterceptResponse
	4, // 4: telepresence.systema.SystemAAgent.RemoveIntercept:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_systema_agent2systema_proto_init() }
func file_rpc_systema_agent2systema_proto_init() {
	if File_rpc_systema_agent2systema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_systema_agent2systema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReviewInterceptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_systema_agent2systema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterceptRemoval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_systema_agent2systema_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_systema_agent2systema_proto_goTypes,
		DependencyIndexes: file_rpc_systema_agent2systema_proto_depIdxs,
		EnumInfos:         file_rpc_systema_agent2systema_proto_enumTypes,
		MessageInfos:      file_rpc_systema_agent2systema_proto_msgTypes,
	}.Build()
	File_rpc_systema_agent2systema_proto = out.File
	file_rpc_systema_agent2systema_proto_rawDesc = nil
	file_rpc_systema_agent2systema_proto_goTypes = nil
	file_rpc_systema_agent2systema_proto_depIdxs = nil
}
