name: "Upload logs"
description: "Upload logs from the test run"
runs:
  using: composite
  steps:
    - run: |
        LOGS="test-logs/${{ runner.os }}"
        mkdir -p "$LOGS"
        if [[ $RUNNER_OS != Windows ]]; then
          rsync -ma --include='*/' --include='*.tap' --include='*.log' --include='Test*.webm' --exclude='*' . "$LOGS"
        fi
        for file in \
          {"${XDG_CACHE_HOME:-$HOME/.cache}/telepresence/logs","$HOME/Library/Logs/telepresence","$LOCALAPPDATA/telepresence/logs","."}/*.log
        do
          if [ -s "$file" ]; then
            cp -v "$file" "$LOGS"
          fi
        done
      shell: bash
      name: Gather logs
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        # If an environment variable LOG_SUFFIX is set, it will be appended to the log filename.
        name: ${{github.job}}-logs-${{ env.LOG_SUFFIX }}
        path: |
          test-logs/${{ runner.os }}/*
