apiVersion: v1
kind: ConfigMap
metadata:
  name: hello
  labels:
    app: hello
data:
  index.html: |
    <html>
      <body>
        <p id="hello"></p>
        <script>
          document.getElementById("hello").innerHTML = "Hello from " + navigator.location.hostname + "!";
        </script>
      </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: ClusterIP
  selector:
    service: hello
  ports:
    - name: proxied
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    service: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hello
  template:
    metadata:
      labels:
        service: hello
    spec:
      volumes:
        - name: hello-cm-volume
          configMap:
            name: hello
        - name: tmp-volume
          emptyDir: {}
      containers:
        - name: hello-container
          image: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: hello-cm-volume
            - mountPath: "/tmp"
              name: tmp-volume
