#!/usr/bin/env bash

# Copyright 2018 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

source ./.ci/helpers

# This block gets a kluster from kubeception.
# The KUBECEPTION_TOKEN env var is set in the circleci webui.
if [ -n "${KUBECEPTION_TOKEN}" ]; then
    # Use a CLAIM_NAME of kubeception.
    echo kubeception > ~/kubeception-claim.txt
    mkdir -p ~/.kube
    export DEV_KUBECONFIG=~/.kube/kubeception.yaml
    # get a kluster with a 1 timeout that is size "medium"
    get_cluster ${DEV_KUBECONFIG} 28800 medium
    kubectl --kubeconfig ${DEV_KUBECONFIG} -n default get service kubernetes
    exit
fi
