name: "Prepare Cluster"
description: "Provision a cluster"
inputs:
  kubeception-token:
    description: "The kubeception token to use"
    required: true
  gke-credentials:
    description: "Service account credentials in JSON format. Account needs permissions to create/destroy clusters"
    required: true
  tel-image:
    description: "Path to the image to load onto the cluster"
    required: true
  cluster-distribution:
    description: "Cluster distribution"
    required: true
    default: Kubeception
  cluster-version:
    description: "Kubernetes version"
    required: true
    default: "1.19"
outputs:
  kubeconfig:
    description: "The resulting kubeconfig file"
    value: ${{ steps.kubeconfig.outputs.KUBECONFIG }}
runs:
  using: composite
  steps:
    - name: Get KUBECONFIG path
      id: kubeconfig
      shell: bash
      run: |
        KUBECONFIG=$HOME/kubeconfig
        if [[ "${RUNNER_OS}" == "Windows" ]]; then
          # With thanks to stack overflow (https://stackoverflow.com/a/13701495) for showing how to convert a unix path to a windows path
          KUBECONFIG=$(echo $KUBECONFIG | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/')
        fi
        echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_OUTPUT
    - name: Create cluster
      uses: datawire/infra-actions/provision-cluster@v0.2.0
      with:
        distribution: ${{ inputs.cluster-distribution }}
        version: ${{ inputs.cluster-version }}
        kubeconfig: "${{ steps.kubeconfig.outputs.KUBECONFIG }}"
        kubeceptionToken: ${{ inputs.kubeception-token }}
        gkeCredentials: ${{ inputs.gke-credentials }}
    - name: Load image
      shell: bash
      env:
        KUBECONFIG: "${{ steps.kubeconfig.outputs.KUBECONFIG }}"
      run: |
        kubectl apply -f build-aux/image-importer.yaml
        kubectl rollout status -w deployment/image-importer
        POD_NAME=$(kubectl get pod -ojsonpath='{.items[0].metadata.name}' -l app=image-importer)
        kubectl cp "${{ inputs.tel-image }}" "$POD_NAME:/tmp/image.tar"
        kubectl exec $POD_NAME -- //hostbin/ctr images import //tmp/image.tar
