syntax = "proto3";
package telepresence.connector;

import "common/version.proto";
import "daemon/daemon.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";
import "manager/manager.proto";

option go_package = "github.com/telepresenceio/telepresence/rpc/v2/connector";

// The Connector service is responsible for connecting to the traffic manager
// and manage intercepts. It can only run when a Daemon is running.
service Connector {
  // Returns version information from the Connector
  rpc Version(google.protobuf.Empty) returns (telepresence.common.VersionInfo);

  // Returns version information from the Root Daemon
  rpc RootDaemonVersion(google.protobuf.Empty) returns (telepresence.common.VersionInfo);

  // Returns version information from the Traffic Manager
  rpc TrafficManagerVersion(google.protobuf.Empty) returns (telepresence.common.VersionInfo);

  // Returns the fully qualified image name of the traffic-agent that the agent-injector is configured to inject.
  rpc AgentImageFQN(google.protobuf.Empty) returns (manager.AgentImageFQN);

  // GetIntercept gets info from intercept name
  rpc GetIntercept(manager.GetInterceptRequest) returns (manager.InterceptInfo);

  // Connects to the cluster and connects the laptop's network (via
  // the daemon process) to the cluster's network.  A result code of
  // UNSPECIFIED indicates that the connection was successfully
  // initiated; if already connected, then either ALREADY_CONNECTED or
  // MUST_RESTART is returned, based on whether the current connection
  // is in agreement with the ConnectionRequest.
  rpc Connect(ConnectRequest) returns (ConnectInfo);

  // Disconnects the cluster
  rpc Disconnect(google.protobuf.Empty) returns (google.protobuf.Empty);

  // GetClusterSubnets gets the outbound info that has been set on daemon
  rpc GetClusterSubnets(google.protobuf.Empty) returns (ClusterSubnets);

  // Status returns the status of the current connection or DISCONNECTED
  // if no connection has been established.
  rpc Status(google.protobuf.Empty) returns (ConnectInfo);

  // Queries the connector whether it is possible to create the given intercept
  // and returns an error if it's not.
  rpc CanIntercept(CreateInterceptRequest) returns (google.protobuf.Empty);

  // Starts an Ingest session.
  rpc Ingest(IngestRequest) returns (IngestInfo);

  // Get info about an ongoing Ingest.
  rpc GetIngest(IngestIdentifier) returns (IngestInfo);

  // Ends an Ingest session.
  rpc LeaveIngest(IngestIdentifier) returns (IngestInfo);

  // Adds an intercept to a workload.  Requires having already called
  // Connect.
  rpc CreateIntercept(CreateInterceptRequest) returns (manager.InterceptInfo);

  // Deactivates and removes an existent workload intercept.
  // Requires having already called Connect.
  rpc RemoveIntercept(manager.RemoveInterceptRequest2) returns (google.protobuf.Empty);

  // Uninstalls traffic-agents from the cluster.
  // Requires having already called Connect.
  rpc Uninstall(UninstallRequest) returns (google.protobuf.Empty);

  // Returns a list of workloads and their current intercept status.
  // Requires having already called Connect.
  rpc List(ListRequest) returns (WorkloadInfoSnapshot);

  // Watch all workloads in the mapped namespaces
  rpc WatchWorkloads(WatchWorkloadsRequest) returns (stream WorkloadInfoSnapshot);

  // SetLogLevel will temporarily change the log-level of the traffic-manager, traffic-agent, and user and root daemons.
  rpc SetLogLevel(LogLevelRequest) returns (google.protobuf.Empty);

  // Quits (terminates) the connector process.
  rpc Quit(google.protobuf.Empty) returns (google.protobuf.Empty);

  // GatherLogs will acquire logs for the various Telepresence components in kubernetes
  // (pending the request) and return them to the caller
  rpc GatherLogs(LogsRequest) returns (LogsResponse);

  // AddInterceptor tells the connector that a given process is serving a specific
  // intercept. The connector must kill this process when the intercept ends
  rpc AddInterceptor(Interceptor) returns  (google.protobuf.Empty);

  // RemoveInterceptor removes a previously added interceptor
  rpc RemoveInterceptor(Interceptor)  returns  (google.protobuf.Empty);

  // GetNamespaces gets the mapped namespaces with an optional prefix
  rpc GetNamespaces(GetNamespacesRequest) returns (GetNamespacesResponse);

  // GetKnownWorkloadKinds returns the known workload kinds
  rpc GetKnownWorkloadKinds(google.protobuf.Empty) returns (manager.KnownWorkloadKinds);

  // RemoteMountAvailability checks if remote mounts are possible using the given
  // mount type and returns an error if its not.
  rpc RemoteMountAvailability(google.protobuf.Empty) returns (google.protobuf.Empty);

  // GetConfig returns the current configuration
  rpc GetConfig(google.protobuf.Empty) returns (ClientConfig);

  // SetDNSExcludes sets the excludes field of DNSConfig.
  rpc SetDNSExcludes(daemon.SetDNSExcludesRequest) returns (google.protobuf.Empty);

  // SetDNSMappings sets the Mappings field of DNSConfig.
  rpc SetDNSMappings(daemon.SetDNSMappingsRequest) returns (google.protobuf.Empty);

  // GetAgentConfig returns the agent configuration for a specific workload.
  rpc GetAgentConfig(manager.AgentConfigRequest) returns (manager.AgentConfigResponse);

  // ResolveSyntheticIP resolves a synthetic IP into a name and optionally
  // the first IP for that name when the daemon performs a DNS lookup.
  rpc ResolveSyntheticIP(ResolveSyntheticRequest) returns (ResolveSyntheticResponse);

  // LookupIP resolves the given name using the Telepresence DNS server
  rpc LookupIP(daemon.LookupIPRequest) returns (daemon.LookupIPResponse);

  // ResolvePort resolves an host:port string from into a netip.AddrPort
  rpc ResolvePort(daemon.ResolvePortRequest) returns (daemon.ResolvePortResponse);

  // RerouteLocalPort reroutes a port on localhost to a netip.AddrPort.
  rpc RerouteLocalPort(daemon.ReroutePortRequest) returns (google.protobuf.Empty);

  // RerouteRemotePort makes a netip.AddrPort available on a new port on the same address.
  rpc RerouteRemotePort(daemon.ReroutePortRequest) returns (google.protobuf.Empty);
}

message Interceptor {
  // The ID of the intercept that is served by this interceptor process
  string intercept_id = 1;
  // The pid of the interceptor process
  int32  pid = 2;
  // Name or ID of container, in case the intercept handler runs in Docker
  string container_name = 3;
}

// ConnectRequest contains the information needed to connect ot a cluster.
message ConnectRequest {
  // The kubernetes flags from the telepresence connect command
  map<string, string> kube_flags = 1;

  // The kubernetes flags used by a containerized daemon
  map<string, string> container_kube_flag_overrides = 9;

  repeated string mapped_namespaces = 2;
  string name = 3;
  bool is_pod_daemon = 4;
  repeated string also_proxy = 5; // protolint:disable:this REPEATED_FIELD_NAMES_PLURALIZED
  repeated string never_proxy = 6; // protolint:disable:this REPEATED_FIELD_NAMES_PLURALIZED
  repeated string allow_conflicting_subnets = 10;
  repeated daemon.SubnetViaWorkload subnet_via_workloads = 11;
  string manager_namespace = 7;
  map<string, string> environment = 8;

  // Kubeconfig YAML, if not to be loaded from file.
  optional bytes kubeconfig_data = 12;

  string client_id = 13;
}

message ConnectInfo {
  string cluster_server = 3;
  string cluster_context = 4;
  common.VersionInfo version = 5;

  // The name of the connection
  string connection_name = 16;

  // The kubernetes flags from the telepresence connect command when the connection was established
  map<string, string> kube_flags = 17;

  // the namespace that the connector is connected to.
  string namespace = 6;

  string manager_install_id = 7;

  manager.InterceptInfoSnapshot intercepts = 8;

  repeated IngestInfo ingests = 9;

  manager.SessionInfo session_info = 10;

  manager.VersionInfo2 manager_version = 19;

  daemon.DaemonStatus daemon_status = 13;
  string manager_namespace = 14;

  repeated string mapped_namespaces = 15;
  repeated daemon.SubnetViaWorkload subnet_via_workloads = 18;

  // Connection was established by the caller's connect call.
  bool initial = 20;

  reserved 1, 2, 11, 12;
}

message UninstallRequest {
  enum UninstallType {
    UNSPECIFIED = 0;

    // Uninstalls an agent from the named workloads
    NAMED_AGENTS = 1;

    // Uninstalls all agents
    ALL_AGENTS = 2;
  }

  UninstallType uninstall_type = 1;
  repeated string agents = 2;

  // Namespace of agents to remove.
  string namespace = 3;
}

message CreateInterceptRequest {
  // No need to set spec.client; the connector will fill that in for
  // you.
  manager.InterceptSpec spec = 1;
  string mount_point = 2;
  string agent_image = 3;
  bool is_pod_daemon = 4;
  bytes extended_info = 5;
  int32 local_mount_port = 6;
  bool mount_read_only = 7;
}

message ListRequest {
  // Bitmap filter
  enum Filter {
    UNSPECIFIED = 0;
    INTERCEPTS = 1;
    REPLACEMENTS = 2;
    INGESTS = 4;
    WIRETAPS = 8;
    INSTALLED_AGENTS = 16;
    EVERYTHING = 31;
  }
  Filter filter = 1;

  // Namespace to list.
  string namespace = 2;
}

message IngestIdentifier {
  // Name of the workload that holds the desire container.
  string workload_name = 1;

  // The name of the desired container. Must be set when the workload contains more
  // than one container candidate.
  string container_name = 2;
}

message IngestRequest {
  IngestIdentifier identifier = 1;

  // Desired mount point. Can be set to "true" to generated temporary mount point,
  // "false" to prevent that mounting takes place, an explicit path to use for the
  // mount or an empty string in combination with a non-zero local_mount_port.
  string mount_point = 2;

  // Local port where an sftp client can connect when doing docker volume mounts.
  int32 local_mount_port = 3;

  // Extra ports that will be forwarded from the intercepting client's localhost
  // to the intercepted pod. Each entry is a string containing a port number followed
  // by an optional "/TCP" or "/UDP".
  repeated string local_ports = 4;
}

message IngestInfo {
  // Name of ingested workload
  string workload = 1;

  string workload_kind = 2;

  // Name of ingested container
  string container = 3;

  // The directory where the intercept mounts can be found in the agent.
  string mount_point = 4;

  // The IP of the ingested pod.
  string pod_ip = 5;

  // The port where the SFTP server listens.
  int32 sftp_port = 6;

  // The port where the FTP server listens.
  int32 ftp_port = 7;

  // The environment of the ingested container
  map<string, string> environment = 8;

  // The directory where the client mounts the remote mount_point.
  string client_mount_point = 9;

  // Map of mount path -> MountPolicy
  map<string, int32> mounts = 10;
}

message WatchWorkloadsRequest {
  // Namespace to watch.
  repeated string namespaces = 1;
}

// WorkloadInfo contains information about a workload
// https://kubernetes.io/docs/concepts/workloads/
message WorkloadInfo {
  // Name of workload
  string name = 1;

  // Namespace of workload
  string namespace = 2;

  // Reason why workload cannot be intercepted, or empty if it can.
  string not_interceptable_reason = 3;

  // InterceptInfo reported from the traffic manager in case the workload is currently intercepted
  repeated manager.InterceptInfo intercept_info = 4;

  // IngestInfo reported from the traffic manager in case the workload is currently intercepted
  repeated IngestInfo ingest_info = 5;

  // Workload Resource type (e.g. Deployment, ReplicaSet, StatefulSet, Rollout)
  string workload_resource_type = 6;

  string uid = 7;

  string agent_version = 8;
}

message WorkloadInfoSnapshot {
  repeated WorkloadInfo workloads = 1;
}

message LogLevelRequest {
  enum Scope {
    UNSPECIFIED = 0;
    LOCAL_ONLY = 1; // applies only to the local daemon processes
    REMOTE_ONLY = 2; // applies only to traffic-manager and traffic-agents
  }

  string log_level = 1;

  // The time that this log-level will be in effect before
  // falling back to the configured log-level.
  google.protobuf.Duration duration = 2;

  Scope scope = 3;
}

message LogsRequest {
  // Whether or not logs from the traffic-manager are desired.
  bool traffic_manager = 1;

  // Whether or not to get the pod yaml deployed to the cluster.
  bool get_pod_yaml = 2;

  // The traffic-agent(s) logs are desired from. Can be `all`, `False`,
  // or substring to filter based on pod names.
  string agents = 3;

  // Directory that the logs will be exported to
  string export_dir = 4;
}

message LogsResponse {
  // General error that isn't associated with a pod such as failing to list the pods.
  string error = 1;

  // pod_info contains one entry per created file name name. The value is either the string
  // "ok" indicating that the file exists, or an error string with info why it could not
  // be created.
  map<string, string> pod_info = 2;
}


message GetNamespacesRequest {
  bool for_client_access = 1;
  string prefix = 2;
}

message GetNamespacesResponse {
  repeated string namespaces = 2;
}

message ClientConfig {
  bytes json = 1;
}

// ClusterSubnets are the cluster subnets that the daemon has detected that need to be
// routed
message ClusterSubnets {
  // pod_subnets are the subnets that pods go into
  repeated manager.IPNet pod_subnets = 1;
  // svc_subnets are subnets that services go into
  repeated manager.IPNet svc_subnets = 2;
}

message ResolveSyntheticRequest {
  // The synthetic IP to be resolved.
  bytes ip = 1;

  // Resolve the IP into a name, but do not make an attempt to resolve the name through DNS.
  bool name_only = 2;
}

message ResolveSyntheticResponse {
  // The name that the synthetic IP resolved to.
  string name = 1;

  // The IP resulting from a DNS lookup using the resolved name.
  bytes resolved_ip = 2;
}