// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: connector/connector.proto

package connector

import (
	common "github.com/telepresenceio/telepresence/rpc/v2/common"
	daemon "github.com/telepresenceio/telepresence/rpc/v2/daemon"
	manager "github.com/telepresenceio/telepresence/rpc/v2/manager"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectInfo_ErrType int32

const (
	ConnectInfo_UNSPECIFIED       ConnectInfo_ErrType = 0 // success
	ConnectInfo_UNAUTHORIZED      ConnectInfo_ErrType = 1 // not authorized to connect
	ConnectInfo_UNAUTHENTICATED   ConnectInfo_ErrType = 5 // not logged in
	ConnectInfo_ALREADY_CONNECTED ConnectInfo_ErrType = 2 // success
	ConnectInfo_MUST_RESTART      ConnectInfo_ErrType = 7 // would-be-success, but kubeconfig has changed
	// failure: Connect has not yet been called (only returned from Status)
	ConnectInfo_DISCONNECTED ConnectInfo_ErrType = 3
	// failure: error parsing kubeconfig or talking to the cluster; error_text and error_category are set
	ConnectInfo_CLUSTER_FAILED ConnectInfo_ErrType = 4
	// failure: error talking to the in-cluster traffic-manager; error_text and error_category are set
	ConnectInfo_TRAFFIC_MANAGER_FAILED ConnectInfo_ErrType = 6
	// failure: error talking to the on-laptop root daemon; error_text and error_category are set
	ConnectInfo_DAEMON_FAILED ConnectInfo_ErrType = 8
)

// Enum value maps for ConnectInfo_ErrType.
var (
	ConnectInfo_ErrType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNAUTHORIZED",
		5: "UNAUTHENTICATED",
		2: "ALREADY_CONNECTED",
		7: "MUST_RESTART",
		3: "DISCONNECTED",
		4: "CLUSTER_FAILED",
		6: "TRAFFIC_MANAGER_FAILED",
		8: "DAEMON_FAILED",
	}
	ConnectInfo_ErrType_value = map[string]int32{
		"UNSPECIFIED":            0,
		"UNAUTHORIZED":           1,
		"UNAUTHENTICATED":        5,
		"ALREADY_CONNECTED":      2,
		"MUST_RESTART":           7,
		"DISCONNECTED":           3,
		"CLUSTER_FAILED":         4,
		"TRAFFIC_MANAGER_FAILED": 6,
		"DAEMON_FAILED":          8,
	}
)

func (x ConnectInfo_ErrType) Enum() *ConnectInfo_ErrType {
	p := new(ConnectInfo_ErrType)
	*p = x
	return p
}

func (x ConnectInfo_ErrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectInfo_ErrType) Descriptor() protoreflect.EnumDescriptor {
	return file_connector_connector_proto_enumTypes[0].Descriptor()
}

func (ConnectInfo_ErrType) Type() protoreflect.EnumType {
	return &file_connector_connector_proto_enumTypes[0]
}

func (x ConnectInfo_ErrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectInfo_ErrType.Descriptor instead.
func (ConnectInfo_ErrType) EnumDescriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{2, 0}
}

type UninstallRequest_UninstallType int32

const (
	UninstallRequest_UNSPECIFIED UninstallRequest_UninstallType = 0
	// Uninstalls an agent from the named workloads
	UninstallRequest_NAMED_AGENTS UninstallRequest_UninstallType = 1
	// Uninstalls all agents
	UninstallRequest_ALL_AGENTS UninstallRequest_UninstallType = 2
)

// Enum value maps for UninstallRequest_UninstallType.
var (
	UninstallRequest_UninstallType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NAMED_AGENTS",
		2: "ALL_AGENTS",
	}
	UninstallRequest_UninstallType_value = map[string]int32{
		"UNSPECIFIED":  0,
		"NAMED_AGENTS": 1,
		"ALL_AGENTS":   2,
	}
)

func (x UninstallRequest_UninstallType) Enum() *UninstallRequest_UninstallType {
	p := new(UninstallRequest_UninstallType)
	*p = x
	return p
}

func (x UninstallRequest_UninstallType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UninstallRequest_UninstallType) Descriptor() protoreflect.EnumDescriptor {
	return file_connector_connector_proto_enumTypes[1].Descriptor()
}

func (UninstallRequest_UninstallType) Type() protoreflect.EnumType {
	return &file_connector_connector_proto_enumTypes[1]
}

func (x UninstallRequest_UninstallType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UninstallRequest_UninstallType.Descriptor instead.
func (UninstallRequest_UninstallType) EnumDescriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{3, 0}
}

// Bitmap filter
type ListRequest_Filter int32

const (
	ListRequest_UNSPECIFIED      ListRequest_Filter = 0
	ListRequest_INTERCEPTS       ListRequest_Filter = 1
	ListRequest_REPLACEMENTS     ListRequest_Filter = 2
	ListRequest_INGESTS          ListRequest_Filter = 4
	ListRequest_WIRETAPS         ListRequest_Filter = 8
	ListRequest_INSTALLED_AGENTS ListRequest_Filter = 16
	ListRequest_EVERYTHING       ListRequest_Filter = 31
)

// Enum value maps for ListRequest_Filter.
var (
	ListRequest_Filter_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "INTERCEPTS",
		2:  "REPLACEMENTS",
		4:  "INGESTS",
		8:  "WIRETAPS",
		16: "INSTALLED_AGENTS",
		31: "EVERYTHING",
	}
	ListRequest_Filter_value = map[string]int32{
		"UNSPECIFIED":      0,
		"INTERCEPTS":       1,
		"REPLACEMENTS":     2,
		"INGESTS":          4,
		"WIRETAPS":         8,
		"INSTALLED_AGENTS": 16,
		"EVERYTHING":       31,
	}
)

func (x ListRequest_Filter) Enum() *ListRequest_Filter {
	p := new(ListRequest_Filter)
	*p = x
	return p
}

func (x ListRequest_Filter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListRequest_Filter) Descriptor() protoreflect.EnumDescriptor {
	return file_connector_connector_proto_enumTypes[2].Descriptor()
}

func (ListRequest_Filter) Type() protoreflect.EnumType {
	return &file_connector_connector_proto_enumTypes[2]
}

func (x ListRequest_Filter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListRequest_Filter.Descriptor instead.
func (ListRequest_Filter) EnumDescriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{5, 0}
}

type LogLevelRequest_Scope int32

const (
	LogLevelRequest_UNSPECIFIED LogLevelRequest_Scope = 0
	LogLevelRequest_LOCAL_ONLY  LogLevelRequest_Scope = 1 // applies only to the local daemon processes
	LogLevelRequest_REMOTE_ONLY LogLevelRequest_Scope = 2 // applies only to traffic-manager and traffic-agents
)

// Enum value maps for LogLevelRequest_Scope.
var (
	LogLevelRequest_Scope_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LOCAL_ONLY",
		2: "REMOTE_ONLY",
	}
	LogLevelRequest_Scope_value = map[string]int32{
		"UNSPECIFIED": 0,
		"LOCAL_ONLY":  1,
		"REMOTE_ONLY": 2,
	}
)

func (x LogLevelRequest_Scope) Enum() *LogLevelRequest_Scope {
	p := new(LogLevelRequest_Scope)
	*p = x
	return p
}

func (x LogLevelRequest_Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevelRequest_Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_connector_connector_proto_enumTypes[3].Descriptor()
}

func (LogLevelRequest_Scope) Type() protoreflect.EnumType {
	return &file_connector_connector_proto_enumTypes[3]
}

func (x LogLevelRequest_Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevelRequest_Scope.Descriptor instead.
func (LogLevelRequest_Scope) EnumDescriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{13, 0}
}

type Interceptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the intercept that is served by this interceptor process
	InterceptId string `protobuf:"bytes,1,opt,name=intercept_id,json=interceptId,proto3" json:"intercept_id,omitempty"`
	// The pid of the interceptor process
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// Name or ID of container, in case the intercept handler runs in Docker
	ContainerName string `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interceptor) Reset() {
	*x = Interceptor{}
	mi := &file_connector_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interceptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interceptor) ProtoMessage() {}

func (x *Interceptor) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interceptor.ProtoReflect.Descriptor instead.
func (*Interceptor) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{0}
}

func (x *Interceptor) GetInterceptId() string {
	if x != nil {
		return x.InterceptId
	}
	return ""
}

func (x *Interceptor) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Interceptor) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

// ConnectRequest contains the information needed to connect ot a cluster.
type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kubernetes flags from the telepresence connect command
	KubeFlags map[string]string `protobuf:"bytes,1,rep,name=kube_flags,json=kubeFlags,proto3" json:"kube_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The kubernetes flags used by a containerized daemon
	ContainerKubeFlagOverrides map[string]string           `protobuf:"bytes,9,rep,name=container_kube_flag_overrides,json=containerKubeFlagOverrides,proto3" json:"container_kube_flag_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MappedNamespaces           []string                    `protobuf:"bytes,2,rep,name=mapped_namespaces,json=mappedNamespaces,proto3" json:"mapped_namespaces,omitempty"`
	Name                       string                      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsPodDaemon                bool                        `protobuf:"varint,4,opt,name=is_pod_daemon,json=isPodDaemon,proto3" json:"is_pod_daemon,omitempty"`
	AlsoProxy                  []string                    `protobuf:"bytes,5,rep,name=also_proxy,json=alsoProxy,proto3" json:"also_proxy,omitempty"`    // protolint:disable:this REPEATED_FIELD_NAMES_PLURALIZED
	NeverProxy                 []string                    `protobuf:"bytes,6,rep,name=never_proxy,json=neverProxy,proto3" json:"never_proxy,omitempty"` // protolint:disable:this REPEATED_FIELD_NAMES_PLURALIZED
	AllowConflictingSubnets    []string                    `protobuf:"bytes,10,rep,name=allow_conflicting_subnets,json=allowConflictingSubnets,proto3" json:"allow_conflicting_subnets,omitempty"`
	SubnetViaWorkloads         []*daemon.SubnetViaWorkload `protobuf:"bytes,11,rep,name=subnet_via_workloads,json=subnetViaWorkloads,proto3" json:"subnet_via_workloads,omitempty"`
	ManagerNamespace           string                      `protobuf:"bytes,7,opt,name=manager_namespace,json=managerNamespace,proto3" json:"manager_namespace,omitempty"`
	Environment                map[string]string           `protobuf:"bytes,8,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Kubeconfig YAML, if not to be loaded from file.
	KubeconfigData []byte `protobuf:"bytes,12,opt,name=kubeconfig_data,json=kubeconfigData,proto3,oneof" json:"kubeconfig_data,omitempty"`
	ClientId       string `protobuf:"bytes,13,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_connector_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetKubeFlags() map[string]string {
	if x != nil {
		return x.KubeFlags
	}
	return nil
}

func (x *ConnectRequest) GetContainerKubeFlagOverrides() map[string]string {
	if x != nil {
		return x.ContainerKubeFlagOverrides
	}
	return nil
}

func (x *ConnectRequest) GetMappedNamespaces() []string {
	if x != nil {
		return x.MappedNamespaces
	}
	return nil
}

func (x *ConnectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectRequest) GetIsPodDaemon() bool {
	if x != nil {
		return x.IsPodDaemon
	}
	return false
}

func (x *ConnectRequest) GetAlsoProxy() []string {
	if x != nil {
		return x.AlsoProxy
	}
	return nil
}

func (x *ConnectRequest) GetNeverProxy() []string {
	if x != nil {
		return x.NeverProxy
	}
	return nil
}

func (x *ConnectRequest) GetAllowConflictingSubnets() []string {
	if x != nil {
		return x.AllowConflictingSubnets
	}
	return nil
}

func (x *ConnectRequest) GetSubnetViaWorkloads() []*daemon.SubnetViaWorkload {
	if x != nil {
		return x.SubnetViaWorkloads
	}
	return nil
}

func (x *ConnectRequest) GetManagerNamespace() string {
	if x != nil {
		return x.ManagerNamespace
	}
	return ""
}

func (x *ConnectRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ConnectRequest) GetKubeconfigData() []byte {
	if x != nil {
		return x.KubeconfigData
	}
	return nil
}

func (x *ConnectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ConnectInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error ConnectInfo_ErrType    `protobuf:"varint,1,opt,name=error,proto3,enum=telepresence.connector.ConnectInfo_ErrType" json:"error,omitempty"`
	// only set for some error codes, see above
	ErrorText      string              `protobuf:"bytes,2,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
	ErrorCategory  int32               `protobuf:"varint,12,opt,name=error_category,json=errorCategory,proto3" json:"error_category,omitempty"`
	ClusterServer  string              `protobuf:"bytes,3,opt,name=cluster_server,json=clusterServer,proto3" json:"cluster_server,omitempty"`
	ClusterContext string              `protobuf:"bytes,4,opt,name=cluster_context,json=clusterContext,proto3" json:"cluster_context,omitempty"`
	Version        *common.VersionInfo `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// The name of the connection
	ConnectionName string `protobuf:"bytes,16,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	// The kubernetes flags from the telepresence connect command when the connection was established
	KubeFlags map[string]string `protobuf:"bytes,17,rep,name=kube_flags,json=kubeFlags,proto3" json:"kube_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// the namespace that the connector is connected to.
	Namespace          string                         `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ManagerInstallId   string                         `protobuf:"bytes,7,opt,name=manager_install_id,json=managerInstallId,proto3" json:"manager_install_id,omitempty"`
	Intercepts         *manager.InterceptInfoSnapshot `protobuf:"bytes,8,opt,name=intercepts,proto3" json:"intercepts,omitempty"`
	Ingests            []*IngestInfo                  `protobuf:"bytes,9,rep,name=ingests,proto3" json:"ingests,omitempty"`
	SessionInfo        *manager.SessionInfo           `protobuf:"bytes,10,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	ManagerVersion     *manager.VersionInfo2          `protobuf:"bytes,19,opt,name=manager_version,json=managerVersion,proto3" json:"manager_version,omitempty"`
	DaemonStatus       *daemon.DaemonStatus           `protobuf:"bytes,13,opt,name=daemon_status,json=daemonStatus,proto3" json:"daemon_status,omitempty"`
	ManagerNamespace   string                         `protobuf:"bytes,14,opt,name=manager_namespace,json=managerNamespace,proto3" json:"manager_namespace,omitempty"`
	MappedNamespaces   []string                       `protobuf:"bytes,15,rep,name=mapped_namespaces,json=mappedNamespaces,proto3" json:"mapped_namespaces,omitempty"`
	SubnetViaWorkloads []*daemon.SubnetViaWorkload    `protobuf:"bytes,18,rep,name=subnet_via_workloads,json=subnetViaWorkloads,proto3" json:"subnet_via_workloads,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConnectInfo) Reset() {
	*x = ConnectInfo{}
	mi := &file_connector_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInfo) ProtoMessage() {}

func (x *ConnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInfo.ProtoReflect.Descriptor instead.
func (*ConnectInfo) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectInfo) GetError() ConnectInfo_ErrType {
	if x != nil {
		return x.Error
	}
	return ConnectInfo_UNSPECIFIED
}

func (x *ConnectInfo) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

func (x *ConnectInfo) GetErrorCategory() int32 {
	if x != nil {
		return x.ErrorCategory
	}
	return 0
}

func (x *ConnectInfo) GetClusterServer() string {
	if x != nil {
		return x.ClusterServer
	}
	return ""
}

func (x *ConnectInfo) GetClusterContext() string {
	if x != nil {
		return x.ClusterContext
	}
	return ""
}

func (x *ConnectInfo) GetVersion() *common.VersionInfo {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ConnectInfo) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

func (x *ConnectInfo) GetKubeFlags() map[string]string {
	if x != nil {
		return x.KubeFlags
	}
	return nil
}

func (x *ConnectInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConnectInfo) GetManagerInstallId() string {
	if x != nil {
		return x.ManagerInstallId
	}
	return ""
}

func (x *ConnectInfo) GetIntercepts() *manager.InterceptInfoSnapshot {
	if x != nil {
		return x.Intercepts
	}
	return nil
}

func (x *ConnectInfo) GetIngests() []*IngestInfo {
	if x != nil {
		return x.Ingests
	}
	return nil
}

func (x *ConnectInfo) GetSessionInfo() *manager.SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

func (x *ConnectInfo) GetManagerVersion() *manager.VersionInfo2 {
	if x != nil {
		return x.ManagerVersion
	}
	return nil
}

func (x *ConnectInfo) GetDaemonStatus() *daemon.DaemonStatus {
	if x != nil {
		return x.DaemonStatus
	}
	return nil
}

func (x *ConnectInfo) GetManagerNamespace() string {
	if x != nil {
		return x.ManagerNamespace
	}
	return ""
}

func (x *ConnectInfo) GetMappedNamespaces() []string {
	if x != nil {
		return x.MappedNamespaces
	}
	return nil
}

func (x *ConnectInfo) GetSubnetViaWorkloads() []*daemon.SubnetViaWorkload {
	if x != nil {
		return x.SubnetViaWorkloads
	}
	return nil
}

type UninstallRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	UninstallType UninstallRequest_UninstallType `protobuf:"varint,1,opt,name=uninstall_type,json=uninstallType,proto3,enum=telepresence.connector.UninstallRequest_UninstallType" json:"uninstall_type,omitempty"`
	Agents        []string                       `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	// Namespace of agents to remove.
	Namespace     string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallRequest) Reset() {
	*x = UninstallRequest{}
	mi := &file_connector_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallRequest) ProtoMessage() {}

func (x *UninstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallRequest.ProtoReflect.Descriptor instead.
func (*UninstallRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{3}
}

func (x *UninstallRequest) GetUninstallType() UninstallRequest_UninstallType {
	if x != nil {
		return x.UninstallType
	}
	return UninstallRequest_UNSPECIFIED
}

func (x *UninstallRequest) GetAgents() []string {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *UninstallRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CreateInterceptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// No need to set spec.client; the connector will fill that in for
	// you.
	Spec           *manager.InterceptSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	MountPoint     string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	AgentImage     string                 `protobuf:"bytes,3,opt,name=agent_image,json=agentImage,proto3" json:"agent_image,omitempty"`
	IsPodDaemon    bool                   `protobuf:"varint,4,opt,name=is_pod_daemon,json=isPodDaemon,proto3" json:"is_pod_daemon,omitempty"`
	ExtendedInfo   []byte                 `protobuf:"bytes,5,opt,name=extended_info,json=extendedInfo,proto3" json:"extended_info,omitempty"`
	LocalMountPort int32                  `protobuf:"varint,6,opt,name=local_mount_port,json=localMountPort,proto3" json:"local_mount_port,omitempty"`
	MountReadOnly  bool                   `protobuf:"varint,7,opt,name=mount_read_only,json=mountReadOnly,proto3" json:"mount_read_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateInterceptRequest) Reset() {
	*x = CreateInterceptRequest{}
	mi := &file_connector_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterceptRequest) ProtoMessage() {}

func (x *CreateInterceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterceptRequest.ProtoReflect.Descriptor instead.
func (*CreateInterceptRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInterceptRequest) GetSpec() *manager.InterceptSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateInterceptRequest) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *CreateInterceptRequest) GetAgentImage() string {
	if x != nil {
		return x.AgentImage
	}
	return ""
}

func (x *CreateInterceptRequest) GetIsPodDaemon() bool {
	if x != nil {
		return x.IsPodDaemon
	}
	return false
}

func (x *CreateInterceptRequest) GetExtendedInfo() []byte {
	if x != nil {
		return x.ExtendedInfo
	}
	return nil
}

func (x *CreateInterceptRequest) GetLocalMountPort() int32 {
	if x != nil {
		return x.LocalMountPort
	}
	return 0
}

func (x *CreateInterceptRequest) GetMountReadOnly() bool {
	if x != nil {
		return x.MountReadOnly
	}
	return false
}

type ListRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Filter ListRequest_Filter     `protobuf:"varint,1,opt,name=filter,proto3,enum=telepresence.connector.ListRequest_Filter" json:"filter,omitempty"`
	// Namespace to list.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_connector_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetFilter() ListRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return ListRequest_UNSPECIFIED
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type IngestIdentifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the workload that holds the desire container.
	WorkloadName string `protobuf:"bytes,1,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	// The name of the desired container. Must be set when the workload contains more
	// than one container candidate.
	ContainerName string `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestIdentifier) Reset() {
	*x = IngestIdentifier{}
	mi := &file_connector_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestIdentifier) ProtoMessage() {}

func (x *IngestIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestIdentifier.ProtoReflect.Descriptor instead.
func (*IngestIdentifier) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{6}
}

func (x *IngestIdentifier) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *IngestIdentifier) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type IngestRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Identifier *IngestIdentifier      `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Desired mount point. Can be set to "true" to generated temporary mount point,
	// "false" to prevent that mounting takes place, an explicit path to use for the
	// mount or an empty string in combination with a non-zero local_mount_port.
	MountPoint string `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	// Local port where an sftp client can connect when doing docker volume mounts.
	LocalMountPort int32 `protobuf:"varint,3,opt,name=local_mount_port,json=localMountPort,proto3" json:"local_mount_port,omitempty"`
	// Extra ports that will be forwarded from the intercepting client's localhost
	// to the intercepted pod. Each entry is a string containing a port number followed
	// by an optional "/TCP" or "/UDP".
	LocalPorts    []string `protobuf:"bytes,4,rep,name=local_ports,json=localPorts,proto3" json:"local_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_connector_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{7}
}

func (x *IngestRequest) GetIdentifier() *IngestIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *IngestRequest) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *IngestRequest) GetLocalMountPort() int32 {
	if x != nil {
		return x.LocalMountPort
	}
	return 0
}

func (x *IngestRequest) GetLocalPorts() []string {
	if x != nil {
		return x.LocalPorts
	}
	return nil
}

type IngestInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of ingested workload
	Workload     string `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	WorkloadKind string `protobuf:"bytes,2,opt,name=workload_kind,json=workloadKind,proto3" json:"workload_kind,omitempty"`
	// Name of ingested container
	Container string `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	// The directory where the intercept mounts can be found in the agent.
	MountPoint string `protobuf:"bytes,4,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	// The IP of the ingested pod.
	PodIp string `protobuf:"bytes,5,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	// The port where the SFTP server listens.
	SftpPort int32 `protobuf:"varint,6,opt,name=sftp_port,json=sftpPort,proto3" json:"sftp_port,omitempty"`
	// The port where the FTP server listens.
	FtpPort int32 `protobuf:"varint,7,opt,name=ftp_port,json=ftpPort,proto3" json:"ftp_port,omitempty"`
	// The environment of the ingested container
	Environment map[string]string `protobuf:"bytes,8,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The directory where the client mounts the remote mount_point.
	ClientMountPoint string `protobuf:"bytes,9,opt,name=client_mount_point,json=clientMountPoint,proto3" json:"client_mount_point,omitempty"`
	// Map of mount path -> MountPolicy
	Mounts        map[string]int32 `protobuf:"bytes,10,rep,name=mounts,proto3" json:"mounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestInfo) Reset() {
	*x = IngestInfo{}
	mi := &file_connector_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestInfo) ProtoMessage() {}

func (x *IngestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestInfo.ProtoReflect.Descriptor instead.
func (*IngestInfo) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{8}
}

func (x *IngestInfo) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *IngestInfo) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

func (x *IngestInfo) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *IngestInfo) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *IngestInfo) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *IngestInfo) GetSftpPort() int32 {
	if x != nil {
		return x.SftpPort
	}
	return 0
}

func (x *IngestInfo) GetFtpPort() int32 {
	if x != nil {
		return x.FtpPort
	}
	return 0
}

func (x *IngestInfo) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *IngestInfo) GetClientMountPoint() string {
	if x != nil {
		return x.ClientMountPoint
	}
	return ""
}

func (x *IngestInfo) GetMounts() map[string]int32 {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type WatchWorkloadsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace to watch.
	Namespaces    []string `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchWorkloadsRequest) Reset() {
	*x = WatchWorkloadsRequest{}
	mi := &file_connector_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchWorkloadsRequest) ProtoMessage() {}

func (x *WatchWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*WatchWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{9}
}

func (x *WatchWorkloadsRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// WorkloadInfo contains information about a workload
// https://kubernetes.io/docs/concepts/workloads/
type WorkloadInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of workload
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace of workload
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Reason why workload cannot be intercepted, or empty if it can.
	NotInterceptableReason string `protobuf:"bytes,3,opt,name=not_interceptable_reason,json=notInterceptableReason,proto3" json:"not_interceptable_reason,omitempty"`
	// InterceptInfo reported from the traffic manager in case the workload is currently intercepted
	InterceptInfo []*manager.InterceptInfo `protobuf:"bytes,4,rep,name=intercept_info,json=interceptInfo,proto3" json:"intercept_info,omitempty"`
	// IngestInfo reported from the traffic manager in case the workload is currently intercepted
	IngestInfo []*IngestInfo `protobuf:"bytes,5,rep,name=ingest_info,json=ingestInfo,proto3" json:"ingest_info,omitempty"`
	// Workload Resource type (e.g. Deployment, ReplicaSet, StatefulSet, Rollout)
	WorkloadResourceType string `protobuf:"bytes,6,opt,name=workload_resource_type,json=workloadResourceType,proto3" json:"workload_resource_type,omitempty"`
	Uid                  string `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	AgentVersion         string `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WorkloadInfo) Reset() {
	*x = WorkloadInfo{}
	mi := &file_connector_connector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadInfo) ProtoMessage() {}

func (x *WorkloadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadInfo.ProtoReflect.Descriptor instead.
func (*WorkloadInfo) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{10}
}

func (x *WorkloadInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadInfo) GetNotInterceptableReason() string {
	if x != nil {
		return x.NotInterceptableReason
	}
	return ""
}

func (x *WorkloadInfo) GetInterceptInfo() []*manager.InterceptInfo {
	if x != nil {
		return x.InterceptInfo
	}
	return nil
}

func (x *WorkloadInfo) GetIngestInfo() []*IngestInfo {
	if x != nil {
		return x.IngestInfo
	}
	return nil
}

func (x *WorkloadInfo) GetWorkloadResourceType() string {
	if x != nil {
		return x.WorkloadResourceType
	}
	return ""
}

func (x *WorkloadInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WorkloadInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type WorkloadInfoSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*WorkloadInfo        `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadInfoSnapshot) Reset() {
	*x = WorkloadInfoSnapshot{}
	mi := &file_connector_connector_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadInfoSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadInfoSnapshot) ProtoMessage() {}

func (x *WorkloadInfoSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadInfoSnapshot.ProtoReflect.Descriptor instead.
func (*WorkloadInfoSnapshot) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{11}
}

func (x *WorkloadInfoSnapshot) GetWorkloads() []*WorkloadInfo {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type InterceptResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterceptInfo *manager.InterceptInfo `protobuf:"bytes,1,opt,name=intercept_info,json=interceptInfo,proto3" json:"intercept_info,omitempty"`
	Error         common.InterceptError  `protobuf:"varint,2,opt,name=error,proto3,enum=telepresence.common.InterceptError" json:"error,omitempty"`
	ErrorText     string                 `protobuf:"bytes,3,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
	ErrorCategory int32                  `protobuf:"varint,7,opt,name=error_category,json=errorCategory,proto3" json:"error_category,omitempty"`
	// The service uid associated with the workload intercepted
	ServiceUid string `protobuf:"bytes,5,opt,name=service_uid,json=serviceUid,proto3" json:"service_uid,omitempty"`
	// The kind of workload in this intercept
	WorkloadKind  string `protobuf:"bytes,6,opt,name=workload_kind,json=workloadKind,proto3" json:"workload_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptResult) Reset() {
	*x = InterceptResult{}
	mi := &file_connector_connector_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptResult) ProtoMessage() {}

func (x *InterceptResult) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptResult.ProtoReflect.Descriptor instead.
func (*InterceptResult) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{12}
}

func (x *InterceptResult) GetInterceptInfo() *manager.InterceptInfo {
	if x != nil {
		return x.InterceptInfo
	}
	return nil
}

func (x *InterceptResult) GetError() common.InterceptError {
	if x != nil {
		return x.Error
	}
	return common.InterceptError(0)
}

func (x *InterceptResult) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

func (x *InterceptResult) GetErrorCategory() int32 {
	if x != nil {
		return x.ErrorCategory
	}
	return 0
}

func (x *InterceptResult) GetServiceUid() string {
	if x != nil {
		return x.ServiceUid
	}
	return ""
}

func (x *InterceptResult) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

type LogLevelRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	LogLevel string                 `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	// The time that this log-level will be in effect before
	// falling back to the configured log-level.
	Duration      *durationpb.Duration  `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Scope         LogLevelRequest_Scope `protobuf:"varint,3,opt,name=scope,proto3,enum=telepresence.connector.LogLevelRequest_Scope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLevelRequest) Reset() {
	*x = LogLevelRequest{}
	mi := &file_connector_connector_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLevelRequest) ProtoMessage() {}

func (x *LogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLevelRequest.ProtoReflect.Descriptor instead.
func (*LogLevelRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{13}
}

func (x *LogLevelRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *LogLevelRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *LogLevelRequest) GetScope() LogLevelRequest_Scope {
	if x != nil {
		return x.Scope
	}
	return LogLevelRequest_UNSPECIFIED
}

type LogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether or not logs from the traffic-manager are desired.
	TrafficManager bool `protobuf:"varint,1,opt,name=traffic_manager,json=trafficManager,proto3" json:"traffic_manager,omitempty"`
	// Whether or not to get the pod yaml deployed to the cluster.
	GetPodYaml bool `protobuf:"varint,2,opt,name=get_pod_yaml,json=getPodYaml,proto3" json:"get_pod_yaml,omitempty"`
	// The traffic-agent(s) logs are desired from. Can be `all`, `False`,
	// or substring to filter based on pod names.
	Agents string `protobuf:"bytes,3,opt,name=agents,proto3" json:"agents,omitempty"`
	// Directory that the logs will be exported to
	ExportDir     string `protobuf:"bytes,4,opt,name=export_dir,json=exportDir,proto3" json:"export_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_connector_connector_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{14}
}

func (x *LogsRequest) GetTrafficManager() bool {
	if x != nil {
		return x.TrafficManager
	}
	return false
}

func (x *LogsRequest) GetGetPodYaml() bool {
	if x != nil {
		return x.GetPodYaml
	}
	return false
}

func (x *LogsRequest) GetAgents() string {
	if x != nil {
		return x.Agents
	}
	return ""
}

func (x *LogsRequest) GetExportDir() string {
	if x != nil {
		return x.ExportDir
	}
	return ""
}

type LogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// General error that isn't associated with a pod such as failing to list the pods.
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// pod_info contains one entry per created file name name. The value is either the string
	// "ok" indicating that the file exists, or an error string with info why it could not
	// be created.
	PodInfo       map[string]string `protobuf:"bytes,2,rep,name=pod_info,json=podInfo,proto3" json:"pod_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_connector_connector_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{15}
}

func (x *LogsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LogsResponse) GetPodInfo() map[string]string {
	if x != nil {
		return x.PodInfo
	}
	return nil
}

type GetNamespacesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ForClientAccess bool                   `protobuf:"varint,1,opt,name=for_client_access,json=forClientAccess,proto3" json:"for_client_access,omitempty"`
	Prefix          string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNamespacesRequest) Reset() {
	*x = GetNamespacesRequest{}
	mi := &file_connector_connector_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespacesRequest) ProtoMessage() {}

func (x *GetNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespacesRequest.ProtoReflect.Descriptor instead.
func (*GetNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{16}
}

func (x *GetNamespacesRequest) GetForClientAccess() bool {
	if x != nil {
		return x.ForClientAccess
	}
	return false
}

func (x *GetNamespacesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type GetNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []string               `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamespacesResponse) Reset() {
	*x = GetNamespacesResponse{}
	mi := &file_connector_connector_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespacesResponse) ProtoMessage() {}

func (x *GetNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespacesResponse.ProtoReflect.Descriptor instead.
func (*GetNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{17}
}

func (x *GetNamespacesResponse) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type ClientConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_connector_connector_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{18}
}

func (x *ClientConfig) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

// ClusterSubnets are the cluster subnets that the daemon has detected that need to be
// routed
type ClusterSubnets struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pod_subnets are the subnets that pods go into
	PodSubnets []*manager.IPNet `protobuf:"bytes,1,rep,name=pod_subnets,json=podSubnets,proto3" json:"pod_subnets,omitempty"`
	// svc_subnets are subnets that services go into
	SvcSubnets    []*manager.IPNet `protobuf:"bytes,2,rep,name=svc_subnets,json=svcSubnets,proto3" json:"svc_subnets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSubnets) Reset() {
	*x = ClusterSubnets{}
	mi := &file_connector_connector_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSubnets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSubnets) ProtoMessage() {}

func (x *ClusterSubnets) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSubnets.ProtoReflect.Descriptor instead.
func (*ClusterSubnets) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{19}
}

func (x *ClusterSubnets) GetPodSubnets() []*manager.IPNet {
	if x != nil {
		return x.PodSubnets
	}
	return nil
}

func (x *ClusterSubnets) GetSvcSubnets() []*manager.IPNet {
	if x != nil {
		return x.SvcSubnets
	}
	return nil
}

type ResolveSyntheticRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The synthetic IP to be resolved.
	Ip []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Resolve the IP into a name, but do not make an attempt to resolve the name through DNS.
	NameOnly      bool `protobuf:"varint,2,opt,name=name_only,json=nameOnly,proto3" json:"name_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSyntheticRequest) Reset() {
	*x = ResolveSyntheticRequest{}
	mi := &file_connector_connector_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSyntheticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSyntheticRequest) ProtoMessage() {}

func (x *ResolveSyntheticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSyntheticRequest.ProtoReflect.Descriptor instead.
func (*ResolveSyntheticRequest) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{20}
}

func (x *ResolveSyntheticRequest) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *ResolveSyntheticRequest) GetNameOnly() bool {
	if x != nil {
		return x.NameOnly
	}
	return false
}

type ResolveSyntheticResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name that the synthetic IP resolved to.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The IP resulting from a DNS lookup using the resolved name.
	ResolvedIp    []byte `protobuf:"bytes,2,opt,name=resolved_ip,json=resolvedIp,proto3" json:"resolved_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSyntheticResponse) Reset() {
	*x = ResolveSyntheticResponse{}
	mi := &file_connector_connector_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSyntheticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSyntheticResponse) ProtoMessage() {}

func (x *ResolveSyntheticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connector_connector_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSyntheticResponse.ProtoReflect.Descriptor instead.
func (*ResolveSyntheticResponse) Descriptor() ([]byte, []int) {
	return file_connector_connector_proto_rawDescGZIP(), []int{21}
}

func (x *ResolveSyntheticResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveSyntheticResponse) GetResolvedIp() []byte {
	if x != nil {
		return x.ResolvedIp
	}
	return nil
}

var File_connector_connector_proto protoreflect.FileDescriptor

const file_connector_connector_proto_rawDesc = "" +
	"\n" +
	"\x19connector/connector.proto\x12\x16telepresence.connector\x1a\x13common/errors.proto\x1a\x14common/version.proto\x1a\x13daemon/daemon.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15manager/manager.proto\"i\n" +
	"\vInterceptor\x12!\n" +
	"\fintercept_id\x18\x01 \x01(\tR\vinterceptId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\"\xe1\a\n" +
	"\x0eConnectRequest\x12T\n" +
	"\n" +
	"kube_flags\x18\x01 \x03(\v25.telepresence.connector.ConnectRequest.KubeFlagsEntryR\tkubeFlags\x12\x89\x01\n" +
	"\x1dcontainer_kube_flag_overrides\x18\t \x03(\v2F.telepresence.connector.ConnectRequest.ContainerKubeFlagOverridesEntryR\x1acontainerKubeFlagOverrides\x12+\n" +
	"\x11mapped_namespaces\x18\x02 \x03(\tR\x10mappedNamespaces\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\ris_pod_daemon\x18\x04 \x01(\bR\visPodDaemon\x12\x1d\n" +
	"\n" +
	"also_proxy\x18\x05 \x03(\tR\talsoProxy\x12\x1f\n" +
	"\vnever_proxy\x18\x06 \x03(\tR\n" +
	"neverProxy\x12:\n" +
	"\x19allow_conflicting_subnets\x18\n" +
	" \x03(\tR\x17allowConflictingSubnets\x12X\n" +
	"\x14subnet_via_workloads\x18\v \x03(\v2&.telepresence.daemon.SubnetViaWorkloadR\x12subnetViaWorkloads\x12+\n" +
	"\x11manager_namespace\x18\a \x01(\tR\x10managerNamespace\x12Y\n" +
	"\venvironment\x18\b \x03(\v27.telepresence.connector.ConnectRequest.EnvironmentEntryR\venvironment\x12,\n" +
	"\x0fkubeconfig_data\x18\f \x01(\fH\x00R\x0ekubeconfigData\x88\x01\x01\x12\x1b\n" +
	"\tclient_id\x18\r \x01(\tR\bclientId\x1a<\n" +
	"\x0eKubeFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aM\n" +
	"\x1fContainerKubeFlagOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_kubeconfig_data\"\x8a\n" +
	"\n" +
	"\vConnectInfo\x12A\n" +
	"\x05error\x18\x01 \x01(\x0e2+.telepresence.connector.ConnectInfo.ErrTypeR\x05error\x12\x1d\n" +
	"\n" +
	"error_text\x18\x02 \x01(\tR\terrorText\x12%\n" +
	"\x0eerror_category\x18\f \x01(\x05R\rerrorCategory\x12%\n" +
	"\x0ecluster_server\x18\x03 \x01(\tR\rclusterServer\x12'\n" +
	"\x0fcluster_context\x18\x04 \x01(\tR\x0eclusterContext\x12:\n" +
	"\aversion\x18\x05 \x01(\v2 .telepresence.common.VersionInfoR\aversion\x12'\n" +
	"\x0fconnection_name\x18\x10 \x01(\tR\x0econnectionName\x12Q\n" +
	"\n" +
	"kube_flags\x18\x11 \x03(\v22.telepresence.connector.ConnectInfo.KubeFlagsEntryR\tkubeFlags\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12,\n" +
	"\x12manager_install_id\x18\a \x01(\tR\x10managerInstallId\x12K\n" +
	"\n" +
	"intercepts\x18\b \x01(\v2+.telepresence.manager.InterceptInfoSnapshotR\n" +
	"intercepts\x12<\n" +
	"\aingests\x18\t \x03(\v2\".telepresence.connector.IngestInfoR\aingests\x12D\n" +
	"\fsession_info\x18\n" +
	" \x01(\v2!.telepresence.manager.SessionInfoR\vsessionInfo\x12K\n" +
	"\x0fmanager_version\x18\x13 \x01(\v2\".telepresence.manager.VersionInfo2R\x0emanagerVersion\x12F\n" +
	"\rdaemon_status\x18\r \x01(\v2!.telepresence.daemon.DaemonStatusR\fdaemonStatus\x12+\n" +
	"\x11manager_namespace\x18\x0e \x01(\tR\x10managerNamespace\x12+\n" +
	"\x11mapped_namespaces\x18\x0f \x03(\tR\x10mappedNamespaces\x12X\n" +
	"\x14subnet_via_workloads\x18\x12 \x03(\v2&.telepresence.daemon.SubnetViaWorkloadR\x12subnetViaWorkloads\x1a<\n" +
	"\x0eKubeFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x01\n" +
	"\aErrType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x01\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x05\x12\x15\n" +
	"\x11ALREADY_CONNECTED\x10\x02\x12\x10\n" +
	"\fMUST_RESTART\x10\a\x12\x10\n" +
	"\fDISCONNECTED\x10\x03\x12\x12\n" +
	"\x0eCLUSTER_FAILED\x10\x04\x12\x1a\n" +
	"\x16TRAFFIC_MANAGER_FAILED\x10\x06\x12\x11\n" +
	"\rDAEMON_FAILED\x10\bJ\x04\b\v\x10\f\"\xeb\x01\n" +
	"\x10UninstallRequest\x12]\n" +
	"\x0euninstall_type\x18\x01 \x01(\x0e26.telepresence.connector.UninstallRequest.UninstallTypeR\runinstallType\x12\x16\n" +
	"\x06agents\x18\x02 \x03(\tR\x06agents\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"B\n" +
	"\rUninstallType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x10\n" +
	"\fNAMED_AGENTS\x10\x01\x12\x0e\n" +
	"\n" +
	"ALL_AGENTS\x10\x02\"\xae\x02\n" +
	"\x16CreateInterceptRequest\x127\n" +
	"\x04spec\x18\x01 \x01(\v2#.telepresence.manager.InterceptSpecR\x04spec\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x1f\n" +
	"\vagent_image\x18\x03 \x01(\tR\n" +
	"agentImage\x12\"\n" +
	"\ris_pod_daemon\x18\x04 \x01(\bR\visPodDaemon\x12#\n" +
	"\rextended_info\x18\x05 \x01(\fR\fextendedInfo\x12(\n" +
	"\x10local_mount_port\x18\x06 \x01(\x05R\x0elocalMountPort\x12&\n" +
	"\x0fmount_read_only\x18\a \x01(\bR\rmountReadOnly\"\xed\x01\n" +
	"\vListRequest\x12B\n" +
	"\x06filter\x18\x01 \x01(\x0e2*.telepresence.connector.ListRequest.FilterR\x06filter\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"|\n" +
	"\x06Filter\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"INTERCEPTS\x10\x01\x12\x10\n" +
	"\fREPLACEMENTS\x10\x02\x12\v\n" +
	"\aINGESTS\x10\x04\x12\f\n" +
	"\bWIRETAPS\x10\b\x12\x14\n" +
	"\x10INSTALLED_AGENTS\x10\x10\x12\x0e\n" +
	"\n" +
	"EVERYTHING\x10\x1f\"^\n" +
	"\x10IngestIdentifier\x12#\n" +
	"\rworkload_name\x18\x01 \x01(\tR\fworkloadName\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\"\xc5\x01\n" +
	"\rIngestRequest\x12H\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2(.telepresence.connector.IngestIdentifierR\n" +
	"identifier\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12(\n" +
	"\x10local_mount_port\x18\x03 \x01(\x05R\x0elocalMountPort\x12\x1f\n" +
	"\vlocal_ports\x18\x04 \x03(\tR\n" +
	"localPorts\"\xa3\x04\n" +
	"\n" +
	"IngestInfo\x12\x1a\n" +
	"\bworkload\x18\x01 \x01(\tR\bworkload\x12#\n" +
	"\rworkload_kind\x18\x02 \x01(\tR\fworkloadKind\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x1f\n" +
	"\vmount_point\x18\x04 \x01(\tR\n" +
	"mountPoint\x12\x15\n" +
	"\x06pod_ip\x18\x05 \x01(\tR\x05podIp\x12\x1b\n" +
	"\tsftp_port\x18\x06 \x01(\x05R\bsftpPort\x12\x19\n" +
	"\bftp_port\x18\a \x01(\x05R\aftpPort\x12U\n" +
	"\venvironment\x18\b \x03(\v23.telepresence.connector.IngestInfo.EnvironmentEntryR\venvironment\x12,\n" +
	"\x12client_mount_point\x18\t \x01(\tR\x10clientMountPoint\x12F\n" +
	"\x06mounts\x18\n" +
	" \x03(\v2..telepresence.connector.IngestInfo.MountsEntryR\x06mounts\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vMountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"7\n" +
	"\x15WatchWorkloadsRequest\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\tR\n" +
	"namespaces\"\xf8\x02\n" +
	"\fWorkloadInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x128\n" +
	"\x18not_interceptable_reason\x18\x03 \x01(\tR\x16notInterceptableReason\x12J\n" +
	"\x0eintercept_info\x18\x04 \x03(\v2#.telepresence.manager.InterceptInfoR\rinterceptInfo\x12C\n" +
	"\vingest_info\x18\x05 \x03(\v2\".telepresence.connector.IngestInfoR\n" +
	"ingestInfo\x124\n" +
	"\x16workload_resource_type\x18\x06 \x01(\tR\x14workloadResourceType\x12\x10\n" +
	"\x03uid\x18\a \x01(\tR\x03uid\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\"Z\n" +
	"\x14WorkloadInfoSnapshot\x12B\n" +
	"\tworkloads\x18\x01 \x03(\v2$.telepresence.connector.WorkloadInfoR\tworkloads\"\xaa\x02\n" +
	"\x0fInterceptResult\x12J\n" +
	"\x0eintercept_info\x18\x01 \x01(\v2#.telepresence.manager.InterceptInfoR\rinterceptInfo\x129\n" +
	"\x05error\x18\x02 \x01(\x0e2#.telepresence.common.InterceptErrorR\x05error\x12\x1d\n" +
	"\n" +
	"error_text\x18\x03 \x01(\tR\terrorText\x12%\n" +
	"\x0eerror_category\x18\a \x01(\x05R\rerrorCategory\x12\x1f\n" +
	"\vservice_uid\x18\x05 \x01(\tR\n" +
	"serviceUid\x12#\n" +
	"\rworkload_kind\x18\x06 \x01(\tR\fworkloadKindJ\x04\b\x04\x10\x05\"\xe5\x01\n" +
	"\x0fLogLevelRequest\x12\x1b\n" +
	"\tlog_level\x18\x01 \x01(\tR\blogLevel\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12C\n" +
	"\x05scope\x18\x03 \x01(\x0e2-.telepresence.connector.LogLevelRequest.ScopeR\x05scope\"9\n" +
	"\x05Scope\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LOCAL_ONLY\x10\x01\x12\x0f\n" +
	"\vREMOTE_ONLY\x10\x02\"\x8f\x01\n" +
	"\vLogsRequest\x12'\n" +
	"\x0ftraffic_manager\x18\x01 \x01(\bR\x0etrafficManager\x12 \n" +
	"\fget_pod_yaml\x18\x02 \x01(\bR\n" +
	"getPodYaml\x12\x16\n" +
	"\x06agents\x18\x03 \x01(\tR\x06agents\x12\x1d\n" +
	"\n" +
	"export_dir\x18\x04 \x01(\tR\texportDir\"\xae\x01\n" +
	"\fLogsResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12L\n" +
	"\bpod_info\x18\x02 \x03(\v21.telepresence.connector.LogsResponse.PodInfoEntryR\apodInfo\x1a:\n" +
	"\fPodInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x14GetNamespacesRequest\x12*\n" +
	"\x11for_client_access\x18\x01 \x01(\bR\x0fforClientAccess\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"7\n" +
	"\x15GetNamespacesResponse\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\"\"\n" +
	"\fClientConfig\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\x8c\x01\n" +
	"\x0eClusterSubnets\x12<\n" +
	"\vpod_subnets\x18\x01 \x03(\v2\x1b.telepresence.manager.IPNetR\n" +
	"podSubnets\x12<\n" +
	"\vsvc_subnets\x18\x02 \x03(\v2\x1b.telepresence.manager.IPNetR\n" +
	"svcSubnets\"F\n" +
	"\x17ResolveSyntheticRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x1b\n" +
	"\tname_only\x18\x02 \x01(\bR\bnameOnly\"O\n" +
	"\x18ResolveSyntheticResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vresolved_ip\x18\x02 \x01(\fR\n" +
	"resolvedIp2\xf0\x16\n" +
	"\tConnector\x12C\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a .telepresence.common.VersionInfo\x12M\n" +
	"\x11RootDaemonVersion\x12\x16.google.protobuf.Empty\x1a .telepresence.common.VersionInfo\x12Q\n" +
	"\x15TrafficManagerVersion\x12\x16.google.protobuf.Empty\x1a .telepresence.common.VersionInfo\x12L\n" +
	"\rAgentImageFQN\x12\x16.google.protobuf.Empty\x1a#.telepresence.manager.AgentImageFQN\x12^\n" +
	"\fGetIntercept\x12).telepresence.manager.GetInterceptRequest\x1a#.telepresence.manager.InterceptInfo\x12V\n" +
	"\aConnect\x12&.telepresence.connector.ConnectRequest\x1a#.telepresence.connector.ConnectInfo\x12<\n" +
	"\n" +
	"Disconnect\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x11GetClusterSubnets\x12\x16.google.protobuf.Empty\x1a&.telepresence.connector.ClusterSubnets\x12E\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a#.telepresence.connector.ConnectInfo\x12g\n" +
	"\fCanIntercept\x12..telepresence.connector.CreateInterceptRequest\x1a'.telepresence.connector.InterceptResult\x12S\n" +
	"\x06Ingest\x12%.telepresence.connector.IngestRequest\x1a\".telepresence.connector.IngestInfo\x12Y\n" +
	"\tGetIngest\x12(.telepresence.connector.IngestIdentifier\x1a\".telepresence.connector.IngestInfo\x12[\n" +
	"\vLeaveIngest\x12(.telepresence.connector.IngestIdentifier\x1a\".telepresence.connector.IngestInfo\x12j\n" +
	"\x0fCreateIntercept\x12..telepresence.connector.CreateInterceptRequest\x1a'.telepresence.connector.InterceptResult\x12i\n" +
	"\x0fRemoveIntercept\x12-.telepresence.manager.RemoveInterceptRequest2\x1a'.telepresence.connector.InterceptResult\x12d\n" +
	"\x0fUpdateIntercept\x12,.telepresence.manager.UpdateInterceptRequest\x1a#.telepresence.manager.InterceptInfo\x12R\n" +
	"\tUninstall\x12(.telepresence.connector.UninstallRequest\x1a\x1b.telepresence.common.Result\x12Y\n" +
	"\x04List\x12#.telepresence.connector.ListRequest\x1a,.telepresence.connector.WorkloadInfoSnapshot\x12o\n" +
	"\x0eWatchWorkloads\x12-.telepresence.connector.WatchWorkloadsRequest\x1a,.telepresence.connector.WorkloadInfoSnapshot0\x01\x12N\n" +
	"\vSetLogLevel\x12'.telepresence.connector.LogLevelRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\x04Quit\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12W\n" +
	"\n" +
	"GatherLogs\x12#.telepresence.connector.LogsRequest\x1a$.telepresence.connector.LogsResponse\x12M\n" +
	"\x0eAddInterceptor\x12#.telepresence.connector.Interceptor\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x11RemoveInterceptor\x12#.telepresence.connector.Interceptor\x1a\x16.google.protobuf.Empty\x12l\n" +
	"\rGetNamespaces\x12,.telepresence.connector.GetNamespacesRequest\x1a-.telepresence.connector.GetNamespacesResponse\x12Y\n" +
	"\x15GetKnownWorkloadKinds\x12\x16.google.protobuf.Empty\x1a(.telepresence.manager.KnownWorkloadKinds\x12N\n" +
	"\x17RemoteMountAvailability\x12\x16.google.protobuf.Empty\x1a\x1b.telepresence.common.Result\x12I\n" +
	"\tGetConfig\x12\x16.google.protobuf.Empty\x1a$.telepresence.connector.ClientConfig\x12T\n" +
	"\x0eSetDNSExcludes\x12*.telepresence.daemon.SetDNSExcludesRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0eSetDNSMappings\x12*.telepresence.daemon.SetDNSMappingsRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\x0eGetAgentConfig\x12(.telepresence.manager.AgentConfigRequest\x1a).telepresence.manager.AgentConfigResponse\x12w\n" +
	"\x12ResolveSyntheticIP\x12/.telepresence.connector.ResolveSyntheticRequest\x1a0.telepresence.connector.ResolveSyntheticResponse\x12W\n" +
	"\bLookupIP\x12$.telepresence.daemon.LookupIPRequest\x1a%.telepresence.daemon.LookupIPResponse2\x89\x04\n" +
	"\fManagerProxy\x12E\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a\".telepresence.manager.VersionInfo2\x12J\n" +
	"\x0fGetClientConfig\x12\x16.google.protobuf.Empty\x1a\x1f.telepresence.manager.CLIConfig\x12`\n" +
	"\vEnsureAgent\x12(.telepresence.manager.EnsureAgentRequest\x1a'.telepresence.manager.AgentInfoSnapshot\x12Z\n" +
	"\x10WatchClusterInfo\x12!.telepresence.manager.SessionInfo\x1a!.telepresence.manager.ClusterInfo0\x01\x12P\n" +
	"\tLookupDNS\x12 .telepresence.manager.DNSRequest\x1a!.telepresence.manager.DNSResponse\x12V\n" +
	"\x06Tunnel\x12#.telepresence.manager.TunnelMessage\x1a#.telepresence.manager.TunnelMessage(\x010\x01B9Z7github.com/telepresenceio/telepresence/rpc/v2/connectorb\x06proto3"

var (
	file_connector_connector_proto_rawDescOnce sync.Once
	file_connector_connector_proto_rawDescData []byte
)

func file_connector_connector_proto_rawDescGZIP() []byte {
	file_connector_connector_proto_rawDescOnce.Do(func() {
		file_connector_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connector_connector_proto_rawDesc), len(file_connector_connector_proto_rawDesc)))
	})
	return file_connector_connector_proto_rawDescData
}

var file_connector_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_connector_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_connector_connector_proto_goTypes = []any{
	(ConnectInfo_ErrType)(0),                // 0: telepresence.connector.ConnectInfo.ErrType
	(UninstallRequest_UninstallType)(0),     // 1: telepresence.connector.UninstallRequest.UninstallType
	(ListRequest_Filter)(0),                 // 2: telepresence.connector.ListRequest.Filter
	(LogLevelRequest_Scope)(0),              // 3: telepresence.connector.LogLevelRequest.Scope
	(*Interceptor)(nil),                     // 4: telepresence.connector.Interceptor
	(*ConnectRequest)(nil),                  // 5: telepresence.connector.ConnectRequest
	(*ConnectInfo)(nil),                     // 6: telepresence.connector.ConnectInfo
	(*UninstallRequest)(nil),                // 7: telepresence.connector.UninstallRequest
	(*CreateInterceptRequest)(nil),          // 8: telepresence.connector.CreateInterceptRequest
	(*ListRequest)(nil),                     // 9: telepresence.connector.ListRequest
	(*IngestIdentifier)(nil),                // 10: telepresence.connector.IngestIdentifier
	(*IngestRequest)(nil),                   // 11: telepresence.connector.IngestRequest
	(*IngestInfo)(nil),                      // 12: telepresence.connector.IngestInfo
	(*WatchWorkloadsRequest)(nil),           // 13: telepresence.connector.WatchWorkloadsRequest
	(*WorkloadInfo)(nil),                    // 14: telepresence.connector.WorkloadInfo
	(*WorkloadInfoSnapshot)(nil),            // 15: telepresence.connector.WorkloadInfoSnapshot
	(*InterceptResult)(nil),                 // 16: telepresence.connector.InterceptResult
	(*LogLevelRequest)(nil),                 // 17: telepresence.connector.LogLevelRequest
	(*LogsRequest)(nil),                     // 18: telepresence.connector.LogsRequest
	(*LogsResponse)(nil),                    // 19: telepresence.connector.LogsResponse
	(*GetNamespacesRequest)(nil),            // 20: telepresence.connector.GetNamespacesRequest
	(*GetNamespacesResponse)(nil),           // 21: telepresence.connector.GetNamespacesResponse
	(*ClientConfig)(nil),                    // 22: telepresence.connector.ClientConfig
	(*ClusterSubnets)(nil),                  // 23: telepresence.connector.ClusterSubnets
	(*ResolveSyntheticRequest)(nil),         // 24: telepresence.connector.ResolveSyntheticRequest
	(*ResolveSyntheticResponse)(nil),        // 25: telepresence.connector.ResolveSyntheticResponse
	nil,                                     // 26: telepresence.connector.ConnectRequest.KubeFlagsEntry
	nil,                                     // 27: telepresence.connector.ConnectRequest.ContainerKubeFlagOverridesEntry
	nil,                                     // 28: telepresence.connector.ConnectRequest.EnvironmentEntry
	nil,                                     // 29: telepresence.connector.ConnectInfo.KubeFlagsEntry
	nil,                                     // 30: telepresence.connector.IngestInfo.EnvironmentEntry
	nil,                                     // 31: telepresence.connector.IngestInfo.MountsEntry
	nil,                                     // 32: telepresence.connector.LogsResponse.PodInfoEntry
	(*daemon.SubnetViaWorkload)(nil),        // 33: telepresence.daemon.SubnetViaWorkload
	(*common.VersionInfo)(nil),              // 34: telepresence.common.VersionInfo
	(*manager.InterceptInfoSnapshot)(nil),   // 35: telepresence.manager.InterceptInfoSnapshot
	(*manager.SessionInfo)(nil),             // 36: telepresence.manager.SessionInfo
	(*manager.VersionInfo2)(nil),            // 37: telepresence.manager.VersionInfo2
	(*daemon.DaemonStatus)(nil),             // 38: telepresence.daemon.DaemonStatus
	(*manager.InterceptSpec)(nil),           // 39: telepresence.manager.InterceptSpec
	(*manager.InterceptInfo)(nil),           // 40: telepresence.manager.InterceptInfo
	(common.InterceptError)(0),              // 41: telepresence.common.InterceptError
	(*durationpb.Duration)(nil),             // 42: google.protobuf.Duration
	(*manager.IPNet)(nil),                   // 43: telepresence.manager.IPNet
	(*emptypb.Empty)(nil),                   // 44: google.protobuf.Empty
	(*manager.GetInterceptRequest)(nil),     // 45: telepresence.manager.GetInterceptRequest
	(*manager.RemoveInterceptRequest2)(nil), // 46: telepresence.manager.RemoveInterceptRequest2
	(*manager.UpdateInterceptRequest)(nil),  // 47: telepresence.manager.UpdateInterceptRequest
	(*daemon.SetDNSExcludesRequest)(nil),    // 48: telepresence.daemon.SetDNSExcludesRequest
	(*daemon.SetDNSMappingsRequest)(nil),    // 49: telepresence.daemon.SetDNSMappingsRequest
	(*manager.AgentConfigRequest)(nil),      // 50: telepresence.manager.AgentConfigRequest
	(*daemon.LookupIPRequest)(nil),          // 51: telepresence.daemon.LookupIPRequest
	(*manager.EnsureAgentRequest)(nil),      // 52: telepresence.manager.EnsureAgentRequest
	(*manager.DNSRequest)(nil),              // 53: telepresence.manager.DNSRequest
	(*manager.TunnelMessage)(nil),           // 54: telepresence.manager.TunnelMessage
	(*manager.AgentImageFQN)(nil),           // 55: telepresence.manager.AgentImageFQN
	(*common.Result)(nil),                   // 56: telepresence.common.Result
	(*manager.KnownWorkloadKinds)(nil),      // 57: telepresence.manager.KnownWorkloadKinds
	(*manager.AgentConfigResponse)(nil),     // 58: telepresence.manager.AgentConfigResponse
	(*daemon.LookupIPResponse)(nil),         // 59: telepresence.daemon.LookupIPResponse
	(*manager.CLIConfig)(nil),               // 60: telepresence.manager.CLIConfig
	(*manager.AgentInfoSnapshot)(nil),       // 61: telepresence.manager.AgentInfoSnapshot
	(*manager.ClusterInfo)(nil),             // 62: telepresence.manager.ClusterInfo
	(*manager.DNSResponse)(nil),             // 63: telepresence.manager.DNSResponse
}
var file_connector_connector_proto_depIdxs = []int32{
	26, // 0: telepresence.connector.ConnectRequest.kube_flags:type_name -> telepresence.connector.ConnectRequest.KubeFlagsEntry
	27, // 1: telepresence.connector.ConnectRequest.container_kube_flag_overrides:type_name -> telepresence.connector.ConnectRequest.ContainerKubeFlagOverridesEntry
	33, // 2: telepresence.connector.ConnectRequest.subnet_via_workloads:type_name -> telepresence.daemon.SubnetViaWorkload
	28, // 3: telepresence.connector.ConnectRequest.environment:type_name -> telepresence.connector.ConnectRequest.EnvironmentEntry
	0,  // 4: telepresence.connector.ConnectInfo.error:type_name -> telepresence.connector.ConnectInfo.ErrType
	34, // 5: telepresence.connector.ConnectInfo.version:type_name -> telepresence.common.VersionInfo
	29, // 6: telepresence.connector.ConnectInfo.kube_flags:type_name -> telepresence.connector.ConnectInfo.KubeFlagsEntry
	35, // 7: telepresence.connector.ConnectInfo.intercepts:type_name -> telepresence.manager.InterceptInfoSnapshot
	12, // 8: telepresence.connector.ConnectInfo.ingests:type_name -> telepresence.connector.IngestInfo
	36, // 9: telepresence.connector.ConnectInfo.session_info:type_name -> telepresence.manager.SessionInfo
	37, // 10: telepresence.connector.ConnectInfo.manager_version:type_name -> telepresence.manager.VersionInfo2
	38, // 11: telepresence.connector.ConnectInfo.daemon_status:type_name -> telepresence.daemon.DaemonStatus
	33, // 12: telepresence.connector.ConnectInfo.subnet_via_workloads:type_name -> telepresence.daemon.SubnetViaWorkload
	1,  // 13: telepresence.connector.UninstallRequest.uninstall_type:type_name -> telepresence.connector.UninstallRequest.UninstallType
	39, // 14: telepresence.connector.CreateInterceptRequest.spec:type_name -> telepresence.manager.InterceptSpec
	2,  // 15: telepresence.connector.ListRequest.filter:type_name -> telepresence.connector.ListRequest.Filter
	10, // 16: telepresence.connector.IngestRequest.identifier:type_name -> telepresence.connector.IngestIdentifier
	30, // 17: telepresence.connector.IngestInfo.environment:type_name -> telepresence.connector.IngestInfo.EnvironmentEntry
	31, // 18: telepresence.connector.IngestInfo.mounts:type_name -> telepresence.connector.IngestInfo.MountsEntry
	40, // 19: telepresence.connector.WorkloadInfo.intercept_info:type_name -> telepresence.manager.InterceptInfo
	12, // 20: telepresence.connector.WorkloadInfo.ingest_info:type_name -> telepresence.connector.IngestInfo
	14, // 21: telepresence.connector.WorkloadInfoSnapshot.workloads:type_name -> telepresence.connector.WorkloadInfo
	40, // 22: telepresence.connector.InterceptResult.intercept_info:type_name -> telepresence.manager.InterceptInfo
	41, // 23: telepresence.connector.InterceptResult.error:type_name -> telepresence.common.InterceptError
	42, // 24: telepresence.connector.LogLevelRequest.duration:type_name -> google.protobuf.Duration
	3,  // 25: telepresence.connector.LogLevelRequest.scope:type_name -> telepresence.connector.LogLevelRequest.Scope
	32, // 26: telepresence.connector.LogsResponse.pod_info:type_name -> telepresence.connector.LogsResponse.PodInfoEntry
	43, // 27: telepresence.connector.ClusterSubnets.pod_subnets:type_name -> telepresence.manager.IPNet
	43, // 28: telepresence.connector.ClusterSubnets.svc_subnets:type_name -> telepresence.manager.IPNet
	44, // 29: telepresence.connector.Connector.Version:input_type -> google.protobuf.Empty
	44, // 30: telepresence.connector.Connector.RootDaemonVersion:input_type -> google.protobuf.Empty
	44, // 31: telepresence.connector.Connector.TrafficManagerVersion:input_type -> google.protobuf.Empty
	44, // 32: telepresence.connector.Connector.AgentImageFQN:input_type -> google.protobuf.Empty
	45, // 33: telepresence.connector.Connector.GetIntercept:input_type -> telepresence.manager.GetInterceptRequest
	5,  // 34: telepresence.connector.Connector.Connect:input_type -> telepresence.connector.ConnectRequest
	44, // 35: telepresence.connector.Connector.Disconnect:input_type -> google.protobuf.Empty
	44, // 36: telepresence.connector.Connector.GetClusterSubnets:input_type -> google.protobuf.Empty
	44, // 37: telepresence.connector.Connector.Status:input_type -> google.protobuf.Empty
	8,  // 38: telepresence.connector.Connector.CanIntercept:input_type -> telepresence.connector.CreateInterceptRequest
	11, // 39: telepresence.connector.Connector.Ingest:input_type -> telepresence.connector.IngestRequest
	10, // 40: telepresence.connector.Connector.GetIngest:input_type -> telepresence.connector.IngestIdentifier
	10, // 41: telepresence.connector.Connector.LeaveIngest:input_type -> telepresence.connector.IngestIdentifier
	8,  // 42: telepresence.connector.Connector.CreateIntercept:input_type -> telepresence.connector.CreateInterceptRequest
	46, // 43: telepresence.connector.Connector.RemoveIntercept:input_type -> telepresence.manager.RemoveInterceptRequest2
	47, // 44: telepresence.connector.Connector.UpdateIntercept:input_type -> telepresence.manager.UpdateInterceptRequest
	7,  // 45: telepresence.connector.Connector.Uninstall:input_type -> telepresence.connector.UninstallRequest
	9,  // 46: telepresence.connector.Connector.List:input_type -> telepresence.connector.ListRequest
	13, // 47: telepresence.connector.Connector.WatchWorkloads:input_type -> telepresence.connector.WatchWorkloadsRequest
	17, // 48: telepresence.connector.Connector.SetLogLevel:input_type -> telepresence.connector.LogLevelRequest
	44, // 49: telepresence.connector.Connector.Quit:input_type -> google.protobuf.Empty
	18, // 50: telepresence.connector.Connector.GatherLogs:input_type -> telepresence.connector.LogsRequest
	4,  // 51: telepresence.connector.Connector.AddInterceptor:input_type -> telepresence.connector.Interceptor
	4,  // 52: telepresence.connector.Connector.RemoveInterceptor:input_type -> telepresence.connector.Interceptor
	20, // 53: telepresence.connector.Connector.GetNamespaces:input_type -> telepresence.connector.GetNamespacesRequest
	44, // 54: telepresence.connector.Connector.GetKnownWorkloadKinds:input_type -> google.protobuf.Empty
	44, // 55: telepresence.connector.Connector.RemoteMountAvailability:input_type -> google.protobuf.Empty
	44, // 56: telepresence.connector.Connector.GetConfig:input_type -> google.protobuf.Empty
	48, // 57: telepresence.connector.Connector.SetDNSExcludes:input_type -> telepresence.daemon.SetDNSExcludesRequest
	49, // 58: telepresence.connector.Connector.SetDNSMappings:input_type -> telepresence.daemon.SetDNSMappingsRequest
	50, // 59: telepresence.connector.Connector.GetAgentConfig:input_type -> telepresence.manager.AgentConfigRequest
	24, // 60: telepresence.connector.Connector.ResolveSyntheticIP:input_type -> telepresence.connector.ResolveSyntheticRequest
	51, // 61: telepresence.connector.Connector.LookupIP:input_type -> telepresence.daemon.LookupIPRequest
	44, // 62: telepresence.connector.ManagerProxy.Version:input_type -> google.protobuf.Empty
	44, // 63: telepresence.connector.ManagerProxy.GetClientConfig:input_type -> google.protobuf.Empty
	52, // 64: telepresence.connector.ManagerProxy.EnsureAgent:input_type -> telepresence.manager.EnsureAgentRequest
	36, // 65: telepresence.connector.ManagerProxy.WatchClusterInfo:input_type -> telepresence.manager.SessionInfo
	53, // 66: telepresence.connector.ManagerProxy.LookupDNS:input_type -> telepresence.manager.DNSRequest
	54, // 67: telepresence.connector.ManagerProxy.Tunnel:input_type -> telepresence.manager.TunnelMessage
	34, // 68: telepresence.connector.Connector.Version:output_type -> telepresence.common.VersionInfo
	34, // 69: telepresence.connector.Connector.RootDaemonVersion:output_type -> telepresence.common.VersionInfo
	34, // 70: telepresence.connector.Connector.TrafficManagerVersion:output_type -> telepresence.common.VersionInfo
	55, // 71: telepresence.connector.Connector.AgentImageFQN:output_type -> telepresence.manager.AgentImageFQN
	40, // 72: telepresence.connector.Connector.GetIntercept:output_type -> telepresence.manager.InterceptInfo
	6,  // 73: telepresence.connector.Connector.Connect:output_type -> telepresence.connector.ConnectInfo
	44, // 74: telepresence.connector.Connector.Disconnect:output_type -> google.protobuf.Empty
	23, // 75: telepresence.connector.Connector.GetClusterSubnets:output_type -> telepresence.connector.ClusterSubnets
	6,  // 76: telepresence.connector.Connector.Status:output_type -> telepresence.connector.ConnectInfo
	16, // 77: telepresence.connector.Connector.CanIntercept:output_type -> telepresence.connector.InterceptResult
	12, // 78: telepresence.connector.Connector.Ingest:output_type -> telepresence.connector.IngestInfo
	12, // 79: telepresence.connector.Connector.GetIngest:output_type -> telepresence.connector.IngestInfo
	12, // 80: telepresence.connector.Connector.LeaveIngest:output_type -> telepresence.connector.IngestInfo
	16, // 81: telepresence.connector.Connector.CreateIntercept:output_type -> telepresence.connector.InterceptResult
	16, // 82: telepresence.connector.Connector.RemoveIntercept:output_type -> telepresence.connector.InterceptResult
	40, // 83: telepresence.connector.Connector.UpdateIntercept:output_type -> telepresence.manager.InterceptInfo
	56, // 84: telepresence.connector.Connector.Uninstall:output_type -> telepresence.common.Result
	15, // 85: telepresence.connector.Connector.List:output_type -> telepresence.connector.WorkloadInfoSnapshot
	15, // 86: telepresence.connector.Connector.WatchWorkloads:output_type -> telepresence.connector.WorkloadInfoSnapshot
	44, // 87: telepresence.connector.Connector.SetLogLevel:output_type -> google.protobuf.Empty
	44, // 88: telepresence.connector.Connector.Quit:output_type -> google.protobuf.Empty
	19, // 89: telepresence.connector.Connector.GatherLogs:output_type -> telepresence.connector.LogsResponse
	44, // 90: telepresence.connector.Connector.AddInterceptor:output_type -> google.protobuf.Empty
	44, // 91: telepresence.connector.Connector.RemoveInterceptor:output_type -> google.protobuf.Empty
	21, // 92: telepresence.connector.Connector.GetNamespaces:output_type -> telepresence.connector.GetNamespacesResponse
	57, // 93: telepresence.connector.Connector.GetKnownWorkloadKinds:output_type -> telepresence.manager.KnownWorkloadKinds
	56, // 94: telepresence.connector.Connector.RemoteMountAvailability:output_type -> telepresence.common.Result
	22, // 95: telepresence.connector.Connector.GetConfig:output_type -> telepresence.connector.ClientConfig
	44, // 96: telepresence.connector.Connector.SetDNSExcludes:output_type -> google.protobuf.Empty
	44, // 97: telepresence.connector.Connector.SetDNSMappings:output_type -> google.protobuf.Empty
	58, // 98: telepresence.connector.Connector.GetAgentConfig:output_type -> telepresence.manager.AgentConfigResponse
	25, // 99: telepresence.connector.Connector.ResolveSyntheticIP:output_type -> telepresence.connector.ResolveSyntheticResponse
	59, // 100: telepresence.connector.Connector.LookupIP:output_type -> telepresence.daemon.LookupIPResponse
	37, // 101: telepresence.connector.ManagerProxy.Version:output_type -> telepresence.manager.VersionInfo2
	60, // 102: telepresence.connector.ManagerProxy.GetClientConfig:output_type -> telepresence.manager.CLIConfig
	61, // 103: telepresence.connector.ManagerProxy.EnsureAgent:output_type -> telepresence.manager.AgentInfoSnapshot
	62, // 104: telepresence.connector.ManagerProxy.WatchClusterInfo:output_type -> telepresence.manager.ClusterInfo
	63, // 105: telepresence.connector.ManagerProxy.LookupDNS:output_type -> telepresence.manager.DNSResponse
	54, // 106: telepresence.connector.ManagerProxy.Tunnel:output_type -> telepresence.manager.TunnelMessage
	68, // [68:107] is the sub-list for method output_type
	29, // [29:68] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_connector_connector_proto_init() }
func file_connector_connector_proto_init() {
	if File_connector_connector_proto != nil {
		return
	}
	file_connector_connector_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connector_connector_proto_rawDesc), len(file_connector_connector_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_connector_connector_proto_goTypes,
		DependencyIndexes: file_connector_connector_proto_depIdxs,
		EnumInfos:         file_connector_connector_proto_enumTypes,
		MessageInfos:      file_connector_connector_proto_msgTypes,
	}.Build()
	File_connector_connector_proto = out.File
	file_connector_connector_proto_goTypes = nil
	file_connector_connector_proto_depIdxs = nil
}
