{{- if not .NoService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .SvcName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Name }}
spec:
{{- if .Headless }}
  clusterIP: None
{{- end }}
  selector:
    app: {{ .Name }}
  ports:
    - name: http
      port: {{ .Port }}
      targetPort: http
{{- if .AppProtocol }}
      appProtocol: {{ .AppProtocol }}
{{- end }}
{{- range .ExtraPorts }}
    - name: {{ .Name }}
      port: {{ .Port }}
      targetPort: {{ .Name }}
{{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Name }}
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: {{ .Name }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
{{- if .Annotations }}
      annotations:
{{- range $k, $v := .Annotations }}
        {{ $k }}: "{{ $v }}"
{{- end }}
{{- end }}
    spec:
      containers:
        - name: {{ .Name }}
          image: {{ .Image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Port }}
{{- range .ExtraPorts }}
            - name: {{ .Name }}
              containerPort: {{ .Port }}
{{- end }}
{{- if .ExtraPorts }}
          env:
            - name: PORTS
              value: "{{ .PortsEnv }}"
{{- end }}
{{- if not .Resources.IsZero }}
          resources:
{{- if or .Resources.Requests.CPU .Resources.Requests.Memory }}
            requests:
{{- if .Resources.Requests.CPU }}
              cpu: {{ .Resources.Requests.CPU }}
{{- end }}
{{- if .Resources.Requests.Memory }}
              memory: {{ .Resources.Requests.Memory }}
{{- end }}
{{- end }}
{{- if or .Resources.Limits.CPU .Resources.Limits.Memory }}
            limits:
{{- if .Resources.Limits.CPU }}
              cpu: {{ .Resources.Limits.CPU }}
{{- end }}
{{- if .Resources.Limits.Memory }}
              memory: {{ .Resources.Limits.Memory }}
{{- end }}
{{- end }}
{{- end }}
