# syntax = docker/dockerfile:1.3

# Copyright 2024 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$BUILDPLATFORM golang:alpine AS routecontroller-build

ENV GOEXPERIMENT=jsonv2

WORKDIR telepresence
COPY go.mod go.sum .
COPY cmd/routecontroller/ cmd/routecontroller/
COPY pkg/ pkg/
COPY build-output/version.txt .

ARG TARGETOS
ARG TARGETARCH

RUN \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /usr/local/bin/route-controller -trimpath -ldflags="-s -w" ./cmd/routecontroller/

FROM alpine AS routecontroller

RUN apk add --no-cache ca-certificates iptables ip6tables

COPY --from=routecontroller-build /usr/local/bin/route-controller /usr/local/bin/route-controller

ENTRYPOINT ["/usr/local/bin/route-controller"]
CMD []
