# syntax = docker/dockerfile:1.3

# Copyright 2026 Datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$BUILDPLATFORM golang:alpine AS kafka-build

ENV GOEXPERIMENT=jsonv2

WORKDIR telepresence
COPY go.mod go.sum ./
COPY cmd/telepresence-kafka/ cmd/telepresence-kafka/
COPY pkg/ pkg/

ARG TARGETOS
ARG TARGETARCH

RUN \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -o /usr/local/bin/telepresence-kafka -trimpath -ldflags="-s -w" ./cmd/telepresence-kafka/

FROM alpine AS kafka

RUN apk add --no-cache ca-certificates

COPY --from=kafka-build /usr/local/bin/telepresence-kafka /usr/local/bin/telepresence-kafka

USER 1000:1000
ENTRYPOINT ["/usr/local/bin/telepresence-kafka"]
