{{- if and .Values.managerRbac.create .Values.nodeAgent.enabled }}
{{- /*
Node-agent Jobs are always created in the traffic-manager's own namespace,
so the permissions to manage them are namespace-scoped regardless of whether
the traffic-manager itself is installed cluster-wide or namespaced.
*/}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traffic-manager-node-agent
  namespace: {{ include "traffic-manager.namespace" $ }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traffic-manager-node-agent
  namespace: {{ include "traffic-manager.namespace" $ }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traffic-manager-node-agent
subjects:
- kind: ServiceAccount
  name: traffic-manager
  namespace: {{ include "traffic-manager.namespace" $ }}
{{- end }}
