// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: daemon/daemon.proto

package daemon

import (
	common "github.com/telepresenceio/telepresence/rpc/v2/common"
	manager "github.com/telepresenceio/telepresence/rpc/v2/manager"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaemonStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OutboundConfig *NetworkConfig         `protobuf:"bytes,4,opt,name=outbound_config,json=outboundConfig,proto3" json:"outbound_config,omitempty"`
	Version        *common.VersionInfo    `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DaemonStatus) Reset() {
	*x = DaemonStatus{}
	mi := &file_daemon_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatus) ProtoMessage() {}

func (x *DaemonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatus.ProtoReflect.Descriptor instead.
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonStatus) GetOutboundConfig() *NetworkConfig {
	if x != nil {
		return x.OutboundConfig
	}
	return nil
}

func (x *DaemonStatus) GetVersion() *common.VersionInfo {
	if x != nil {
		return x.Version
	}
	return nil
}

type Domains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domains) Reset() {
	*x = Domains{}
	mi := &file_daemon_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domains) ProtoMessage() {}

func (x *Domains) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domains.ProtoReflect.Descriptor instead.
func (*Domains) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *Domains) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type DNSMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AliasFor      string                 `protobuf:"bytes,2,opt,name=alias_for,json=aliasFor,proto3" json:"alias_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSMapping) Reset() {
	*x = DNSMapping{}
	mi := &file_daemon_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSMapping) ProtoMessage() {}

func (x *DNSMapping) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSMapping.ProtoReflect.Descriptor instead.
func (*DNSMapping) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *DNSMapping) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSMapping) GetAliasFor() string {
	if x != nil {
		return x.AliasFor
	}
	return ""
}

// DNS configuration for the local DNS resolver
type DNSConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// local_ip is the address of the local DNS server. Only used by Linux systems that have no
	// systemd-resolved configured. Defaults to the first line of /etc/resolv.conf
	LocalIp []byte `protobuf:"bytes,1,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	// remote_ip is the address of the kube-dns.kube-system, dns-default.openshift-dns, or similar service,
	RemoteIp []byte `protobuf:"bytes,2,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	// Suffixes to exclude
	ExcludeSuffixes []string `protobuf:"bytes,3,rep,name=exclude_suffixes,json=excludeSuffixes,proto3" json:"exclude_suffixes,omitempty"`
	// Suffixes to include. Has higher prio than the excludes
	IncludeSuffixes []string `protobuf:"bytes,4,rep,name=include_suffixes,json=includeSuffixes,proto3" json:"include_suffixes,omitempty"`
	// Exclude are a list of hostname that the DNS resolver will not resolve even if they exist.
	Excludes []string `protobuf:"bytes,8,rep,name=excludes,proto3" json:"excludes,omitempty"`
	// DNSMapping contains a hostname and its associated alias. When requesting the name, the intended behavior is
	// to resolve the alias instead.
	Mappings []*DNSMapping `protobuf:"bytes,9,rep,name=mappings,proto3" json:"mappings,omitempty"`
	// The maximum time wait for a cluster side host lookup.
	LookupTimeout *durationpb.Duration `protobuf:"bytes,6,opt,name=lookup_timeout,json=lookupTimeout,proto3" json:"lookup_timeout,omitempty"`
	// Perform a recursion check on first connect.
	RecursionCheck bool `protobuf:"varint,5,opt,name=recursion_check,json=recursionCheck,proto3" json:"recursion_check,omitempty"`
	// If set, this error indicates why DNS is not working.
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSConfig) Reset() {
	*x = DNSConfig{}
	mi := &file_daemon_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSConfig) ProtoMessage() {}

func (x *DNSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSConfig.ProtoReflect.Descriptor instead.
func (*DNSConfig) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *DNSConfig) GetLocalIp() []byte {
	if x != nil {
		return x.LocalIp
	}
	return nil
}

func (x *DNSConfig) GetRemoteIp() []byte {
	if x != nil {
		return x.RemoteIp
	}
	return nil
}

func (x *DNSConfig) GetExcludeSuffixes() []string {
	if x != nil {
		return x.ExcludeSuffixes
	}
	return nil
}

func (x *DNSConfig) GetIncludeSuffixes() []string {
	if x != nil {
		return x.IncludeSuffixes
	}
	return nil
}

func (x *DNSConfig) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *DNSConfig) GetMappings() []*DNSMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *DNSConfig) GetLookupTimeout() *durationpb.Duration {
	if x != nil {
		return x.LookupTimeout
	}
	return nil
}

func (x *DNSConfig) GetRecursionCheck() bool {
	if x != nil {
		return x.RecursionCheck
	}
	return false
}

func (x *DNSConfig) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubnetViaWorkload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The remote IP that the DNS resolver translates into a Virtual IP to use locally.
	Subnet string `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	// The workload that the virtual IP will be routed to.
	Workload      string `protobuf:"bytes,2,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetViaWorkload) Reset() {
	*x = SubnetViaWorkload{}
	mi := &file_daemon_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetViaWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetViaWorkload) ProtoMessage() {}

func (x *SubnetViaWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetViaWorkload.ProtoReflect.Descriptor instead.
func (*SubnetViaWorkload) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *SubnetViaWorkload) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *SubnetViaWorkload) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

// NetworkConfig contains all information that the root daemon needs in order to
// establish outbound traffic to the cluster.
type NetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session makes it possible for the root daemon to identify itself as the
	// same client as the user daemon.
	Session *manager.SessionInfo `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Route subnets via given workload using virtual IPs
	SubnetViaWorkloads []*SubnetViaWorkload `protobuf:"bytes,2,rep,name=subnet_via_workloads,json=subnetViaWorkloads,proto3" json:"subnet_via_workloads,omitempty"`
	// Users home directory
	HomeDir string `protobuf:"bytes,3,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	// Connection namespace
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Kubernetes flags
	KubeFlags map[string]string `protobuf:"bytes,5,rep,name=kube_flags,json=kubeFlags,proto3" json:"kube_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Kubeconfig YAML, if not to be loaded from file.
	KubeconfigData []byte `protobuf:"bytes,6,opt,name=kubeconfig_data,json=kubeconfigData,proto3,oneof" json:"kubeconfig_data,omitempty"`
	// The completely merged client Config, unless daemon runs embedded
	ClientConfig  []byte `protobuf:"bytes,7,opt,name=client_config,json=clientConfig,proto3,oneof" json:"client_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_daemon_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkConfig) GetSession() *manager.SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *NetworkConfig) GetSubnetViaWorkloads() []*SubnetViaWorkload {
	if x != nil {
		return x.SubnetViaWorkloads
	}
	return nil
}

func (x *NetworkConfig) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

func (x *NetworkConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NetworkConfig) GetKubeFlags() map[string]string {
	if x != nil {
		return x.KubeFlags
	}
	return nil
}

func (x *NetworkConfig) GetKubeconfigData() []byte {
	if x != nil {
		return x.KubeconfigData
	}
	return nil
}

func (x *NetworkConfig) GetClientConfig() []byte {
	if x != nil {
		return x.ClientConfig
	}
	return nil
}

type SetDNSExcludesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Excludes      []string               `protobuf:"bytes,1,rep,name=excludes,proto3" json:"excludes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDNSExcludesRequest) Reset() {
	*x = SetDNSExcludesRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDNSExcludesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDNSExcludesRequest) ProtoMessage() {}

func (x *SetDNSExcludesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDNSExcludesRequest.ProtoReflect.Descriptor instead.
func (*SetDNSExcludesRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *SetDNSExcludesRequest) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

type SetDNSMappingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mappings      []*DNSMapping          `protobuf:"bytes,1,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDNSMappingsRequest) Reset() {
	*x = SetDNSMappingsRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDNSMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDNSMappingsRequest) ProtoMessage() {}

func (x *SetDNSMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDNSMappingsRequest.ProtoReflect.Descriptor instead.
func (*SetDNSMappingsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *SetDNSMappingsRequest) GetMappings() []*DNSMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type WaitForAgentIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForAgentIPRequest) Reset() {
	*x = WaitForAgentIPRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForAgentIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForAgentIPRequest) ProtoMessage() {}

func (x *WaitForAgentIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForAgentIPRequest.ProtoReflect.Descriptor instead.
func (*WaitForAgentIPRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *WaitForAgentIPRequest) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *WaitForAgentIPRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type WaitForAgentIPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The local IP of the agent (might be virtual)
	LocalIp       []byte `protobuf:"bytes,1,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForAgentIPResponse) Reset() {
	*x = WaitForAgentIPResponse{}
	mi := &file_daemon_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForAgentIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForAgentIPResponse) ProtoMessage() {}

func (x *WaitForAgentIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForAgentIPResponse.ProtoReflect.Descriptor instead.
func (*WaitForAgentIPResponse) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *WaitForAgentIPResponse) GetLocalIp() []byte {
	if x != nil {
		return x.LocalIp
	}
	return nil
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           map[string]string      `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_daemon_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *Environment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

var File_daemon_daemon_proto protoreflect.FileDescriptor

const file_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	"\x13daemon/daemon.proto\x12\x13telepresence.daemon\x1a\x14common/version.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15manager/manager.proto\"\xa3\x01\n" +
	"\fDaemonStatus\x12K\n" +
	"\x0foutbound_config\x18\x04 \x01(\v2\".telepresence.daemon.NetworkConfigR\x0eoutboundConfig\x12:\n" +
	"\aversion\x18\x05 \x01(\v2 .telepresence.common.VersionInfoR\aversionJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"#\n" +
	"\aDomains\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"=\n" +
	"\n" +
	"DNSMapping\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\talias_for\x18\x02 \x01(\tR\baliasFor\"\xf3\x02\n" +
	"\tDNSConfig\x12\x19\n" +
	"\blocal_ip\x18\x01 \x01(\fR\alocalIp\x12\x1b\n" +
	"\tremote_ip\x18\x02 \x01(\fR\bremoteIp\x12)\n" +
	"\x10exclude_suffixes\x18\x03 \x03(\tR\x0fexcludeSuffixes\x12)\n" +
	"\x10include_suffixes\x18\x04 \x03(\tR\x0fincludeSuffixes\x12\x1a\n" +
	"\bexcludes\x18\b \x03(\tR\bexcludes\x12;\n" +
	"\bmappings\x18\t \x03(\v2\x1f.telepresence.daemon.DNSMappingR\bmappings\x12@\n" +
	"\x0elookup_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\rlookupTimeout\x12'\n" +
	"\x0frecursion_check\x18\x05 \x01(\bR\x0erecursionCheck\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"G\n" +
	"\x11SubnetViaWorkload\x12\x16\n" +
	"\x06subnet\x18\x01 \x01(\tR\x06subnet\x12\x1a\n" +
	"\bworkload\x18\x02 \x01(\tR\bworkload\"\xed\x03\n" +
	"\rNetworkConfig\x12;\n" +
	"\asession\x18\x01 \x01(\v2!.telepresence.manager.SessionInfoR\asession\x12X\n" +
	"\x14subnet_via_workloads\x18\x02 \x03(\v2&.telepresence.daemon.SubnetViaWorkloadR\x12subnetViaWorkloads\x12\x19\n" +
	"\bhome_dir\x18\x03 \x01(\tR\ahomeDir\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12P\n" +
	"\n" +
	"kube_flags\x18\x05 \x03(\v21.telepresence.daemon.NetworkConfig.KubeFlagsEntryR\tkubeFlags\x12,\n" +
	"\x0fkubeconfig_data\x18\x06 \x01(\fH\x00R\x0ekubeconfigData\x88\x01\x01\x12(\n" +
	"\rclient_config\x18\a \x01(\fH\x01R\fclientConfig\x88\x01\x01\x1a<\n" +
	"\x0eKubeFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_kubeconfig_dataB\x10\n" +
	"\x0e_client_config\"3\n" +
	"\x15SetDNSExcludesRequest\x12\x1a\n" +
	"\bexcludes\x18\x01 \x03(\tR\bexcludes\"T\n" +
	"\x15SetDNSMappingsRequest\x12;\n" +
	"\bmappings\x18\x01 \x03(\v2\x1f.telepresence.daemon.DNSMappingR\bmappings\"\\\n" +
	"\x15WaitForAgentIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"3\n" +
	"\x16WaitForAgentIPResponse\x12\x19\n" +
	"\blocal_ip\x18\x01 \x01(\fR\alocalIp\"\x82\x01\n" +
	"\vEnvironment\x12;\n" +
	"\x03env\x18\x01 \x03(\v2).telepresence.daemon.Environment.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf7\a\n" +
	"\x06Daemon\x12C\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a .telepresence.common.VersionInfo\x12C\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a!.telepresence.daemon.DaemonStatus\x126\n" +
	"\x04Quit\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\aConnect\x12\".telepresence.daemon.NetworkConfig\x1a!.telepresence.daemon.DaemonStatus\x12<\n" +
	"\n" +
	"Disconnect\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x10GetNetworkConfig\x12\x16.google.protobuf.Empty\x1a\".telepresence.daemon.NetworkConfig\x12M\n" +
	"\x15SetDNSTopLevelDomains\x12\x1c.telepresence.daemon.Domains\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0eSetDNSExcludes\x12*.telepresence.daemon.SetDNSExcludesRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0eSetDNSMappings\x12*.telepresence.daemon.SetDNSMappingsRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vSetLogLevel\x12%.telepresence.manager.LogLevelRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x0fTranslateEnvIPs\x12 .telepresence.daemon.Environment\x1a .telepresence.daemon.Environment\x12@\n" +
	"\x0eWaitForNetwork\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12i\n" +
	"\x0eWaitForAgentIP\x12*.telepresence.daemon.WaitForAgentIPRequest\x1a+.telepresence.daemon.WaitForAgentIPResponseB6Z4github.com/telepresenceio/telepresence/rpc/v2/daemonb\x06proto3"

var (
	file_daemon_daemon_proto_rawDescOnce sync.Once
	file_daemon_daemon_proto_rawDescData []byte
)

func file_daemon_daemon_proto_rawDescGZIP() []byte {
	file_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_daemon_proto_rawDesc), len(file_daemon_daemon_proto_rawDesc)))
	})
	return file_daemon_daemon_proto_rawDescData
}

var file_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_daemon_daemon_proto_goTypes = []any{
	(*DaemonStatus)(nil),            // 0: telepresence.daemon.DaemonStatus
	(*Domains)(nil),                 // 1: telepresence.daemon.Domains
	(*DNSMapping)(nil),              // 2: telepresence.daemon.DNSMapping
	(*DNSConfig)(nil),               // 3: telepresence.daemon.DNSConfig
	(*SubnetViaWorkload)(nil),       // 4: telepresence.daemon.SubnetViaWorkload
	(*NetworkConfig)(nil),           // 5: telepresence.daemon.NetworkConfig
	(*SetDNSExcludesRequest)(nil),   // 6: telepresence.daemon.SetDNSExcludesRequest
	(*SetDNSMappingsRequest)(nil),   // 7: telepresence.daemon.SetDNSMappingsRequest
	(*WaitForAgentIPRequest)(nil),   // 8: telepresence.daemon.WaitForAgentIPRequest
	(*WaitForAgentIPResponse)(nil),  // 9: telepresence.daemon.WaitForAgentIPResponse
	(*Environment)(nil),             // 10: telepresence.daemon.Environment
	nil,                             // 11: telepresence.daemon.NetworkConfig.KubeFlagsEntry
	nil,                             // 12: telepresence.daemon.Environment.EnvEntry
	(*common.VersionInfo)(nil),      // 13: telepresence.common.VersionInfo
	(*durationpb.Duration)(nil),     // 14: google.protobuf.Duration
	(*manager.SessionInfo)(nil),     // 15: telepresence.manager.SessionInfo
	(*emptypb.Empty)(nil),           // 16: google.protobuf.Empty
	(*manager.LogLevelRequest)(nil), // 17: telepresence.manager.LogLevelRequest
}
var file_daemon_daemon_proto_depIdxs = []int32{
	5,  // 0: telepresence.daemon.DaemonStatus.outbound_config:type_name -> telepresence.daemon.NetworkConfig
	13, // 1: telepresence.daemon.DaemonStatus.version:type_name -> telepresence.common.VersionInfo
	2,  // 2: telepresence.daemon.DNSConfig.mappings:type_name -> telepresence.daemon.DNSMapping
	14, // 3: telepresence.daemon.DNSConfig.lookup_timeout:type_name -> google.protobuf.Duration
	15, // 4: telepresence.daemon.NetworkConfig.session:type_name -> telepresence.manager.SessionInfo
	4,  // 5: telepresence.daemon.NetworkConfig.subnet_via_workloads:type_name -> telepresence.daemon.SubnetViaWorkload
	11, // 6: telepresence.daemon.NetworkConfig.kube_flags:type_name -> telepresence.daemon.NetworkConfig.KubeFlagsEntry
	2,  // 7: telepresence.daemon.SetDNSMappingsRequest.mappings:type_name -> telepresence.daemon.DNSMapping
	14, // 8: telepresence.daemon.WaitForAgentIPRequest.timeout:type_name -> google.protobuf.Duration
	12, // 9: telepresence.daemon.Environment.env:type_name -> telepresence.daemon.Environment.EnvEntry
	16, // 10: telepresence.daemon.Daemon.Version:input_type -> google.protobuf.Empty
	16, // 11: telepresence.daemon.Daemon.Status:input_type -> google.protobuf.Empty
	16, // 12: telepresence.daemon.Daemon.Quit:input_type -> google.protobuf.Empty
	5,  // 13: telepresence.daemon.Daemon.Connect:input_type -> telepresence.daemon.NetworkConfig
	16, // 14: telepresence.daemon.Daemon.Disconnect:input_type -> google.protobuf.Empty
	16, // 15: telepresence.daemon.Daemon.GetNetworkConfig:input_type -> google.protobuf.Empty
	1,  // 16: telepresence.daemon.Daemon.SetDNSTopLevelDomains:input_type -> telepresence.daemon.Domains
	6,  // 17: telepresence.daemon.Daemon.SetDNSExcludes:input_type -> telepresence.daemon.SetDNSExcludesRequest
	7,  // 18: telepresence.daemon.Daemon.SetDNSMappings:input_type -> telepresence.daemon.SetDNSMappingsRequest
	17, // 19: telepresence.daemon.Daemon.SetLogLevel:input_type -> telepresence.manager.LogLevelRequest
	10, // 20: telepresence.daemon.Daemon.TranslateEnvIPs:input_type -> telepresence.daemon.Environment
	16, // 21: telepresence.daemon.Daemon.WaitForNetwork:input_type -> google.protobuf.Empty
	8,  // 22: telepresence.daemon.Daemon.WaitForAgentIP:input_type -> telepresence.daemon.WaitForAgentIPRequest
	13, // 23: telepresence.daemon.Daemon.Version:output_type -> telepresence.common.VersionInfo
	0,  // 24: telepresence.daemon.Daemon.Status:output_type -> telepresence.daemon.DaemonStatus
	16, // 25: telepresence.daemon.Daemon.Quit:output_type -> google.protobuf.Empty
	0,  // 26: telepresence.daemon.Daemon.Connect:output_type -> telepresence.daemon.DaemonStatus
	16, // 27: telepresence.daemon.Daemon.Disconnect:output_type -> google.protobuf.Empty
	5,  // 28: telepresence.daemon.Daemon.GetNetworkConfig:output_type -> telepresence.daemon.NetworkConfig
	16, // 29: telepresence.daemon.Daemon.SetDNSTopLevelDomains:output_type -> google.protobuf.Empty
	16, // 30: telepresence.daemon.Daemon.SetDNSExcludes:output_type -> google.protobuf.Empty
	16, // 31: telepresence.daemon.Daemon.SetDNSMappings:output_type -> google.protobuf.Empty
	16, // 32: telepresence.daemon.Daemon.SetLogLevel:output_type -> google.protobuf.Empty
	10, // 33: telepresence.daemon.Daemon.TranslateEnvIPs:output_type -> telepresence.daemon.Environment
	16, // 34: telepresence.daemon.Daemon.WaitForNetwork:output_type -> google.protobuf.Empty
	9,  // 35: telepresence.daemon.Daemon.WaitForAgentIP:output_type -> telepresence.daemon.WaitForAgentIPResponse
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_daemon_daemon_proto_init() }
func file_daemon_daemon_proto_init() {
	if File_daemon_daemon_proto != nil {
		return
	}
	file_daemon_daemon_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_daemon_proto_rawDesc), len(file_daemon_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_daemon_proto_msgTypes,
	}.Build()
	File_daemon_daemon_proto = out.File
	file_daemon_daemon_proto_goTypes = nil
	file_daemon_daemon_proto_depIdxs = nil
}
