// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: daemon/daemon.proto

package daemon

import (
	common "github.com/telepresenceio/telepresence/rpc/v2/common"
	manager "github.com/telepresenceio/telepresence/rpc/v2/manager"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaemonStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Managed        bool                   `protobuf:"varint,2,opt,name=managed,proto3" json:"managed,omitempty"`
	OutboundConfig *NetworkConfig         `protobuf:"bytes,4,opt,name=outbound_config,json=outboundConfig,proto3" json:"outbound_config,omitempty"`
	Version        *common.VersionInfo    `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DaemonStatus) Reset() {
	*x = DaemonStatus{}
	mi := &file_daemon_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatus) ProtoMessage() {}

func (x *DaemonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatus.ProtoReflect.Descriptor instead.
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonStatus) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *DaemonStatus) GetOutboundConfig() *NetworkConfig {
	if x != nil {
		return x.OutboundConfig
	}
	return nil
}

func (x *DaemonStatus) GetVersion() *common.VersionInfo {
	if x != nil {
		return x.Version
	}
	return nil
}

type Domains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domains) Reset() {
	*x = Domains{}
	mi := &file_daemon_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domains) ProtoMessage() {}

func (x *Domains) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domains.ProtoReflect.Descriptor instead.
func (*Domains) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *Domains) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type DNSMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AliasFor      string                 `protobuf:"bytes,2,opt,name=alias_for,json=aliasFor,proto3" json:"alias_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSMapping) Reset() {
	*x = DNSMapping{}
	mi := &file_daemon_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSMapping) ProtoMessage() {}

func (x *DNSMapping) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSMapping.ProtoReflect.Descriptor instead.
func (*DNSMapping) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *DNSMapping) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSMapping) GetAliasFor() string {
	if x != nil {
		return x.AliasFor
	}
	return ""
}

// DNS configuration for the local DNS resolver
type DNSConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// local_address is the address and port of the local DNS server.
	// In netip.AddrPort binary form.
	LocalAddresses [][]byte `protobuf:"bytes,1,rep,name=local_addresses,json=localAddresses,proto3" json:"local_addresses,omitempty"`
	// vif_address is the address and port that the DNS server uses on the Telepresence VIF. Only used by Linux systems.
	// In netip.AddrPort binary form.
	VifAddress []byte `protobuf:"bytes,2,opt,name=vif_address,json=vifAddress,proto3" json:"vif_address,omitempty"`
	// Suffixes to exclude
	ExcludeSuffixes []string `protobuf:"bytes,3,rep,name=exclude_suffixes,json=excludeSuffixes,proto3" json:"exclude_suffixes,omitempty"`
	// Suffixes to include. Has higher prio than the excludes
	IncludeSuffixes []string `protobuf:"bytes,4,rep,name=include_suffixes,json=includeSuffixes,proto3" json:"include_suffixes,omitempty"`
	// Exclude are a list of hostname that the DNS resolver will not resolve even if they exist.
	Excludes []string `protobuf:"bytes,8,rep,name=excludes,proto3" json:"excludes,omitempty"`
	// DNSMapping contains a hostname and its associated alias. When requesting the name, the intended behavior is
	// to resolve the alias instead.
	Mappings []*DNSMapping `protobuf:"bytes,9,rep,name=mappings,proto3" json:"mappings,omitempty"`
	// The maximum time wait for a cluster side host lookup.
	LookupTimeout *durationpb.Duration `protobuf:"bytes,6,opt,name=lookup_timeout,json=lookupTimeout,proto3" json:"lookup_timeout,omitempty"`
	// Perform a recursion check on first connect.
	RecursionCheck bool `protobuf:"varint,5,opt,name=recursion_check,json=recursionCheck,proto3" json:"recursion_check,omitempty"`
	// If set, this error indicates why DNS is not working.
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSConfig) Reset() {
	*x = DNSConfig{}
	mi := &file_daemon_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSConfig) ProtoMessage() {}

func (x *DNSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSConfig.ProtoReflect.Descriptor instead.
func (*DNSConfig) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *DNSConfig) GetLocalAddresses() [][]byte {
	if x != nil {
		return x.LocalAddresses
	}
	return nil
}

func (x *DNSConfig) GetVifAddress() []byte {
	if x != nil {
		return x.VifAddress
	}
	return nil
}

func (x *DNSConfig) GetExcludeSuffixes() []string {
	if x != nil {
		return x.ExcludeSuffixes
	}
	return nil
}

func (x *DNSConfig) GetIncludeSuffixes() []string {
	if x != nil {
		return x.IncludeSuffixes
	}
	return nil
}

func (x *DNSConfig) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *DNSConfig) GetMappings() []*DNSMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *DNSConfig) GetLookupTimeout() *durationpb.Duration {
	if x != nil {
		return x.LookupTimeout
	}
	return nil
}

func (x *DNSConfig) GetRecursionCheck() bool {
	if x != nil {
		return x.RecursionCheck
	}
	return false
}

func (x *DNSConfig) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubnetViaWorkload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The remote IP that the DNS resolver translates into a Virtual IP to use locally.
	Subnet string `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	// The workload that the virtual IP will be routed to.
	Workload      string `protobuf:"bytes,2,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetViaWorkload) Reset() {
	*x = SubnetViaWorkload{}
	mi := &file_daemon_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetViaWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetViaWorkload) ProtoMessage() {}

func (x *SubnetViaWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetViaWorkload.ProtoReflect.Descriptor instead.
func (*SubnetViaWorkload) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *SubnetViaWorkload) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *SubnetViaWorkload) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

// NetworkConfig contains all information that the root daemon needs in order to
// establish outbound traffic to the cluster.
type NetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session makes it possible for the root daemon to identify itself as the
	// same client as the user daemon.
	Session *manager.SessionInfo `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Route subnets via given workload using virtual IPs
	SubnetViaWorkloads []*SubnetViaWorkload `protobuf:"bytes,2,rep,name=subnet_via_workloads,json=subnetViaWorkloads,proto3" json:"subnet_via_workloads,omitempty"`
	// Port mappings enforced by the TUN-device.
	PortMappings []string `protobuf:"bytes,8,rep,name=port_mappings,json=portMappings,proto3" json:"port_mappings,omitempty"`
	// Users home directory
	HomeDir string `protobuf:"bytes,3,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	// Connection namespace
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Namespace where the connected traffic-manager is installed.
	ManagerNamespace string `protobuf:"bytes,9,opt,name=manager_namespace,json=managerNamespace,proto3" json:"manager_namespace,omitempty"`
	// Mapped namespaces
	MappedNamespaces []string `protobuf:"bytes,10,rep,name=mapped_namespaces,json=mappedNamespaces,proto3" json:"mapped_namespaces,omitempty"`
	// Kubernetes flags
	KubeFlags map[string]string `protobuf:"bytes,5,rep,name=kube_flags,json=kubeFlags,proto3" json:"kube_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Kubeconfig YAML, if not to be loaded from file.
	KubeconfigData []byte `protobuf:"bytes,6,opt,name=kubeconfig_data,json=kubeconfigData,proto3,oneof" json:"kubeconfig_data,omitempty"`
	// The completely merged client Config, unless daemon runs embedded
	ClientConfig  []byte `protobuf:"bytes,7,opt,name=client_config,json=clientConfig,proto3,oneof" json:"client_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_daemon_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkConfig) GetSession() *manager.SessionInfo {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *NetworkConfig) GetSubnetViaWorkloads() []*SubnetViaWorkload {
	if x != nil {
		return x.SubnetViaWorkloads
	}
	return nil
}

func (x *NetworkConfig) GetPortMappings() []string {
	if x != nil {
		return x.PortMappings
	}
	return nil
}

func (x *NetworkConfig) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

func (x *NetworkConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NetworkConfig) GetManagerNamespace() string {
	if x != nil {
		return x.ManagerNamespace
	}
	return ""
}

func (x *NetworkConfig) GetMappedNamespaces() []string {
	if x != nil {
		return x.MappedNamespaces
	}
	return nil
}

func (x *NetworkConfig) GetKubeFlags() map[string]string {
	if x != nil {
		return x.KubeFlags
	}
	return nil
}

func (x *NetworkConfig) GetKubeconfigData() []byte {
	if x != nil {
		return x.KubeconfigData
	}
	return nil
}

func (x *NetworkConfig) GetClientConfig() []byte {
	if x != nil {
		return x.ClientConfig
	}
	return nil
}

type SetDNSExcludesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Excludes      []string               `protobuf:"bytes,1,rep,name=excludes,proto3" json:"excludes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDNSExcludesRequest) Reset() {
	*x = SetDNSExcludesRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDNSExcludesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDNSExcludesRequest) ProtoMessage() {}

func (x *SetDNSExcludesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDNSExcludesRequest.ProtoReflect.Descriptor instead.
func (*SetDNSExcludesRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *SetDNSExcludesRequest) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

type SetDNSMappingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mappings      []*DNSMapping          `protobuf:"bytes,1,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDNSMappingsRequest) Reset() {
	*x = SetDNSMappingsRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDNSMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDNSMappingsRequest) ProtoMessage() {}

func (x *SetDNSMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDNSMappingsRequest.ProtoReflect.Descriptor instead.
func (*SetDNSMappingsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *SetDNSMappingsRequest) GetMappings() []*DNSMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type WaitForAgentIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForAgentIPRequest) Reset() {
	*x = WaitForAgentIPRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForAgentIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForAgentIPRequest) ProtoMessage() {}

func (x *WaitForAgentIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForAgentIPRequest.ProtoReflect.Descriptor instead.
func (*WaitForAgentIPRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *WaitForAgentIPRequest) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *WaitForAgentIPRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *WaitForAgentIPRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type WaitForAgentIPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The local IP of the agent (might be virtual)
	LocalIp       []byte `protobuf:"bytes,1,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForAgentIPResponse) Reset() {
	*x = WaitForAgentIPResponse{}
	mi := &file_daemon_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForAgentIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForAgentIPResponse) ProtoMessage() {}

func (x *WaitForAgentIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForAgentIPResponse.ProtoReflect.Descriptor instead.
func (*WaitForAgentIPResponse) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *WaitForAgentIPResponse) GetLocalIp() []byte {
	if x != nil {
		return x.LocalIp
	}
	return nil
}

type LookupIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupIPRequest) Reset() {
	*x = LookupIPRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupIPRequest) ProtoMessage() {}

func (x *LookupIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupIPRequest.ProtoReflect.Descriptor instead.
func (*LookupIPRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *LookupIPRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupIPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP in netip.Addr binary form
	Ip            []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupIPResponse) Reset() {
	*x = LookupIPResponse{}
	mi := &file_daemon_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupIPResponse) ProtoMessage() {}

func (x *LookupIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupIPResponse.ProtoReflect.Descriptor instead.
func (*LookupIPResponse) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *LookupIPResponse) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           map[string]string      `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_daemon_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *Environment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ResolvePortRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host is the name or IP-address of the targeted host.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// port can be symbolic if the host is the name of a service, and can be suffixed with /{tcp|udp}.
	Port          string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePortRequest) Reset() {
	*x = ResolvePortRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePortRequest) ProtoMessage() {}

func (x *ResolvePortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePortRequest.ProtoReflect.Descriptor instead.
func (*ResolvePortRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *ResolvePortRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ResolvePortRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type ResolvePortResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host_port is a iputil.ProtoAddrPort in binary format
	HostPort      []byte `protobuf:"bytes,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePortResponse) Reset() {
	*x = ResolvePortResponse{}
	mi := &file_daemon_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePortResponse) ProtoMessage() {}

func (x *ResolvePortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePortResponse.ProtoReflect.Descriptor instead.
func (*ResolvePortResponse) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *ResolvePortResponse) GetHostPort() []byte {
	if x != nil {
		return x.HostPort
	}
	return nil
}

type ReroutePortRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host_port is a iputil.ProtoAddrPort in binary format
	DstHostPort []byte `protobuf:"bytes,1,opt,name=dst_host_port,json=dstHostPort,proto3" json:"dst_host_port,omitempty"`
	// port is will be rerouted to the host_port.
	SrcPort       uint32 `protobuf:"varint,2,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReroutePortRequest) Reset() {
	*x = ReroutePortRequest{}
	mi := &file_daemon_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReroutePortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReroutePortRequest) ProtoMessage() {}

func (x *ReroutePortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReroutePortRequest.ProtoReflect.Descriptor instead.
func (*ReroutePortRequest) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *ReroutePortRequest) GetDstHostPort() []byte {
	if x != nil {
		return x.DstHostPort
	}
	return nil
}

func (x *ReroutePortRequest) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

type QuitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set to true when the root daemon runs as a service.
	RootDaemonWillContinue bool `protobuf:"varint,1,opt,name=root_daemon_will_continue,json=rootDaemonWillContinue,proto3" json:"root_daemon_will_continue,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *QuitResponse) Reset() {
	*x = QuitResponse{}
	mi := &file_daemon_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitResponse) ProtoMessage() {}

func (x *QuitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitResponse.ProtoReflect.Descriptor instead.
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *QuitResponse) GetRootDaemonWillContinue() bool {
	if x != nil {
		return x.RootDaemonWillContinue
	}
	return false
}

type Activity struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Activity *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	// session_end is true when this is the final Activity message emitted
	// before the root daemon's session terminates. The metrics fields below
	// are only meaningful on such terminal messages; intermediate liveness
	// pings leave them at zero.
	SessionEnd bool `protobuf:"varint,2,opt,name=session_end,json=sessionEnd,proto3" json:"session_end,omitempty"`
	// session_duration is how long the session was active, set on the
	// terminal message only.
	SessionDuration *durationpb.Duration `protobuf:"bytes,3,opt,name=session_duration,json=sessionDuration,proto3" json:"session_duration,omitempty"`
	// outbound_tunnels counts the number of outbound tunnels the root daemon
	// established during the session (one per accepted local connection that
	// was streamed to the cluster). DNS pipes are not counted.
	OutboundTunnels int64 `protobuf:"varint,4,opt,name=outbound_tunnels,json=outboundTunnels,proto3" json:"outbound_tunnels,omitempty"`
	// outbound_tunnel_errors counts attempts that failed to establish an
	// outbound tunnel (manager dial failure, agent unreachable, recursive
	// VIF dispatch, etc).
	OutboundTunnelErrors int64 `protobuf:"varint,5,opt,name=outbound_tunnel_errors,json=outboundTunnelErrors,proto3" json:"outbound_tunnel_errors,omitempty"`
	// incoming_dials counts dial requests received by the dial watchers from
	// traffic-agents during intercepts (one per WatchDial frame).
	IncomingDials int64 `protobuf:"varint,6,opt,name=incoming_dials,json=incomingDials,proto3" json:"incoming_dials,omitempty"`
	// incoming_dial_errors counts incoming dials that could not be served
	// (manager tunnel open failure, stream creation failure, etc).
	IncomingDialErrors int64 `protobuf:"varint,7,opt,name=incoming_dial_errors,json=incomingDialErrors,proto3" json:"incoming_dial_errors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_daemon_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_daemon_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *Activity) GetActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *Activity) GetSessionEnd() bool {
	if x != nil {
		return x.SessionEnd
	}
	return false
}

func (x *Activity) GetSessionDuration() *durationpb.Duration {
	if x != nil {
		return x.SessionDuration
	}
	return nil
}

func (x *Activity) GetOutboundTunnels() int64 {
	if x != nil {
		return x.OutboundTunnels
	}
	return 0
}

func (x *Activity) GetOutboundTunnelErrors() int64 {
	if x != nil {
		return x.OutboundTunnelErrors
	}
	return 0
}

func (x *Activity) GetIncomingDials() int64 {
	if x != nil {
		return x.IncomingDials
	}
	return 0
}

func (x *Activity) GetIncomingDialErrors() int64 {
	if x != nil {
		return x.IncomingDialErrors
	}
	return 0
}

var File_daemon_daemon_proto protoreflect.FileDescriptor

const file_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	"\x13daemon/daemon.proto\x12\x13telepresence.daemon\x1a\x14common/version.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15manager/manager.proto\"\xb7\x01\n" +
	"\fDaemonStatus\x12\x18\n" +
	"\amanaged\x18\x02 \x01(\bR\amanaged\x12K\n" +
	"\x0foutbound_config\x18\x04 \x01(\v2\".telepresence.daemon.NetworkConfigR\x0eoutboundConfig\x12:\n" +
	"\aversion\x18\x05 \x01(\v2 .telepresence.common.VersionInfoR\aversionJ\x04\b\x03\x10\x04\"#\n" +
	"\aDomains\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\"=\n" +
	"\n" +
	"DNSMapping\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\talias_for\x18\x02 \x01(\tR\baliasFor\"\x85\x03\n" +
	"\tDNSConfig\x12'\n" +
	"\x0flocal_addresses\x18\x01 \x03(\fR\x0elocalAddresses\x12\x1f\n" +
	"\vvif_address\x18\x02 \x01(\fR\n" +
	"vifAddress\x12)\n" +
	"\x10exclude_suffixes\x18\x03 \x03(\tR\x0fexcludeSuffixes\x12)\n" +
	"\x10include_suffixes\x18\x04 \x03(\tR\x0fincludeSuffixes\x12\x1a\n" +
	"\bexcludes\x18\b \x03(\tR\bexcludes\x12;\n" +
	"\bmappings\x18\t \x03(\v2\x1f.telepresence.daemon.DNSMappingR\bmappings\x12@\n" +
	"\x0elookup_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\rlookupTimeout\x12'\n" +
	"\x0frecursion_check\x18\x05 \x01(\bR\x0erecursionCheck\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"G\n" +
	"\x11SubnetViaWorkload\x12\x16\n" +
	"\x06subnet\x18\x01 \x01(\tR\x06subnet\x12\x1a\n" +
	"\bworkload\x18\x02 \x01(\tR\bworkload\"\xec\x04\n" +
	"\rNetworkConfig\x12;\n" +
	"\asession\x18\x01 \x01(\v2!.telepresence.manager.SessionInfoR\asession\x12X\n" +
	"\x14subnet_via_workloads\x18\x02 \x03(\v2&.telepresence.daemon.SubnetViaWorkloadR\x12subnetViaWorkloads\x12#\n" +
	"\rport_mappings\x18\b \x03(\tR\fportMappings\x12\x19\n" +
	"\bhome_dir\x18\x03 \x01(\tR\ahomeDir\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12+\n" +
	"\x11manager_namespace\x18\t \x01(\tR\x10managerNamespace\x12+\n" +
	"\x11mapped_namespaces\x18\n" +
	" \x03(\tR\x10mappedNamespaces\x12P\n" +
	"\n" +
	"kube_flags\x18\x05 \x03(\v21.telepresence.daemon.NetworkConfig.KubeFlagsEntryR\tkubeFlags\x12,\n" +
	"\x0fkubeconfig_data\x18\x06 \x01(\fH\x00R\x0ekubeconfigData\x88\x01\x01\x12(\n" +
	"\rclient_config\x18\a \x01(\fH\x01R\fclientConfig\x88\x01\x01\x1a<\n" +
	"\x0eKubeFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_kubeconfig_dataB\x10\n" +
	"\x0e_client_config\"3\n" +
	"\x15SetDNSExcludesRequest\x12\x1a\n" +
	"\bexcludes\x18\x01 \x03(\tR\bexcludes\"T\n" +
	"\x15SetDNSMappingsRequest\x12;\n" +
	"\bmappings\x18\x01 \x03(\v2\x1f.telepresence.daemon.DNSMappingR\bmappings\"z\n" +
	"\x15WaitForAgentIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"3\n" +
	"\x16WaitForAgentIPResponse\x12\x19\n" +
	"\blocal_ip\x18\x01 \x01(\fR\alocalIp\"%\n" +
	"\x0fLookupIPRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10LookupIPResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\"\x82\x01\n" +
	"\vEnvironment\x12;\n" +
	"\x03env\x18\x01 \x03(\v2).telepresence.daemon.Environment.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x12ResolvePortRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\"2\n" +
	"\x13ResolvePortResponse\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\fR\bhostPort\"S\n" +
	"\x12ReroutePortRequest\x12\"\n" +
	"\rdst_host_port\x18\x01 \x01(\fR\vdstHostPort\x12\x19\n" +
	"\bsrc_port\x18\x02 \x01(\rR\asrcPort\"I\n" +
	"\fQuitResponse\x129\n" +
	"\x19root_daemon_will_continue\x18\x01 \x01(\bR\x16rootDaemonWillContinue\"\xe3\x02\n" +
	"\bActivity\x126\n" +
	"\bactivity\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bactivity\x12\x1f\n" +
	"\vsession_end\x18\x02 \x01(\bR\n" +
	"sessionEnd\x12D\n" +
	"\x10session_duration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fsessionDuration\x12)\n" +
	"\x10outbound_tunnels\x18\x04 \x01(\x03R\x0foutboundTunnels\x124\n" +
	"\x16outbound_tunnel_errors\x18\x05 \x01(\x03R\x14outboundTunnelErrors\x12%\n" +
	"\x0eincoming_dials\x18\x06 \x01(\x03R\rincomingDials\x120\n" +
	"\x14incoming_dial_errors\x18\a \x01(\x03R\x12incomingDialErrors2\xdf\n" +
	"\n" +
	"\x06Daemon\x12C\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a .telepresence.common.VersionInfo\x12C\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a!.telepresence.daemon.DaemonStatus\x12A\n" +
	"\x04Quit\x12\x16.google.protobuf.Empty\x1a!.telepresence.daemon.QuitResponse\x12P\n" +
	"\aConnect\x12\".telepresence.daemon.NetworkConfig\x1a!.telepresence.daemon.DaemonStatus\x12<\n" +
	"\n" +
	"Disconnect\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x10GetNetworkConfig\x12\x16.google.protobuf.Empty\x1a\".telepresence.daemon.NetworkConfig\x12M\n" +
	"\x15SetDNSTopLevelDomains\x12\x1c.telepresence.daemon.Domains\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0eSetDNSExcludes\x12*.telepresence.daemon.SetDNSExcludesRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x0eSetDNSMappings\x12*.telepresence.daemon.SetDNSMappingsRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vSetLogLevel\x12%.telepresence.manager.LogLevelRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x0fTranslateEnvIPs\x12 .telepresence.daemon.Environment\x1a .telepresence.daemon.Environment\x12@\n" +
	"\x0eWaitForNetwork\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12i\n" +
	"\x0eWaitForAgentIP\x12*.telepresence.daemon.WaitForAgentIPRequest\x1a+.telepresence.daemon.WaitForAgentIPResponse\x12W\n" +
	"\bLookupIP\x12$.telepresence.daemon.LookupIPRequest\x1a%.telepresence.daemon.LookupIPResponse\x12`\n" +
	"\vResolvePort\x12'.telepresence.daemon.ResolvePortRequest\x1a(.telepresence.daemon.ResolvePortResponse\x12T\n" +
	"\x11RerouteRemotePort\x12'.telepresence.daemon.ReroutePortRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0fActivityWatcher\x12\x16.google.protobuf.Empty\x1a\x1d.telepresence.daemon.Activity0\x01B6Z4github.com/telepresenceio/telepresence/rpc/v2/daemonb\x06proto3"

var (
	file_daemon_daemon_proto_rawDescOnce sync.Once
	file_daemon_daemon_proto_rawDescData []byte
)

func file_daemon_daemon_proto_rawDescGZIP() []byte {
	file_daemon_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_daemon_proto_rawDesc), len(file_daemon_daemon_proto_rawDesc)))
	})
	return file_daemon_daemon_proto_rawDescData
}

var file_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_daemon_daemon_proto_goTypes = []any{
	(*DaemonStatus)(nil),            // 0: telepresence.daemon.DaemonStatus
	(*Domains)(nil),                 // 1: telepresence.daemon.Domains
	(*DNSMapping)(nil),              // 2: telepresence.daemon.DNSMapping
	(*DNSConfig)(nil),               // 3: telepresence.daemon.DNSConfig
	(*SubnetViaWorkload)(nil),       // 4: telepresence.daemon.SubnetViaWorkload
	(*NetworkConfig)(nil),           // 5: telepresence.daemon.NetworkConfig
	(*SetDNSExcludesRequest)(nil),   // 6: telepresence.daemon.SetDNSExcludesRequest
	(*SetDNSMappingsRequest)(nil),   // 7: telepresence.daemon.SetDNSMappingsRequest
	(*WaitForAgentIPRequest)(nil),   // 8: telepresence.daemon.WaitForAgentIPRequest
	(*WaitForAgentIPResponse)(nil),  // 9: telepresence.daemon.WaitForAgentIPResponse
	(*LookupIPRequest)(nil),         // 10: telepresence.daemon.LookupIPRequest
	(*LookupIPResponse)(nil),        // 11: telepresence.daemon.LookupIPResponse
	(*Environment)(nil),             // 12: telepresence.daemon.Environment
	(*ResolvePortRequest)(nil),      // 13: telepresence.daemon.ResolvePortRequest
	(*ResolvePortResponse)(nil),     // 14: telepresence.daemon.ResolvePortResponse
	(*ReroutePortRequest)(nil),      // 15: telepresence.daemon.ReroutePortRequest
	(*QuitResponse)(nil),            // 16: telepresence.daemon.QuitResponse
	(*Activity)(nil),                // 17: telepresence.daemon.Activity
	nil,                             // 18: telepresence.daemon.NetworkConfig.KubeFlagsEntry
	nil,                             // 19: telepresence.daemon.Environment.EnvEntry
	(*common.VersionInfo)(nil),      // 20: telepresence.common.VersionInfo
	(*durationpb.Duration)(nil),     // 21: google.protobuf.Duration
	(*manager.SessionInfo)(nil),     // 22: telepresence.manager.SessionInfo
	(*timestamppb.Timestamp)(nil),   // 23: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 24: google.protobuf.Empty
	(*manager.LogLevelRequest)(nil), // 25: telepresence.manager.LogLevelRequest
}
var file_daemon_daemon_proto_depIdxs = []int32{
	5,  // 0: telepresence.daemon.DaemonStatus.outbound_config:type_name -> telepresence.daemon.NetworkConfig
	20, // 1: telepresence.daemon.DaemonStatus.version:type_name -> telepresence.common.VersionInfo
	2,  // 2: telepresence.daemon.DNSConfig.mappings:type_name -> telepresence.daemon.DNSMapping
	21, // 3: telepresence.daemon.DNSConfig.lookup_timeout:type_name -> google.protobuf.Duration
	22, // 4: telepresence.daemon.NetworkConfig.session:type_name -> telepresence.manager.SessionInfo
	4,  // 5: telepresence.daemon.NetworkConfig.subnet_via_workloads:type_name -> telepresence.daemon.SubnetViaWorkload
	18, // 6: telepresence.daemon.NetworkConfig.kube_flags:type_name -> telepresence.daemon.NetworkConfig.KubeFlagsEntry
	2,  // 7: telepresence.daemon.SetDNSMappingsRequest.mappings:type_name -> telepresence.daemon.DNSMapping
	21, // 8: telepresence.daemon.WaitForAgentIPRequest.timeout:type_name -> google.protobuf.Duration
	19, // 9: telepresence.daemon.Environment.env:type_name -> telepresence.daemon.Environment.EnvEntry
	23, // 10: telepresence.daemon.Activity.activity:type_name -> google.protobuf.Timestamp
	21, // 11: telepresence.daemon.Activity.session_duration:type_name -> google.protobuf.Duration
	24, // 12: telepresence.daemon.Daemon.Version:input_type -> google.protobuf.Empty
	24, // 13: telepresence.daemon.Daemon.Status:input_type -> google.protobuf.Empty
	24, // 14: telepresence.daemon.Daemon.Quit:input_type -> google.protobuf.Empty
	5,  // 15: telepresence.daemon.Daemon.Connect:input_type -> telepresence.daemon.NetworkConfig
	24, // 16: telepresence.daemon.Daemon.Disconnect:input_type -> google.protobuf.Empty
	24, // 17: telepresence.daemon.Daemon.GetNetworkConfig:input_type -> google.protobuf.Empty
	1,  // 18: telepresence.daemon.Daemon.SetDNSTopLevelDomains:input_type -> telepresence.daemon.Domains
	6,  // 19: telepresence.daemon.Daemon.SetDNSExcludes:input_type -> telepresence.daemon.SetDNSExcludesRequest
	7,  // 20: telepresence.daemon.Daemon.SetDNSMappings:input_type -> telepresence.daemon.SetDNSMappingsRequest
	25, // 21: telepresence.daemon.Daemon.SetLogLevel:input_type -> telepresence.manager.LogLevelRequest
	12, // 22: telepresence.daemon.Daemon.TranslateEnvIPs:input_type -> telepresence.daemon.Environment
	24, // 23: telepresence.daemon.Daemon.WaitForNetwork:input_type -> google.protobuf.Empty
	8,  // 24: telepresence.daemon.Daemon.WaitForAgentIP:input_type -> telepresence.daemon.WaitForAgentIPRequest
	10, // 25: telepresence.daemon.Daemon.LookupIP:input_type -> telepresence.daemon.LookupIPRequest
	13, // 26: telepresence.daemon.Daemon.ResolvePort:input_type -> telepresence.daemon.ResolvePortRequest
	15, // 27: telepresence.daemon.Daemon.RerouteRemotePort:input_type -> telepresence.daemon.ReroutePortRequest
	24, // 28: telepresence.daemon.Daemon.ActivityWatcher:input_type -> google.protobuf.Empty
	20, // 29: telepresence.daemon.Daemon.Version:output_type -> telepresence.common.VersionInfo
	0,  // 30: telepresence.daemon.Daemon.Status:output_type -> telepresence.daemon.DaemonStatus
	16, // 31: telepresence.daemon.Daemon.Quit:output_type -> telepresence.daemon.QuitResponse
	0,  // 32: telepresence.daemon.Daemon.Connect:output_type -> telepresence.daemon.DaemonStatus
	24, // 33: telepresence.daemon.Daemon.Disconnect:output_type -> google.protobuf.Empty
	5,  // 34: telepresence.daemon.Daemon.GetNetworkConfig:output_type -> telepresence.daemon.NetworkConfig
	24, // 35: telepresence.daemon.Daemon.SetDNSTopLevelDomains:output_type -> google.protobuf.Empty
	24, // 36: telepresence.daemon.Daemon.SetDNSExcludes:output_type -> google.protobuf.Empty
	24, // 37: telepresence.daemon.Daemon.SetDNSMappings:output_type -> google.protobuf.Empty
	24, // 38: telepresence.daemon.Daemon.SetLogLevel:output_type -> google.protobuf.Empty
	12, // 39: telepresence.daemon.Daemon.TranslateEnvIPs:output_type -> telepresence.daemon.Environment
	24, // 40: telepresence.daemon.Daemon.WaitForNetwork:output_type -> google.protobuf.Empty
	9,  // 41: telepresence.daemon.Daemon.WaitForAgentIP:output_type -> telepresence.daemon.WaitForAgentIPResponse
	11, // 42: telepresence.daemon.Daemon.LookupIP:output_type -> telepresence.daemon.LookupIPResponse
	14, // 43: telepresence.daemon.Daemon.ResolvePort:output_type -> telepresence.daemon.ResolvePortResponse
	24, // 44: telepresence.daemon.Daemon.RerouteRemotePort:output_type -> google.protobuf.Empty
	17, // 45: telepresence.daemon.Daemon.ActivityWatcher:output_type -> telepresence.daemon.Activity
	29, // [29:46] is the sub-list for method output_type
	12, // [12:29] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_daemon_daemon_proto_init() }
func file_daemon_daemon_proto_init() {
	if File_daemon_daemon_proto != nil {
		return
	}
	file_daemon_daemon_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_daemon_proto_rawDesc), len(file_daemon_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_daemon_proto_msgTypes,
	}.Build()
	File_daemon_daemon_proto = out.File
	file_daemon_daemon_proto_goTypes = nil
	file_daemon_daemon_proto_depIdxs = nil
}
