{{- if .Values.client }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traffic-manager.name" $ }}-clients
  namespace:  {{ include "traffic-manager.namespace" . }}
data:
  client.yaml: |
    {{- toYaml .Values.client | nindent 4 }}
{{- end }}
