//go:build linux

package agentinit

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/netip"
	"os"
	"runtime/debug"
	"strconv"

	"github.com/telepresenceio/clog"
	"github.com/telepresenceio/telepresence/v2/pkg/agentconfig"
	"github.com/telepresenceio/telepresence/v2/pkg/agentnft"
	"github.com/telepresenceio/telepresence/v2/pkg/nftutil"
	"github.com/telepresenceio/telepresence/v2/pkg/version"
)

type config struct {
	*agentconfig.Sidecar
}

func loadConfig() (*config, error) {
	cfgTight, ok := os.LookupEnv(agentconfig.EnvAgentConfig)
	if !ok {
		return nil, errors.New("unable to retrieve agent ConfigMap entry")
	}

	c := config{}
	var err error
	c.Sidecar, err = agentconfig.UnmarshalJSON(cfgTight)
	if err != nil {
		return nil, fmt.Errorf("unable to decode agent ConfigMap: %w", err)
	}
	return &c, nil
}

func trafficAgentUID() (uint32, error) {
	if uid, ok := os.LookupEnv(agentconfig.EnvAgentUID); ok && uid != "" {
		parsed, err := strconv.ParseUint(uid, 10, 32)
		if err != nil {
			return 0, fmt.Errorf("invalid %s %q: %w", agentconfig.EnvAgentUID, uid, err)
		}
		return uint32(parsed), nil
	}
	return uint32(os.Getuid()), nil
}

// trafficAgentOwner returns the owner match that singles out traffic originating from the
// traffic-agent. The agent is identified by its primary group when AGENT_GID is set. The
// agent's UID may be shared with an application container (it is inherited from the app's
// securityContext unless explicitly configured), so when AGENT_GID is unset (the agent config
// was generated by an older traffic-manager), the UID-based identification is used as a fallback.
func trafficAgentOwner() (agentnft.OwnerMatch, error) {
	if gid, ok, err := agentconfig.AgentGIDFromEnv(); err != nil {
		return agentnft.OwnerMatch{}, err
	} else if ok {
		return agentnft.OwnerMatch{UseGID: true, ID: gid}, nil
	}
	uid, err := trafficAgentUID()
	if err != nil {
		return agentnft.OwnerMatch{}, err
	}
	return agentnft.OwnerMatch{UseGID: false, ID: uid}, nil
}

// buildNftConfig translates the sidecar config into the agentnft ruleset config, with the
// owner resolved from this container's identity (see trafficAgentOwner).
func (c *config) buildNftConfig(loopback string, podIP netip.Addr) (agentnft.Config, error) {
	owner, err := trafficAgentOwner()
	if err != nil {
		return agentnft.Config{}, err
	}
	return agentnft.ConfigFor(c.Sidecar, loopback, podIP, owner), nil
}

func findLoopback() (string, error) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "", fmt.Errorf("failed to get network interfaces: %w", err)
	}
	for _, iface := range ifaces {
		// If the interface is down, we can't use it anyway
		if iface.Flags&net.FlagUp == 0 {
			continue
		}
		if iface.Flags&net.FlagLoopback != 0 {
			return iface.Name, nil
		}
	}
	return "", fmt.Errorf("unable to find loopback network interface")
}

// Main is the main function for the agent init container.
func Main(ctx context.Context, args ...string) error {
	debug.SetTraceback("single")
	clog.Infof(ctx, "Traffic Agent Init %s", version.Version)
	cfg, err := loadConfig()
	if err != nil {
		clog.Error(ctx, err)
		return err
	}

	lo, err := findLoopback()
	if err != nil {
		clog.Error(ctx, err)
		return err
	}

	podIP, err := netip.ParseAddr(os.Getenv("POD_IP"))
	if err != nil {
		clog.Error(ctx, err)
		return err
	}

	nftCfg, err := cfg.buildNftConfig(lo, podIP)
	if err != nil {
		clog.Error(ctx, err)
		return err
	}

	rs, err := agentnft.Build(nftCfg)
	if err != nil {
		clog.Error(ctx, err)
		return err
	}

	// The ruleset is applied as a single atomic, idempotent full-replace, so
	// re-running the init container (e.g. on pod restart) cleanly reprograms
	// the pod's network namespace.
	if err = nftutil.Apply(ctx, &rs.Ruleset); err != nil {
		clog.Error(ctx, err)
	}
	return err
}
