#!/usr/bin/env python3

"""
Given a path on the command line, create symlink from
/export/telepresence-root/<path> to <path>.

E.g. /podinfo means a symlink will be created from
/export/telepresence-root/podinfo to /podinfo.

/var, /tmp and /etc are actually symlinks to /private/var etc. on OS X. A union
mount of a symlink and a directory just has the directory overwrite the symlink
completely, so we instead do those as /private/var etc.
"""

import sys
import os


def main(path):
    if path.split("/")[1] in ("var", "etc", "tmp"):
        path = "/private" + path
    full_path = os.path.join("/export/telepresence-root", path[1:])
    parent_path = os.path.dirname(full_path)
    if not os.path.exists(parent_path):
        os.makedirs(parent_path)
    os.symlink(path, full_path)


if __name__ == '__main__':
    main(sys.argv[1])
