# /etc/newsyslog.d/telepresence-rootd.conf
# Rotate telepresence-rootd.log daily, keep 7 days, compress, restart daemon

/var/log/telepresence-rootd.log {
    daily
    rotate 7
    compress
    missingok
}
