apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traffic-manager.name" $ }}
  namespace: {{ include "traffic-manager.namespace" $ }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
data:
{{- $client := deepCopy (.Values.client | default dict) }}
{{- if .Values.nodeAgent.enabled }}
{{- $na := default dict (get $client "nodeAgent") }}
{{- if not (hasKey $na "enabled") }}
{{- $_ := set $na "enabled" true }}
{{- $_ := set $client "nodeAgent" $na }}
{{- end }}
{{- end }}
{{- if $client }}
  client.yaml: |
    {{- toYaml $client | nindent 4 }}
{{- end }}
{{- with .Values.intercept }}
{{- if .environment }}
  agent-env.yaml: |
    {{- toYaml .environment | nindent 4 }}
{{- end }}
{{- end }}
  namespace-selector.yaml: |
    {{- toYaml (mustFromJson (include "traffic-manager.namespaceSelector" $)) | nindent 4 }}
  agent-state.yaml: |
    AgentStates: {}
