// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: teleroute/service.proto

package teleroute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the semver version of the Telepresence Daemon.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// dnsServer in netip.AddrPort binary form
	DnsServer     []byte `protobuf:"bytes,2,opt,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_teleroute_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teleroute_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_teleroute_service_proto_rawDescGZIP(), []int{0}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDnsServer() []byte {
	if x != nil {
		return x.DnsServer
	}
	return nil
}

type EnslaveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interface_name is the veth interface that is moved into the Telepresence daemon's network namespace
	// to be bridged with the VIF.
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnslaveRequest) Reset() {
	*x = EnslaveRequest{}
	mi := &file_teleroute_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnslaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnslaveRequest) ProtoMessage() {}

func (x *EnslaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teleroute_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnslaveRequest.ProtoReflect.Descriptor instead.
func (*EnslaveRequest) Descriptor() ([]byte, []int) {
	return file_teleroute_service_proto_rawDescGZIP(), []int{1}
}

func (x *EnslaveRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

type Routes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each route in netip.Prefix binary form
	Routes        [][]byte `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Routes) Reset() {
	*x = Routes{}
	mi := &file_teleroute_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Routes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routes) ProtoMessage() {}

func (x *Routes) ProtoReflect() protoreflect.Message {
	mi := &file_teleroute_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routes.ProtoReflect.Descriptor instead.
func (*Routes) Descriptor() ([]byte, []int) {
	return file_teleroute_service_proto_rawDescGZIP(), []int{2}
}

func (x *Routes) GetRoutes() [][]byte {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_teleroute_service_proto protoreflect.FileDescriptor

const file_teleroute_service_proto_rawDesc = "" +
	"\n" +
	"\x17teleroute/service.proto\x12\x16telepresence.teleroute\x1a\x1bgoogle/protobuf/empty.proto\"G\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"dns_server\x18\x02 \x01(\fR\tdnsServer\"7\n" +
	"\x0eEnslaveRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\" \n" +
	"\x06Routes\x12\x16\n" +
	"\x06routes\x18\x01 \x03(\fR\x06routes2\xe8\x01\n" +
	"\tTeleroute\x12D\n" +
	"\x04Info\x12\x16.google.protobuf.Empty\x1a$.telepresence.teleroute.InfoResponse\x12L\n" +
	"\n" +
	"EnslaveVIF\x12&.telepresence.teleroute.EnslaveRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\vWatchRoutes\x12\x16.google.protobuf.Empty\x1a\x1e.telepresence.teleroute.Routes0\x01B9Z7github.com/telepresenceio/telepresence/rpc/v2/telerouteb\x06proto3"

var (
	file_teleroute_service_proto_rawDescOnce sync.Once
	file_teleroute_service_proto_rawDescData []byte
)

func file_teleroute_service_proto_rawDescGZIP() []byte {
	file_teleroute_service_proto_rawDescOnce.Do(func() {
		file_teleroute_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_teleroute_service_proto_rawDesc), len(file_teleroute_service_proto_rawDesc)))
	})
	return file_teleroute_service_proto_rawDescData
}

var file_teleroute_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_teleroute_service_proto_goTypes = []any{
	(*InfoResponse)(nil),   // 0: telepresence.teleroute.InfoResponse
	(*EnslaveRequest)(nil), // 1: telepresence.teleroute.EnslaveRequest
	(*Routes)(nil),         // 2: telepresence.teleroute.Routes
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_teleroute_service_proto_depIdxs = []int32{
	3, // 0: telepresence.teleroute.Teleroute.Info:input_type -> google.protobuf.Empty
	1, // 1: telepresence.teleroute.Teleroute.EnslaveVIF:input_type -> telepresence.teleroute.EnslaveRequest
	3, // 2: telepresence.teleroute.Teleroute.WatchRoutes:input_type -> google.protobuf.Empty
	0, // 3: telepresence.teleroute.Teleroute.Info:output_type -> telepresence.teleroute.InfoResponse
	3, // 4: telepresence.teleroute.Teleroute.EnslaveVIF:output_type -> google.protobuf.Empty
	2, // 5: telepresence.teleroute.Teleroute.WatchRoutes:output_type -> telepresence.teleroute.Routes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teleroute_service_proto_init() }
func file_teleroute_service_proto_init() {
	if File_teleroute_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_teleroute_service_proto_rawDesc), len(file_teleroute_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teleroute_service_proto_goTypes,
		DependencyIndexes: file_teleroute_service_proto_depIdxs,
		MessageInfos:      file_teleroute_service_proto_msgTypes,
	}.Build()
	File_teleroute_service_proto = out.File
	file_teleroute_service_proto_goTypes = nil
	file_teleroute_service_proto_depIdxs = nil
}
