name: Go Dependency Submission
on:
  push:
    branches:
      - release/v2

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      # generates the embedded dc-cli.json that the build target imports
      - name: "Build dependencies"
        run: make build-deps

      - name: Run snapshot action
        uses: actions/go-dependency-submission@v2
        with:
          go-mod-path: go.mod
          go-build-target: cmd/telepresence/main.go
